export {
  completeRound,
  createInitialRoundState,
  createRoundState,
  difficultyForGridIndex,
  expireRound,
  interruptRound,
  maskingPolicyForGridIndex,
  skipGrid,
  startRound,
  submitSwipe,
  tickTimer,
  type RoundState,
  type SubmitSwipeResult,
} from './round-state-manager.js';
