import type { SampleThemeWords } from '../types.js';

/**
 * Generated from docs/design/word-lists — do not hand-edit.
 * Regenerate with `node scripts/generate-word-lists.mjs` after the source
 * JSON files change (rebuild the engine first: `npm run build`).
 */
export const ENGLISH_WORD_LIST_THEMES: readonly SampleThemeWords[] = [
  {
    themeId: "en-a-anatomy",
    label: "Anatomy",
    difficultyTier: "A",
    wordsByLength: {
      4: ["HAIR","HAND","IRIS","KNEE","LUNG","NAIL","NECK","NOSE","SKIN","VEIN"],
      5: ["ANKLE","AORTA","BLOOD","BRAIN","ELBOW","FEMUR","GLAND","HEART","LIVER","MOUTH","NERVE","OVARY","SCALP","THIGH","THUMB","TIBIA","TOOTH"],
      6: ["ARTERY","BREAST","EYELID","FINGER","KIDNEY","LARYNX","MUSCLE","PELVIS","RADIUS","RETINA","THORAX","THROAT","TONGUE"],
      7: ["ABDOMEN","BLADDER","EARDRUM","EYELASH","FOREARM","HUMERUS","KNEECAP","PHARYNX","STERNUM","STOMACH","TRACHEA"],
    },
  },
  {
    themeId: "en-a-animals",
    label: "Animals",
    difficultyTier: "A",
    wordsByLength: {
      4: ["CRAB","CROW","DEER","DOVE","DUCK","FLEA","FROG","GOAT","GULL","HAWK","IBIS","KIWI","LAMB","LION","LYNX","MARE","MITE","MOLE","MOTH","MULE","ORCA","PONY","PUMA","SEAL","SLUG","SWAN","TICK","TOAD","TUNA","WASP","WOLF","WORM","ZEBU"],
      5: ["CRANE","DINGO","EAGLE","GOOSE","HERON","HORSE","HUSKY","HYENA","KOALA","LLAMA","LOUSE","MACAW","MOOSE","MOUSE","OTTER","PANDA","QUAIL","RAVEN","SHARK","SHEEP","SHELL","SKUNK","SNAIL","SNAKE","SNIPE","SQUID","STORK","TAPIR","TIGER","TROUT","VIPER","WHALE","ZEBRA"],
      6: ["CONDOR","COUGAR","CUCKOO","DONKEY","ERMINE","FALCON","GROUSE","HORNET","IGUANA","JACKAL","JAGUAR","LIZARD","LOCUST","MAGPIE","MARTIN","MONKEY","MUSSEL","OYSTER","PARROT","PIGEON","RABBIT","SALMON","SCARAB","SHRIMP","SPIDER","SPONGE","TOUCAN","TURKEY","TURTLE","URCHIN","WALRUS","WEASEL"],
      7: ["BUZZARD","CRICKET","DOLPHIN","FIREFLY","GAZELLE","GIRAFFE","GORILLA","GRIZZLY","HAMSTER","LADYBUG","LEOPARD","LOBSTER","MAMMOTH","MUSTANG","OPOSSUM","OSTRICH","PANTHER","PEACOCK","PEAFOWL","PELICAN","PENGUIN","PIRANHA","PITBULL","RACCOON","ROOSTER","SARDINE","SEAGULL","SPARROW","TERMITE","VULTURE","WARBLER"],
    },
  },
  {
    themeId: "en-a-clothes-accessories",
    label: "Clothes & Accessories",
    difficultyTier: "A",
    wordsByLength: {
      4: ["BELT","BOOT","CAPE","COAT","CUFF","GARB","GOWN","JEAN","KEPI","KILT","MASK","ROBE","SARI","SHOE","SILK","SOCK","SUIT","TUTU","VEIL","VEST","WOOL"],
      5: ["APRON","BERET","BURQA","CLOAK","DENIM","FROCK","GILET","GLOVE","KIPPA","LINEN","LYCRA","NIQAB","NYLON","PANTS","PARKA","PURSE","SCARF","SHAWL","SHIRT","SKIRT","TUNIC"],
      6: ["ANORAK","ATTIRE","BIKINI","BLAZER","BLOUSE","BONNET","BOXERS","BRIEFS","BUCKLE","BUTTON","CAFTAN","CLOTHE","COLLAR","CORSET","COTTON","CRAVAT","FLEECE","GIRDLE","HELMET","HOODIE","JERSEY","KIMONO","MOHAIR","OUTFIT","POCKET","PONCHO","PYJAMA","SANDAL","SARONG","SCRUBS","SHORTS","SLEEVE","STRAPS","TIGHTS","TRUNKS","TURBAN","TUXEDO","VELVET","WALLET","ZIPPER"],
      7: ["APPAREL","CATSUIT","CHEMISE","FASHION","GARMENT","HANDBAG","HOMBURG","LEATHER","MAGENTA","MITTENS","MUFFLER","NECKTIE","SNEAKER","STYLIST","SWEATER","TOPCOAT","UNIFORM"],
    },
  },
  {
    themeId: "en-a-fruits",
    label: "Fruits",
    difficultyTier: "A",
    wordsByLength: {
      4: ["LIME","PEAR","PLUM"],
      5: ["APPLE","GRAPE","GUAVA","LEMON","MANGO","MELON","OLIVE","PEACH","PECAN"],
      6: ["BANANA","CHERRY","CITRON","JUJUBE","LOQUAT","LYCHEE","ORANGE","PAPAYA","PEANUT","POMELO","TOMATO"],
      7: ["APRICOT","AVOCADO","COCONUT","KUMQUAT","PUMPKIN","RAISINS","RHUBARB","VANILLA"],
    },
  },
  {
    themeId: "en-a-vegetables",
    label: "Vegetables",
    difficultyTier: "A",
    wordsByLength: {
      4: ["CORN","GUAR","LEEK"],
      5: ["CRESS","ONION"],
      6: ["CARROT","CELERY","CHIVES","ENDIVE","GARLIC","GINGER","LENTIL","MANIOC","POTATO","RADISH","SPROUT","SQUASH","TURNIP"],
      7: ["ARUGULA","CABBAGE","LETTUCE","PARSNIP","SHALLOT","SOYBEAN","SPINACH","TRUFFLE"],
    },
  },
  {
    themeId: "en-a-musical-instruments",
    label: "Musical Instruments",
    difficultyTier: "A",
    wordsByLength: {
      4: ["BASS","GONG","HARP","HORN","LUTE","LYRE","OBOE","TUBA"],
      5: ["BANJO","CELLO","DRUMS","FLUTE","KAZOO","ORGAN","PIANO","SITAR","VIOLA"],
      6: ["CYMBAL","GUITAR","VIOLIN"],
      7: ["BAGPIPE","BASSOON","DARBUKA","MARIMBA","OCARINA","TRUMPET","UKULELE"],
    },
  },
  {
    themeId: "en-a-occupations",
    label: "Occupations",
    difficultyTier: "A",
    wordsByLength: {
      4: ["CHEF","COOK","KING","MAID","MONK","POET"],
      5: ["ACTOR","BAKER","CLERK","COACH","CROOK","DIVER","GUARD","GUIDE","JUDGE","MASON","MAYOR","MINER","MODEL","NURSE","PILOT","QUEEN","RABBI","SCOUT","SMITH","TILER","VALET","VICAR"],
      6: ["ARCHER","ARTIST","AUTHOR","BANKER","BARBER","BARMAN","BROKER","BUTLER","CONSUL","DEPUTY","DOCTOR","DRIVER","EDITOR","EXPERT","FARMER","GOLFER","HUNTER","INTERN","JAILER","JESTER","JOCKEY","LAWYER","PASTOR","PRIEST","PRINCE","RANGER","SAILOR","SCRIBE","SELLER","SINGER","TAILOR","TELLER","TRADER","TYPIST","WAITER","WARDEN","WEAVER","WELDER","WRITER"],
      7: ["ADVISER","ANALYST","ATHLETE","BASSIST","BUILDER","BURGLAR","BUTCHER","CAPTAIN","CASHIER","CATERER","CELLIST","CHEMIST","CLEANER","CORONER","DENTIST","DOORMAN","DRAFTER","DRUMMER","EMPEROR","FIREMAN","FLORIST","FLUTIST","GENERAL","HARPIST","JANITOR","JEWELER","LABORER","MANAGER","MIDWIFE","PAINTER","PEDDLER","PIANIST","PLUMBER","POSTMAN","RANCHER","REFEREE","RETIREE","SENATOR","SHERIFF","SOLDIER","STEWARD","STUDENT","SURGEON","SWIMMER","TEACHER","VETERAN","WARRIOR"],
    },
  },
  {
    themeId: "en-a-sports",
    label: "Sports",
    difficultyTier: "A",
    wordsByLength: {
      4: ["AXEL","BALL","BUNT","CLUB","GOAL","GOLF","HOOP","JUDO","JUMP","LUGE","POLE","POLO","PUCK","RACE","TEAM"],
      5: ["CATCH","RACER","RELAY","RUGBY","SCUBA","SKATE","STICK"],
      6: ["BOCCIE","BOXING","CLEATS","GOALIE","HOCKEY","HURDLE","JOGGER","KARATE","LEAGUE","MALLET","PLAYER","RACING","RACKET","ROWING","SLALOM","SOCCER","STRIKE","TENNIS","UMPIRE","VOLLEY","WEIGHT","WICKET"],
      7: ["ARCHERY","BOWLING","COMPETE","CROQUET","CURLING","CYCLING","FENCING","FIELDER","PARKOUR","PITCHER","RAFTING","SLEDDER"],
    },
  },
  {
    themeId: "en-a-modes-of-transport",
    label: "Modes of Transport",
    difficultyTier: "A",
    wordsByLength: {
      4: ["AUTO","BIKE","BOAT","CART","JEEP","LIMO","SHIP","TAXI"],
      5: ["BARGE","BUGGY","CANOE","FERRY","LORRY","METRO","TRAIN","TRUCK","WAGON","YACHT"],
      6: ["GALLEY","GLIDER","LITTER","ROCKET","SLEIGH","SUBWAY","VESSEL"],
      7: ["BICYCLE","CARAVAN","CRUISER","FRIGATE","GONDOLA","MINIBUS","SCOOTER","TRAMWAY"],
    },
  },
  {
    themeId: "en-a-countries",
    label: "Countries",
    difficultyTier: "A",
    wordsByLength: {
      4: ["CUBA","FIJI","IRAN","IRAQ","MALI","NIUE","OMAN","PERU","TOGO"],
      5: ["BENIN","BURMA","CHILE","CHINA","CONGO","EGYPT","GABON","GHANA","HAITI","INDIA","ITALY","JAPAN","KENYA","LIBYA","MALTA","NAURU","NEPAL","NIGER","PALAU","QATAR","SAMOA","SPAIN","SUDAN","SYRIA","TONGA","YEMEN"],
      6: ["ANGOLA","BELIZE","BHUTAN","BRAZIL","BRUNEI","CANADA","CYPRUS","FRANCE","GAMBIA","GREECE","GUINEA","GUYANA","ISRAEL","JORDAN","KOSOVO","KUWAIT","LATVIA","MALAWI","MEXICO","MONACO","NORWAY","PANAMA","POLAND","RUSSIA","RWANDA","SERBIA","SWEDEN","TAIWAN","TUVALU","UGANDA","ZAMBIA"],
      7: ["ALBANIA","ALGERIA","ANDORRA","ARMENIA","AUSTRIA","BAHAMAS","BAHRAIN","BELARUS","BELGIUM","BOLIVIA","BURUNDI","COMOROS","CROATIA","DENMARK","ECUADOR","ERITREA","ESTONIA","FINLAND","GEORGIA","GERMANY","GRENADA","HUNGARY","ICELAND","IRELAND","JAMAICA","LEBANON","LESOTHO","LIBERIA","MOLDOVA","MOROCCO","NAMIBIA","NIGERIA","ROMANIA","SENEGAL","SOMALIA","TUNISIA","UKRAINE","URUGUAY","VANUATU","VIETNAM"],
    },
  },
  {
    themeId: "en-a-vegan-food",
    label: "Vegan Food",
    difficultyTier: "A",
    wordsByLength: {
      4: ["MINT","SAGE","SALT"],
      5: ["ACORN","ANISE","BASIL","CLOVE","CUMIN","PASTA","PENNE","SUMAC","THYME"],
      6: ["ALMOND","CASHEW","FENNEL","PEPPER","RAISIN","WALNUT","WASABI"],
      7: ["CARAWAY","CHICORY","CHUTNEY","KETCHUP","MUSTARD","OREGANO","PAPRIKA","PARSLEY","SAFFRON","VINEGAR"],
    },
  },
  {
    themeId: "en-a-non-vegan-food",
    label: "Non-Vegan Food",
    difficultyTier: "A",
    wordsByLength: {
      4: ["BEEF","PORK","VEAL"],
      5: ["BACON","SQUAB"],
      6: ["BUTTER","CHEESE","MUTTON","OMELET"],
      7: ["CHEDDAR","CHICKEN","SAUSAGE"],
    },
  },
  {
    themeId: "en-b-alcoholic-drinks",
    label: "Alcoholic Drinks",
    difficultyTier: "B",
    wordsByLength: {
      4: ["ARAK","BEER","MEAD","OUZO","RAKI","SAKE","WINE"],
      5: ["CIDER","LAGER","PORTO","VODKA"],
      6: ["BRANDY","COGNAC","GRAPPA","KIRSCH","LIQUOR","PASTIS","SHERRY"],
      7: ["BOURBON","CACHACA","MASTIKA","SAMBUCA","SANGRIA","TEQUILA","WHISKEY"],
    },
  },
  {
    themeId: "en-b-hand-tools",
    label: "Hand Tools",
    difficultyTier: "B",
    wordsByLength: {
      4: ["GLUE","WIRE"],
      5: ["CLAMP","DRILL","RULER"],
      6: ["CHISEL","HAMMER","JIGSAW","WRENCH"],
      7: ["HACKSAW","SCRAPER","STAPLER"],
    },
  },
  {
    themeId: "en-b-furniture",
    label: "Furniture",
    difficultyTier: "B",
    wordsByLength: {
      4: ["CRIB","DESK","SOFA"],
      5: ["BENCH","CHAIR","COUCH","FUTON","STOOL","TABLE"],
      6: ["BUFFET","CRADLE","THRONE"],
      7: ["DRESSER","HAMMOCK","HASSOCK","JUKEBOX"],
    },
  },
  {
    themeId: "en-b-tableware-kitchen-utensils",
    label: "Tableware & Kitchen Utensils",
    difficultyTier: "B",
    wordsByLength: {
      4: ["BOWL","FORK","MOLD","OVEN"],
      5: ["CROCK","FRYER","GLASS","GRILL","KNIFE","LADLE","PLATE","RICER","SHEAR","SIEVE","SPOON","STOVE","TONGS","TOWEL","WHISK"],
      6: ["BASKET","BOTTLE","CANDLE","CARAFE","COOKER","FRIDGE","FUNNEL","GRATER","KETTLE","NAPKIN","PEELER","SKEWER","SLICER","TEAPOT","ZESTER"],
      7: ["BLENDER","COASTER","CUTLERY","FLOWERS","FREEZER","GRIDDLE","GRINDER","INFUSER","PLATTER","POACHER","ROASTER","SPATULA","STEAMER","TOASTER"],
    },
  },
  {
    themeId: "en-b-flowers",
    label: "Flowers",
    difficultyTier: "B",
    wordsByLength: {
      4: ["ARUM","LEAF","LILY","ROSE","STEM"],
      5: ["BLOOM","BROOM","LILAC","PEONY","PETAL","POPPY","SPINE","TULIP"],
      6: ["AZALEA","MIMOSA","ORCHID","PISTIL","VIOLET","YARROW"],
      7: ["CAMELIA","JASMINE","SYRINGA","THISTLE"],
    },
  },
  {
    themeId: "en-b-bodies-of-water",
    label: "Bodies of Water",
    difficultyTier: "B",
    wordsByLength: {
      4: ["GULF","LAKE","POND","POOL"],
      5: ["CREEK","FJORD","OASIS","OCEAN","RIVER","SWAMP"],
      6: ["LAGOON","RAPIDS","SOURCE","SPRING","STREAM"],
      7: ["ESTUARY","GLACIER","ICEBERG","RIVULET","TORRENT"],
    },
  },
  {
    themeId: "en-b-plants-and-trees",
    label: "Plants and Trees",
    difficultyTier: "B",
    wordsByLength: {
      4: ["BUDS","BULB","PINE","PORE","ROOT","SEED","TWIG"],
      5: ["ALDER","BIRCH","CEDAR","FRUIT","HAZEL","MAPLE","THORN","WHEAT"],
      6: ["ACACIA","BRANCH","FLOWER","NECTAR","POLLEN","STIGMA","WILLOW"],
      7: ["COROLLA","CYPRESS","SEQUOIA"],
    },
  },
  {
    themeId: "en-c-jewelry-accessories",
    label: "Jewelry & Accessories",
    difficultyTier: "C",
    wordsByLength: {
      4: ["JADE","ONYX","OPAL","RING","RUBY"],
      5: ["AGATE","AMBER","BERYL","CHAIN","PEARL","TIARA","TOPAZ"],
      6: ["AMULET","BROOCH","DIADEM","GARNET","JASPER","QUARTZ","SPINEL","ZIRCON"],
      7: ["APATITE","AZURITE","CITRINE","CRYSTAL","DIAMOND","EARRING","EMERALD","PENDANT"],
    },
  },
  {
    themeId: "en-c-time-timekeeping",
    label: "Time & Timekeeping",
    difficultyTier: "C",
    wordsByLength: {
      4: ["HOUR","LATE","PAST","SOON","THEN","WEEK","YEAR","ZONE"],
      5: ["AFTER","DELAY","EARLY","EPOCH","MONTH","TARDY","TODAY"],
      6: ["ANNUAL","BEFORE","DECADE","FUTURE","MINUTE","MOMENT","PERIOD","SECOND"],
      7: ["CENTURY","JUBILEE","MORNING","PRESENT","SUNDIAL","TONIGHT"],
    },
  },
  {
    themeId: "en-c-mammals",
    label: "Mammals",
    difficultyTier: "C",
    wordsByLength: {
      4: ["BEAR","BOAR","HARE"],
      5: ["BISON","CAMEL","LEMUR","OKAPI"],
      6: ["BEAVER","COYOTE","MARMOT","WAPITI"],
      7: ["BUFFALO","CARIBOU","CHEETAH","MACAQUE","WALLABY"],
    },
  },
  {
    themeId: "en-c-sports-facilities",
    label: "Sports Facilities",
    difficultyTier: "C",
    wordsByLength: {
      4: ["DOJO","HALL","RINK"],
      5: ["ARENA","COURT","FIELD","PISTE"],
      6: ["COURSE"],
      7: ["CIRCUIT","STADIUM"],
    },
  },
  {
    themeId: "en-d-musical-styles",
    label: "Musical Styles",
    difficultyTier: "D",
    wordsByLength: {
      4: ["ACID","FOLK","FUNK","JAZZ","PUNK","ROCK","SOCA","SOUL","ZOUK"],
      5: ["BLUES","CONGA","MAMBO","METAL","OPERA","SALSA","SAMBA"],
      6: ["BOLERO","GOSPEL","GRUNGE","MOTOWN","REGGAE","TECHNO","TRANCE"],
      7: ["BAROQUE","BRITPOP","CALYPSO","COUNTRY","DUBSTEP","RAGTIME"],
    },
  },
  {
    themeId: "en-d-light-sources",
    label: "Light Sources",
    difficultyTier: "D",
    wordsByLength: {
      4: ["FIRE","LAMP","LAVA","MOON","NEON","STAR"],
      5: ["COMET","FLAME","FLASH","LASER","MATCH","SPARK","TORCH"],
      6: ["BEACON","METEOR","SPRITE"],
      7: ["LANTERN","LIGHTER"],
    },
  },
  {
    themeId: "en-d-car-parts",
    label: "Car Parts",
    difficultyTier: "D",
    wordsByLength: {
      4: ["AXLE","DOOR","FUEL","FUSE","LOCK","RIMS","TIRE"],
      5: ["ALARM","GAUGE","MOTOR","PEDAL","WHEEL"],
      6: ["AIRBAG","BRAKES","BUMPER","CLUTCH","FILTER","GASKET","HEATER","PISTON","WINDOW"],
      7: ["CHASSIS","CONSOLE","GEARBOX","SPOILER","STARTER","SUNROOF"],
    },
  },
  {
    themeId: "en-d-animal-body-parts",
    label: "Animal Body Parts",
    difficultyTier: "D",
    wordsByLength: {
      4: ["ARMS","BEAK","CLAW","FANG","FOOT","HOOF","HUMP","LEGS","MANE","PAWS","SPOT","TAIL","TUSK","WING"],
      5: ["GILLS","TRUNK"],
      6: ["SCALES"],
      7: ["ANTENNA","CUTICLE","FEATHER","FLIPPER","STINGER"],
    },
  },
  {
    themeId: "en-d-animal-babies",
    label: "Animal Babies",
    difficultyTier: "D",
    wordsByLength: {
      4: ["CALF","COLT","FAWN","FOAL","PUPA"],
      5: ["CHICK","ELVER","LARVA","OWLET","POULT","PUPPY","SHOAT"],
      6: ["CYGNET","EAGLET","KITTEN","MAGGOT","PIGLET"],
      7: ["GOSLING","LAMBKIN","TADPOLE"],
    },
  },
  {
    themeId: "en-d-the-calendar",
    label: "The Calendar",
    difficultyTier: "D",
    wordsByLength: {
      4: ["JULY","JUNE"],
      5: ["APRIL","ARIES","LIBRA","MARCH","VIRGO"],
      6: ["AUGUST","CANCER","FRIDAY","GEMINI","MONDAY","PISCES","SUNDAY","TAURUS"],
      7: ["SCORPIO","TUESDAY"],
    },
  },
  {
    themeId: "en-d-weather-climate",
    label: "Weather & Climate",
    difficultyTier: "D",
    wordsByLength: {
      4: ["COLD","HEAT","RAIN","TIDE","WIND"],
      5: ["CLOUD","FROST","STORM"],
      6: ["AUTUMN","SEASON","SUMMER","WINTER"],
      7: ["CYCLONE","TEMPEST","THUNDER","TORNADO","TWISTER","TYPHOON"],
    },
  },
  {
    themeId: "en-d-famous-brands",
    label: "Famous Brands",
    difficultyTier: "D",
    wordsByLength: {
      4: ["ACER","AVON","BOSE","DELL","DIOR","FILA","FUJI","LEGO","MARS","NIKE","OLAY","OREO","SONY","TWIX","VISA"],
      5: ["ASICS","CANON","CASIO","CREST","DOLBY","EVIAN","FANTA","GUCCI","HALLS","HEINZ","KNORR","KRAFT","LINDT","MAGGI","NIKON","NIVEA","NOKIA","PEPSI","PRADA","ROLEX","SANYO","SHARP","TEFAL","TWIRL","UMBRO","VICHY","WELLA","XEROX"],
      6: ["ADIDAS","ARMANI","BOUNTY","CHANEL","CRUNCH","GALAXY","GIBSON","GODIVA","HENKEL","HERMES","HOOVER","LIPTON","MATTEL","MENTOS","RAYBAN","REEBOK","REVLON","REXONA","SIGNAL","SMACKS","TAMPAX","VIAGRA"],
      7: ["AIRNESS","BARILLA","BUITONI","CADBURY","CARTIER","CLARINS","COLGATE","CRAYOLA","GRUNDIG","HISENSE","KENWOOD","KICKERS","KLEENEX","LACOSTE","LANCOME","MAIZENA","MIRINDA","NESCAFE","NUTELLA","PAMPERS","PANTENE","PERRIER","PHILIPS","SAMSUNG","SUNSILK","TOSHIBA","VERSACE"],
    },
  },
  {
    themeId: "en-d-music",
    label: "Music",
    difficultyTier: "D",
    wordsByLength: {
      4: ["ALTO","BAND","BEAT","CLEF","DUET","NOTE","SOLO","SONG","TRIO","TUNE"],
      5: ["CHORD","PITCH","TEMPO","TENOR","THEME"],
      6: ["ADAGIO","ANTHEM","ATONAL","AUBADE","BALLAD","CHORUS","MELODY","OCTAVE","RHYTHM","TIMBRE","UNISON","VOLUME"],
      7: ["CADENCE","CANTATA","CONCERT","HARMONY","QUARTET","QUINTET","SOLFEGE","SOPRANO"],
    },
  },
  {
    themeId: "en-e-liquid-containers",
    label: "Liquid Containers",
    difficultyTier: "E",
    wordsByLength: {
      4: ["CASK","EWER","TANK","VASE","VIAL"],
      5: ["BARRE","CRUET","FLASK","STEIN"],
      6: ["BEAKER","GOBLET"],
      7: ["AMPHORA"],
    },
  },
  {
    themeId: "en-e-chemical-elements",
    label: "Chemical Elements",
    difficultyTier: "E",
    wordsByLength: {
      4: ["GOLD","LEAD","ZINC"],
      5: ["ARGON","BORON","RADON","XENON"],
      6: ["BARIUM","CARBON","CERIUM","COBALT","CURIUM","ERBIUM","HELIUM","INDIUM","IODINE","NICKEL","OXYGEN","RADIUM","SODIUM","SULFUR"],
      7: ["ARSENIC","BISMUTH","BOHRIUM","BROMINE","CADMIUM","CALCIUM","DUBNIUM","IRIDIUM","KRYPTON","LITHIUM","MERCURY","SILICON","THORIUM","URANIUM"],
    },
  },
  {
    themeId: "en-e-animal-groups",
    label: "Animal Groups",
    difficultyTier: "E",
    wordsByLength: {
      4: ["BEVY","COVE","HERD","LAIR","PACK"],
      5: ["BROOD","FLOCK","HORDE","SHOAL","SWARM"],
      6: ["COLONY"],
      7: ["ROOKERY"],
    },
  },
  {
    themeId: "en-e-human-bones",
    label: "Human Bones",
    difficultyTier: "E",
    wordsByLength: {
      4: ["RIBS","ULNA"],
      5: ["INCUS","TALUS","VOMER"],
      6: ["COCCYX","FIBULA","SACRUM","STAPES","TARSUS"],
      7: ["MALLEUS","MAXILLA","PATELLA","SCAPULA"],
    },
  },
  {
    themeId: "en-e-works-of-art",
    label: "Works of Art",
    difficultyTier: "E",
    wordsByLength: {
      4: ["EPIC","HYMN","PLAY","POEM","SHOW"],
      5: ["ALBUM","DANCE","ELEGY","MOVIE","NOVEL","PHOTO","PROSE","PSALM"],
      6: ["COMEDY","EFFIGY","LITANY","SONATA","SONNET","STATUE","TATTOO"],
      7: ["EPIGRAM","MUSICAL","POTTERY","REQUIEM"],
    },
  },
  {
    themeId: "en-e-lakes-and-rivers",
    label: "Lakes and Rivers",
    difficultyTier: "E",
    wordsByLength: {
      4: ["ERIE","NESS","NILE"],
      5: ["HURON","INDUS","LEMAN","LOIRE","RHINE","SEINE","VOLGA","VOLTA"],
      6: ["BAIKAL","DANUBE","GANGES","LOMOND","MEKONG","THAMES"],
      7: ["ONTARIO","WHEATON","YANGTZE","ZAMBEZI"],
    },
  },
  {
    themeId: "en-e-currencies",
    label: "Currencies",
    difficultyTier: "E",
    wordsByLength: {
      4: ["BATH","DIME","DRAM","EURO","HWAN","INTI","KUNA","LIRA","MARK","PESO","REAL","YANG","YUAN"],
      5: ["BUDJU","DINAR","FRANC","KRONA","LIVRE","PAISA","POUND","RIYAL","RUBLE","RUPEE","SCUDO","SUCRE","ZLOTY"],
      6: ["DENIER","DINERO","DIRHAM","DOLLAR","ESCUDO","FLORIN","GINEIH","GOURDE","KORUNA","PESETA","SHEKEL","TANGKA","THALER"],
      7: ["AFGHANI","AUSTRAL","BOLIVAR","CRUZADO","DRACHMA","PENNING","PIASTRA"],
    },
  },
  {
    themeId: "en-e-languages",
    label: "Languages",
    difficultyTier: "E",
    wordsByLength: {
      4: ["THAI","URDU","ZULU"],
      5: ["CZECH","DUTCH","GREEK","HAKKA","HINDI","IRISH","MALAY","MAORI","MAYAN","SWATI","TAJIK","TAMIL","UZBEK","WELSH","XIANG"],
      6: ["ABKHAZ","ARABIC","BASQUE","BERBER","DANISH","FRENCH","GAELIC","GERMAN","HEBREW","KAZAKH","KOREAN","KYRGYZ","NEPALI","SLOVAK","SOMALI"],
      7: ["AMHARIC","BENGALI","BOSNIAN","BURMESE","CATALAN","CHINESE","ENGLISH","FINNISH","FRISIAN","ITALIAN","KURDISH","LATVIAN","MALTESE","PERSIAN","PUNJABI","QUECHUA","RUSSIAN","SERBIAN","SLOVENE","SPANISH","SWAHILI","SWEDISH","TIBETAN","TURKISH","TURKMEN","YIDDISH"],
    },
  },
  {
    themeId: "en-e-african-cities",
    label: "African Cities",
    difficultyTier: "E",
    wordsByLength: {
      4: ["KANO","LAMU","MAUN","SUEZ"],
      5: ["ACCRA","AKURE","CAIRO","DAKAR","GIZEH","LAGOS","RABAT","WARRI"],
      6: ["AGADIR","BANGUI","DOUALA","DURBAN","HARARE","IBADAN","ILORIN","KADUNA","KIGALI","KUMASI","LUSAKA","MATOLA","NIAMEY","SOWETO"],
      7: ["ABIDJAN","ALGIERS","CONAKRY","KAMPALA","MOMBASA","NAIROBI","TANGIER","TRIPOLI","YAOUNDE"],
    },
  },
  {
    themeId: "en-e-asian-cities",
    label: "Asian Cities",
    difficultyTier: "E",
    wordsByLength: {
      4: ["DOHA","XIAN"],
      5: ["DELHI","DHAKA","DUBAI","KABUL","MOSUL","OSAKA","SANAA","SEOUL","SURAT","TOKYO","WUHAN"],
      6: ["ALEPPO","ANKARA","BEIRUT","BOMBAY","JAIPUR","JEDDAH","LAHORE","MADRAS","MANILA","MOSCOW","RIYADH","TEHRAN"],
      7: ["BAGHDAD","BANGKOK","BEIJING","BISHKEK","JAKARTA","KARACHI","MASHHAD","RANGOON","TIANJIN"],
    },
  },
  {
    themeId: "en-e-european-cities",
    label: "European Cities",
    difficultyTier: "E",
    wordsByLength: {
      4: ["BONN","HAMM","LYON","NICE","RIGA","ROME","VIGO","YORK"],
      5: ["BRAGA","BREDA","BREST","DIJON","ESPOO","ESSEN","GENOA","LAHTI","LEEDS","LIEGE","LILLE","MILAN","NAMUR","PADUA","PARIS","REIMS","SOFIA","VARNA"],
      6: ["ANGERS","ATHENS","BERLIN","BOLTON","BREMEN","BRUGES","CANNES","DUBLIN","DUDLEY","FOGGIA","KAUNAS","KRAKOW","LISBON","LONDON","MADRID","MALAGA","MUNICH","NAPOLI","PRAGUE","RENNES","RIJEKA","SLOUGH","TORINO","TOULON","VENICE","VERONA","VIENNA","WARSAW"],
      7: ["BELFAST","BOLOGNA","BRESCIA","BRISTOL","CARDIFF","CATANIA","COLOGNE","CORDOBA","CRAIOVA","DRESDEN","GLASGOW","GRANADA","HAARLEM","HAMBURG","HANOVER","LEIPZIG","NEWPORT","NICOSIA","PALERMO","RAVENNA","ROSTOCK","SALERNO","SEVILLE","TALLINN","TAMPERE","VILNIUS"],
    },
  },
  {
    themeId: "en-e-south-american-cities",
    label: "South-American Cities",
    difficultyTier: "E",
    wordsByLength: {
      4: ["CALI","LEON","LIMA"],
      5: ["BELEM","NATAL","QUITO"],
      6: ["BOGOTA","MANAUS","RECIFE","SANTOS"],
      7: ["CARACAS","MARACAY","MENDOZA","ROSARIO"],
    },
  },
  {
    themeId: "en-e-world-cities",
    label: "World Cities",
    difficultyTier: "E",
    wordsByLength: {
      4: ["BERN","KIEV","LOME","OMSK","OSLO","PISA"],
      5: ["AMMAN","HANOI","KYOTO","LUXOR","MECCA","MINSK","TUNIS","TURIN"],
      6: ["ASMARA","ASTANA","BAMAKO","BILBAO","BISSAU","BOSTON","DENVER","GENOVA","LUANDA","MANAMA","MAPUTO","MASERU","MILANO","MUMBAI","OXFORD","RHODES","SYDNEY","TAIPEI","ZAGREB","ZURICH"],
      7: ["ATLANTA","CAYENNE","CHESTER","KOLKATA","LARNACA","MEMPHIS","MYKONOS","ORLANDO","PAPEETE","YEREVAN"],
    },
  },
  {
    themeId: "en-e-god-goddesses",
    label: "God & Goddesses",
    difficultyTier: "E",
    wordsByLength: {
      4: ["ARIS","CIRC","HERA","JUNO","ODIN","RAMA","THOR","ZEUS"],
      5: ["CERES","DIANA","HADES","HESTI","JANUS","SHIVA","VENUS","VESTA"],
      6: ["APOLLO","ATHENA","ISHTAR","SATURN","VISHNU","VULCAN"],
      7: ["ARTEMIS","DEMETER","JUPITER","KRISHNA","MINERVA","NEPTUNE"],
    },
  },
  {
    themeId: "en-e-car-manufacturers",
    label: "Car Manufacturers",
    difficultyTier: "E",
    wordsByLength: {
      4: ["AUDI","FIAT","FORD","OPEL","SAAB","SEAT"],
      5: ["BUICK","DACIA","DODGE","HONDA","ISUZU","LEXUS","LOTUS","MAZDA","SKODA","SMART","VOLVO"],
      6: ["HUMMER","LANCIA","NISSAN","SUBARU","SUZUKI","TOYOTA"],
      7: ["BENTLEY","BUGATTI","CITROEN","FERRARI","HYUNDAI","PEUGEOT","PONTIAC","PORSCHE","RENAULT"],
    },
  },
];
