import type { SampleThemeWords } from '../types.js';

/**
 * Generated from docs/design/word-lists — do not hand-edit.
 * Regenerate with `node scripts/generate-word-lists.mjs` after the source
 * JSON files change (rebuild the engine first: `npm run build`).
 */
export const ENGLISH_WORD_LIST_THEMES: readonly SampleThemeWords[] = [
  {
    themeId: "en-a-anatomy",
    label: "Anatomy",
    difficultyTier: "A",
    wordsByLength: {
      4: ["HAIR","HAND","IRIS","KNEE","LUNG","NAIL","NECK","NOSE","SKIN","VEIN"],
      5: ["ANKLE","AORTA","BLOOD","BRAIN","ELBOW","FEMUR","GLAND","HEART","LIVER","MOUTH","NERVE","OVARY","SCALP","THIGH","THUMB","TIBIA","TOOTH","ATERY"],
      6: ["BREAST","EYELID","FINGER","KIDNEY","LARYNX","MUSCLE","PELVIS","RADIUS","RETINA","THORAX","THROAT","TONGUE"],
      7: ["ABDOMEN","BLADDER","EARDRUM","EYELASH","FOREARM","HUMERUS","KNEECAP","PHARYNX","STERNUM","STOMACH","TRACHEA"],
    },
  },
  {
    themeId: "en-a-animals",
    label: "Animals",
    difficultyTier: "A",
    wordsByLength: {
      4: ["CRAB","CROW","DEER","DOVE","DUCK","FLEA","FROG","GOAT","GULL","HAWK","IBIS","KIWI","LAMB","LION","LYNX","MARE","MITE","MOLE","MOTH","MULE","ORCA","PONY","PUMA","SEAL","SLUG","SWAN","TICK","TOAD","TUNA","WASP","WOLF","WORM","ZEBU"],
      5: ["CRANE","DINGO","EAGLE","GOOSE","HERON","HORSE","HUSKY","HYENA","KOALA","LLAMA","LOUSE","MACAW","MOOSE","MOUSE","OTTER","PANDA","QUAIL","RAVEN","SHARK","SHEEP","SHELL","SKUNK","SNAIL","SNAKE","SNIPE","SQUID","STORK","TAPIR","TIGER","TROUT","VIPER","WHALE","ZEBRA"],
      6: ["CONDOR","CUCKOO","DONKEY","ERMINE","FALCON","GROUSE","HORNET","IGUANA","JACKAL","JAGUAR","LIZARD","LOCUST","MAGPIE","MARTIN","MUSSEL","OYSTER","PARROT","PIGEON","RABBIT","SCARAB","SHRIMP","SPIDER","SPONGE","TOUCAN","TURKEY","TURTLE","URCHIN","WALRUS","WEASEL","COUGAR","MONKEY","SALMON"],
      7: ["BUZZARD","CRICKET","DOLPHIN","FIREFLY","GAZELLE","GIRAFFE","GORILLA","GRIZZLY","HAMSTER","LADYBUG","LEOPARD","LOBSTER","MAMMOTH","MUSTANG","OPOSSUM","OSTRICH","PANTHER","PEACOCK","PEAFOWL","PELICAN","PENGUIN","PIRANHA","PITBULL","RACCOON","ROOSTER","SARDINE","SEAGULL","SPARROW","TERMITE","VULTURE","WARBLER"],
    },
  },
  {
    themeId: "en-a-clothes-accessories",
    label: "Clothes & Accessories",
    difficultyTier: "A",
    wordsByLength: {
      4: ["BELT","BOOT","CAPE","COAT","CUFF","GARB","GOWN","JEAN","KEPI","KILT","MASK","ROBE","SARI","SHOE","SILK","SOCK","SUIT","TUTU","VEIL","VEST","WOOL"],
      5: ["APRON","BERET","BURQA","CLOAK","DENIM","FROCK","GILET","KIPPA","LINEN","LYCRA","NIQAB","NYLON","PANTS","PARKA","PURSE","SCARF","SHAWL","SHIRT","SKIRT","TUNIC","GLOVE"],
      6: ["ANORAK","ATTIRE","BIKINI","BLAZER","BLOUSE","BONNET","BOXERS","BRIEFS","BUCKLE","BUTTON","CAFTAN","CLOTHE","COLLAR","CORSET","COTTON","CRAVAT","FLEECE","GIRDLE","HELMET","HOODIE","JERSEY","KIMONO","MOHAIR","OUTFIT","POCKET","PONCHO","PYJAMA","SANDAL","SARONG","SCRUBS","SHORTS","SLEEVE","STRAPS","TIGHTS","TRUNKS","TURBAN","TUXEDO","VELVET","WALLET","ZIPPER"],
      7: ["APPAREL","CATSUIT","CHEMISE","FASHION","GARMENT","HANDBAG","HOMBURG","LEATHER","MAGENTA","MITTENS","MUFFLER","NECKTIE","SNEAKER","STYLIST","SWEATER","TOPCOAT","UNIFORM"],
    },
  },
  {
    themeId: "en-a-botanic",
    label: "Botanic",
    difficultyTier: "A",
    wordsByLength: {
      4: ["BUDS","BULB","CORN","LEAF","LILY","MINT","PINE","PORE","ROOT","ROSE","SEED","STEM","TWIG"],
      5: ["ALDER","BIRCH","BLOOM","BROOM","CEDAR","FRUIT","HAZEL","LILAC","MAPLE","PETAL","SPINE","THORN","TULIP","WHEAT"],
      6: ["ACACIA","BRANCH","FLOWER","NECTAR","PISTIL","POLLEN","STIGMA","WILLOW"],
      7: ["COROLLA","CYPRESS","SEQUOIA"],
    },
  },
  {
    themeId: "en-a-human-constructions",
    label: "Human Constructions",
    difficultyTier: "A",
    wordsByLength: {
      4: ["BANK","BARN","FARM","FORT","JAIL","MALL","MILL","PORT","SHED","SHOP","SILO","WALL"],
      5: ["ABBEY","ARENA","FORUM","HOTEL","HOUSE","IGLOO","LEVEE","MOTEL","RANCH","TOWER","VILLA"],
      6: ["ASYLUM","BRIDGE","BUNKER","CAMPUS","CASTLE","CHAPEL","CHURCH","CINEMA","DUPLEX","FAVELA","GARAGE","HANGAR","MARINA","MOSQUE","MUSEUM","PAGODA","PALACE","PIGPEN","PRISON","SCHOOL","SHRINE","STABLE","TEMPLE","TUNNEL"],
      7: ["AIRPORT","BREWERY","CAPITOL","CARPORT","CITADEL","COLLEGE","EMBASSY","FACTORY","FOUNDRY","HAYLOFT","LIBRARY","PYRAMID","STADIUM","THEATER"],
    },
  },
  {
    themeId: "en-a-musical-instruments",
    label: "Musical instruments",
    difficultyTier: "A",
    wordsByLength: {
      4: ["BASS","GONG","HARP","HORN","LUTE","LYRE","OBOE","TUBA"],
      5: ["BANJO","CELLO","DRUMS","FLUTE","KAZOO","ORGAN","PIANO","SITAR","VIOLA"],
      6: ["CYMBAL","GUITAR","VIOLIN"],
      7: ["BAGPIPE","BASSOON","DARBUKA","MARIMBA","OCARINA","TRUMPET","UKULELE"],
    },
  },
  {
    themeId: "en-a-occupations",
    label: "Occupations",
    difficultyTier: "A",
    wordsByLength: {
      4: ["CHEF","COOK","KING","MAID","MONK","POET"],
      5: ["ACTOR","BAKER","CLERK","COACH","CROOK","DIVER","GUARD","GUIDE","JUDGE","MASON","MAYOR","MINER","MODEL","NURSE","PILOT","QUEEN","RABBI","SCOUT","SMITH","TILER","VALET","VICAR"],
      6: ["ARCHER","ARTIST","AUTHOR","BANKER","BARBER","BARMAN","BROKER","BUTLER","CONSUL","DEPUTY","DOCTOR","DRIVER","EDITOR","EXPERT","FARMER","GOLFER","HUNTER","INTERN","JAILER","JESTER","JOCKEY","LAWYER","PASTOR","PRIEST","PRINCE","RANGER","SAILOR","SCRIBE","SELLER","SINGER","TAILOR","TELLER","TRADER","TYPIST","WAITER","WARDEN","WEAVER","WELDER","WRITER","ATHLET"],
      7: ["ADVISER","ANALYST","BASSIST","BUILDER","BURGLAR","BUTCHER","CAPTAIN","CASHIER","CATERER","CELLIST","CHEMIST","CLEANER","CORONER","DENTIST","DOORMAN","DRAFTER","DRUMMER","EMPEROR","FIREMAN","FLORIST","FLUTIST","GENERAL","HARPIST","JANITOR","JEWELER","LABORER","MANAGER","MIDWIFE","PAINTER","PEDDLER","PIANIST","PLUMBER","POSTMAN","RANCHER","REFEREE","RETIREE","SENATOR","SHERIFF","SOLDIER","STEWARD","STUDENT","SURGEON","SWIMMER","TEACHER","VETERAN","WARRIOR"],
    },
  },
  {
    themeId: "en-a-planet-earth",
    label: "Planet Earth",
    difficultyTier: "A",
    wordsByLength: {
      4: ["BOSK","CAVE","COVE","CRAG","DAWN","DUNE","DUSK","FIRE","GULF","HEAT","HILL","LAKE","LAVA","PEAK","POND","RAIN","REEF","ROCK","SAND","SOIL","TIDE","VALE","WAVE","WIND"],
      5: ["ATOLL","BASIN","BEACH","BROOK","BUTTE","CANAL","CLIFF","CLOUD","COAST","CORAL","CREEK","DELTA","FIRTH","FJORD","FLOOD","FLORA","FROST","GRASS","GROVE","MAGMA","MARSH","NIGHT","OASIS","OCEAN","OZONE","PLAIN","RAPID","RIDGE","RIVER","SHORE","SILEX","SLUSH","STEAM","STORM","SWAMP","WOODS"],
      6: ["AURORA","AUTUMN","BASALT","BREEZE","CANYON","CAVERN","CRATER","DESERT","FOREST","FOSSIL","GEYSER","HOLLOW","ISLAND","JUNGLE","LAGOON","MEADOW","PEBBLE","PUDDLE","RAVINE","RUNNEL","SEASON","SLOUGH","SOURCE","SPRING","STEPPE","STREAM","SUMMER","SUMMIT","SUNSET","TUNDRA","VALLEY","WINTER"],
      7: ["CONIFER","CURRENT","CYCLONE","DRIZZLE","DROUGHT","ECLIPSE","EQUINOX","ESTUARY","GLACIER","GRANITE","ICEBERG","RAINBOW","SAVANNA","SUNRISE","TEMPEST","THUNDER","TORNADO","TORRENT","TSUNAMI","TWISTER","TYPHOON","VOLCANO"],
    },
  },
  {
    themeId: "en-a-sports",
    label: "Sports",
    difficultyTier: "A",
    wordsByLength: {
      4: ["AXEL","BALL","BUNT","CLUB","GOAL","GOLF","HOOP","JUDO","JUMP","LUGE","POLE","POLO","PUCK","RACE","TEAM"],
      5: ["CATCH","RACER","RELAY","RUGBY","SCUBA","SKATE","STICK"],
      6: ["BOCCIE","BOXING","CLEATS","GOALIE","HOCKEY","HURDLE","JOGGER","KARATE","LEAGUE","MALLET","PLAYER","RACING","RACKET","ROWING","SLALOM","SOCCER","SQUASH","STRIKE","TENNIS","UMPIRE","VOLLEY","WEIGHT","WICKET"],
      7: ["ARCHERY","ATHLETE","BOWLING","COMPETE","CROQUET","CURLING","CYCLING","FENCING","FIELDER","PARKOUR","PITCHER","RAFTING","SLEDDER"],
    },
  },
  {
    themeId: "en-a-transportation",
    label: "Transportation",
    difficultyTier: "A",
    wordsByLength: {
      4: ["AUTO","BIKE","BOAT","CART","JEEP","LIMO","SHIP","TAXI"],
      5: ["BARGE","BUGGY","CANOE","FERRY","LORRY","METRO","TRAIN","TRUCK","WAGON","YACHT"],
      6: ["GALLEY","GLIDER","LITTER","ROCKET","SLEIGH","SUBWAY","VESSEL"],
      7: ["BICYCLE","CARAVAN","CRUISER","FRIGATE","GONDOLA","MINIBUS","SCOOTER","TRAMWAY"],
    },
  },
  {
    themeId: "en-a-vegan-food",
    label: "Vegan Food",
    difficultyTier: "A",
    wordsByLength: {
      4: ["GUAR","LEEK","LIME","PEAR","PLUM","SAGE","SALT"],
      5: ["ACORN","ANISE","APPLE","BASIL","CRESS","CUMIN","GRAPE","GUAVA","LEMON","MANGO","MELON","OLIVE","ONION","PASTA","PEACH","PECAN","PENNE","SUMAC","THYME","CLOVE"],
      6: ["ALMOND","BANANA","CARROT","CASHEW","CELERY","CHERRY","CHIVES","CITRON","ENDIVE","FENNEL","GARLIC","GINGER","JUJUBE","LENTIL","LOQUAT","LYCHEE","MANIOC","ORANGE","PAPAYA","PEANUT","PEPPER","POMELO","POTATO","RADISH","SPROUT","TOMATO","TURNIP","WALNUT","WASABI","RAISIN"],
      7: ["APRICOT","ARUGULA","AVOCADO","CABBAGE","CARAWAY","CHICORY","CHUTNEY","COCONUT","KETCHUP","KUMQUAT","LETTUCE","MUSTARD","OREGANO","PAPRIKA","PARSLEY","PARSNIP","PUMPKIN","RHUBARB","SAFFRON","SHALLOT","SOYBEAN","SPINACH","TRUFFLE","VANILLA","VINEGAR"],
    },
  },
  {
    themeId: "en-b-at-school",
    label: "At school",
    difficultyTier: "B",
    wordsByLength: {
      4: ["BOOK","EXAM","GLUE","MATH","QUIZ","TEST"],
      5: ["ATLAS","BOARD","CHALK","CLASS","EASEL","GLOBE","PAPER","PUPIL","SLIDE"],
      6: ["ANSWER","BINDER","CRAYON","ERASER","FOLDER","LESSON","MARKER","PENCIL","RECESS"],
      7: ["ALGEBRA","COMPASS","GRAMMAR","HISTORY","PHYSICS","PROJECT","SCIENCE"],
    },
  },
  {
    themeId: "en-b-at-the-farm",
    label: "At the farm",
    difficultyTier: "B",
    wordsByLength: {
      4: ["COOP","FOAL","MILK","OATS","RAKE"],
      5: ["CHICK","CROPS","DAIRY","FENCE","FIELD"],
      6: ["BARLEY","BUCKET","GRAINS","PIGLET","SHOVEL","TILLER","WEEDER"],
      7: ["CHICKEN","HARVEST","PASTURE","POULTRY","TRACTOR"],
    },
  },
  {
    themeId: "en-b-beverages",
    label: "Beverages",
    difficultyTier: "B",
    wordsByLength: {
      4: ["ARAK","BEER","COLA","MATE","MEAD","OUZO","SAKE","SODA","WINE"],
      5: ["CIDER","JUICE","LAGER","PORTO","VODKA","WATER"],
      6: ["BRANDY","COFFEE","COGNAC","GRAPPA","KIRSCH","LIQUOR","TISANE"],
      7: ["BOURBON","SANGRIA","TEQUILA","WHISKEY"],
    },
  },
  {
    themeId: "en-b-circus-funfair",
    label: "Circus & Funfair",
    difficultyTier: "B",
    wordsByLength: {
      4: ["BEAR","CAGE","FEAT","GAME","MAZE","RIDE","RING","SHOW","TENT","WHIP"],
      5: ["BOOTH","CANDY","CLOWN","GIANT","MAGIC","PRIZE","TAMER","TRICK"],
      6: ["BANNER","PARADE","TICKET","TROUPE"],
      7: ["ACROBAT","APPLAUD","FESTIVE","GYMNAST","JUGGLER","LEOTARD","TRAINER","TRAPEZE"],
    },
  },
  {
    themeId: "en-b-computers-and-internet",
    label: "Computers and Internet",
    difficultyTier: "B",
    wordsByLength: {
      4: ["BLOG","BYTE","CHAT","COPY","DATA","DRAG","FILE","FONT","HOST","ICON","LINK","REDO","SAVE","SCAN","SPAM","UNDO","VINE"],
      5: ["CACHE","DEBUG","EMAIL","ENTER","FLASH","FRAME","INBOX","LOGIN","MACRO","MEDIA","MODEM","PASTE","RESET","SHIFT","TWEET","VIRUS"],
      6: ["ANALOG","BACKUP","BINARY","BITMAP","BUFFER","COOKIE","DELETE","DOMAIN","FORMAT","HACKER","KERNEL","LAPTOP","ONLINE","PIRACY","PORTAL","REBOOT","ROUTER","SCRIPT","SCROLL","SERVER","SYNTAX","THREAD","UPLOAD","WIDGET"],
      7: ["BROWSER","CAPTCHA","COMPILE","DESKTOP","ENCRYPT","HASHTAG","KEYWORD","LURKING","MALWARE","MONITOR","NETWORK","OFFLINE","PODCAST","PROCESS","PROGRAM","RESTORE","RUNTIME","SPYWARE","STORAGE","TOOLBAR","VIRTUAL","WEBSITE"],
    },
  },
  {
    themeId: "en-b-dances",
    label: "Dances",
    difficultyTier: "B",
    wordsByLength: {
      4: ["ACRO","HULA"],
      5: ["CONGA","DABKA","DISCO","LIMBO","MAMBO","POLKA","RUMBA","SALSA","SAMBA","STOMP","SWING","TANGO","TWIST","WALTZ"],
      6: ["BALLET","BOLERO","MINUET"],
      7: ["BEGUINE","LAMBADA","MAZURKA"],
    },
  },
  {
    themeId: "en-b-colors",
    label: "Colors",
    difficultyTier: "B",
    wordsByLength: {
      4: ["AQUA","BLUE","CYAN","GRAY","JADE","PINK"],
      5: ["AMBER","AZURE","BEIGE","BLACK","BROWN","GREEN","IVORY","MAUVE","SEPIA","WHITE"],
      6: ["AMAZON","COPPER","INDIGO","MAROON","PURPLE","SILVER","VIOLET","YELLOW"],
      7: ["EMERALD"],
    },
  },
  {
    themeId: "en-b-feudalism",
    label: "Feudalism",
    difficultyTier: "B",
    wordsByLength: {
      4: ["DAME","DUKE","LADY","LORD","PAGE","SERF"],
      5: ["BARON","COUNT","COURT","CROWN","LIEGE","REALM","REIGN"],
      6: ["DONJON","KNIGHT","ONAGER","PLEDGE","SHIELD","SQUIRE"],
      7: ["BARONET","DUCHESS","DYNASTY","KINGDOM","LOYALTY","MARQUIS","MONARCH","ROYALTY","SCEPTER"],
    },
  },
  {
    themeId: "en-b-furniture",
    label: "Furniture",
    difficultyTier: "B",
    wordsByLength: {
      4: ["CRIB","DESK","SOFA"],
      5: ["BENCH","CHAIR","COUCH","FUTON","STOOL","TABLE"],
      6: ["BUFFET","CRADLE","THRONE"],
      7: ["DRESSER","HAMMOCK","HASSOCK","JUKEBOX"],
    },
  },
  {
    themeId: "en-b-health",
    label: "Health",
    difficultyTier: "B",
    wordsByLength: {
      4: ["ACNE","COLD","CURE","CYST","DIET","DRUG","GERM","PAIN","PILL","WART"],
      5: ["COUGH","CRAMP","FEVER","GRAZE","MUMPS","SPASM","TOXIN","WOUND"],
      6: ["ASTHMA","BENIGN","BIOPSY","CANCER","ECZEMA","INJURY","OTITIS","POISON","RABIES","SPRAIN"],
      7: ["ALLERGY","ANAEMIA","ANXIETY","BANDAGE","BEDSORE","BLISTER","CALORIE","DISEASE","HYGIENE","ILLNESS","INSULIN","MALARIA","OBESITY","PATIENT","SYMPTOM","TENSION","THERAPY"],
    },
  },
  {
    themeId: "en-b-in-a-fairy-tale",
    label: "In a fairy tale",
    difficultyTier: "B",
    wordsByLength: {
      4: ["HERO","OGRE","WAND","WISH"],
      5: ["CURSE","DWARF","FAIRY","GHOST","GNOME","PIXIE","SPELL","SWORD","TROLL","WITCH"],
      6: ["DRAGON"],
      7: ["MERMAID","UNICORN","VILLAIN"],
    },
  },
  {
    themeId: "en-b-in-the-bathroom",
    label: "In the bathroom",
    difficultyTier: "B",
    wordsByLength: {
      4: ["COMB","SINK","SWAB"],
      5: ["BIDET","RAZOR","SCALE"],
      6: ["FAUCET","LOOFAH","LOTION","POWDER","SHAVER","TISSUE","TOILET","URINAL"],
      7: ["BATHTUB","BUBBLES","PERFUME","SHAMPOO"],
    },
  },
  {
    themeId: "en-b-in-the-jewelry-shop",
    label: "In the jewelry shop",
    difficultyTier: "B",
    wordsByLength: {
      4: ["ONYX","OPAL","RUBY"],
      5: ["AGATE","BERYL","CHAIN","PEARL","TIARA","TOPAZ"],
      6: ["AMULET","BROOCH","DIADEM","GARNET","JASPER","QUARTZ","SPINEL","ZIRCON"],
      7: ["APATITE","AZURITE","CITRINE","CRYSTAL","DIAMOND","EARRING","PENDANT"],
    },
  },
  {
    themeId: "en-b-in-the-kitchen",
    label: "In the Kitchen",
    difficultyTier: "B",
    wordsByLength: {
      4: ["FORK","MOLD","OVEN"],
      5: ["CROCK","FRYER","GLASS","GRILL","KNIFE","LADLE","RICER","SHEAR","SIEVE","SPOON","STOVE","TONGS","WHISK"],
      6: ["CARAFE","COOKER","FRIDGE","FUNNEL","GRATER","KETTLE","PEELER","SKEWER","SLICER","TEAPOT","ZESTER"],
      7: ["BLENDER","CUTLERY","FREEZER","GRIDDLE","GRINDER","INFUSER","PLATTER","POACHER","ROASTER","SPATULA","STEAMER","TOASTER"],
    },
  },
  {
    themeId: "en-b-mathematics",
    label: "Mathematics",
    difficultyTier: "B",
    wordsByLength: {
      4: ["AXIS","CUBE","ODDS","PLUS"],
      5: ["ANGLE","CURVE","EQUAL","GRAPH","MINUS","PRISM","RATIO","TOTAL","VALUE"],
      6: ["CIRCLE","CONVEX","DEDUCT","DIVIDE","FACTOR","MEDIAN","NUMBER","RADIAN","REDUCE","SQUARE","VECTOR","VOLUME"],
      7: ["AVERAGE","BALANCE","CONCAVE","DECIMAL","DIAGRAM","DIVISOR","FORMULA","HEXAGON","NUMERAL","OBLIQUE","PERCENT","POLYGON","SEGMENT","THEOREM"],
    },
  },
  {
    themeId: "en-b-money-and-business",
    label: "Money and Business",
    difficultyTier: "B",
    wordsByLength: {
      4: ["BILL","CASH","CENT","DEAL","DEBT","DIME","EARN","FUND","LEND","LOAN","LOSS","POOR","RATE","RENT","RICH","SALE","SELL"],
      5: ["CHEAP","CHECK","DEBIT","GROSS","NICHE","OUTGO","PENCE","PENNY","POUND","PRICE","TRADE","VAULT"],
      6: ["AFFORD","BORROW","BUDGET","CHANGE","COUPON","CREDIT","EXPORT","IMPORT","INCOME","INVEST","LENDER","MARGIN","NICKEL","PROFIT","REBATE","STOCKS","TARIFF"],
      7: ["BARGAIN","CAPITAL","DEFICIT","DEPOSIT","ECONOMY","EXPENSE","FINANCE","INVOICE","PAYMENT","QUARTER","RECEIPT","RESERVE","SAVINGS"],
    },
  },
  {
    themeId: "en-b-music",
    label: "Music",
    difficultyTier: "B",
    wordsByLength: {
      4: ["ALTO","BAND","BEAT","CLEF","DUET","NOTE","SOLO","SONG","TRIO","TUNE"],
      5: ["CANON","CHORD","OPERA","PITCH","TEMPO","TENOR","THEME"],
      6: ["ADAGIO","ANTHEM","ATONAL","AUBADE","BALLAD","CHORUS","MELODY","OCTAVE","RHYTHM","TIMBRE","UNISON"],
      7: ["CADENCE","CANTATA","CONCERT","HARMONY","QUARTET","QUINTET","SOLFEGE","SOPRANO"],
    },
  },
  {
    themeId: "en-b-music-styles",
    label: "Music styles",
    difficultyTier: "B",
    wordsByLength: {
      4: ["ACID","FOLK","FUNK","JAZZ","PUNK","SOCA","SOUL","ZOUK"],
      5: ["BLUES","METAL"],
      6: ["GOSPEL","GRUNGE","MOTOWN","REGGAE","TECHNO","TRANCE"],
      7: ["BAROQUE","BRITPOP","CALYPSO","COUNTRY","DUBSTEP","RAGTIME"],
    },
  },
  {
    themeId: "en-b-on-the-dining-table",
    label: "On the dining table",
    difficultyTier: "B",
    wordsByLength: {
      4: ["BOWL","FOOD","MEAL"],
      5: ["BREAD","DRINK","PLATE","TOWEL"],
      6: ["BASKET","BOTTLE","CANDLE","NAPKIN"],
      7: ["COASTER","FLOWERS"],
    },
  },
  {
    themeId: "en-b-sources-of-light",
    label: "Sources of Light",
    difficultyTier: "B",
    wordsByLength: {
      4: ["LAMP","MOON","NEON","STAR"],
      5: ["COMET","FLAME","LASER","MATCH","SPARK","TORCH"],
      6: ["BEACON","METEOR","SPRITE"],
      7: ["LANTERN","LIGHTER"],
    },
  },
  {
    themeId: "en-b-spare-parts",
    label: "Spare Parts",
    difficultyTier: "B",
    wordsByLength: {
      4: ["AXLE","DOOR","FUEL","FUSE","LOCK","RIMS","TIRE"],
      5: ["ALARM","GAUGE","MOTOR","PEDAL","WHEEL"],
      6: ["AIRBAG","BRAKES","BUMPER","CLUTCH","FILTER","GASKET","HEATER","PISTON","WINDOW"],
      7: ["CHASSIS","CONSOLE","GEARBOX","SPOILER","STARTER","SUNROOF"],
    },
  },
  {
    themeId: "en-b-the-family",
    label: "The Family",
    difficultyTier: "B",
    wordsByLength: {
      4: ["AUNT","BABY","WIFE"],
      5: ["CHILD","NIECE","UNCLE"],
      6: ["COUSIN","FATHER","MOTHER","NEPHEW","SISTER","SPOUSE"],
      7: ["BROTHER","HUSBAND"],
    },
  },
  {
    themeId: "en-c-animal-habitats",
    label: "Animal Habitats",
    difficultyTier: "C",
    wordsByLength: {
      4: ["HIVE","LAIR","NEST","SETT"],
      5: ["LODGE","STALL"],
      6: ["BURROW","KENNEL","PIGSTY","WARREN"],
      7: ["CATTERY"],
    },
  },
  {
    themeId: "en-c-artistic-productions",
    label: "Artistic productions",
    difficultyTier: "C",
    wordsByLength: {
      4: ["EPIC","HYMN","PLAY","POEM"],
      5: ["ALBUM","DANCE","ELEGY","MOVIE","NOVEL","PHOTO","PROSE","PSALM"],
      6: ["COMEDY","EFFIGY","LITANY","SONATA","SONNET","STATUE","TATTOO"],
      7: ["EPIGRAM","MUSICAL","POTTERY","REQUIEM"],
    },
  },
  {
    themeId: "en-c-airport-planes",
    label: "Airport & Planes",
    difficultyTier: "C",
    wordsByLength: {
      4: ["GATE","TAIL","VISA","WING"],
      5: ["CABIN","CRAFT"],
      6: ["FASTEN","FLIGHT","FLYING","RUNWAY"],
      7: ["AILERON","AIRLINE","COPILOT","CUSTOMS","HORIZON","LANDING","STEALTH","TAKEOFF","TURBINE"],
    },
  },
  {
    themeId: "en-c-at-the-beach",
    label: "At the Beach",
    difficultyTier: "C",
    wordsByLength: {
      4: ["FINS","KELP","PIER","SURF"],
      5: ["CONCH","WHARF"],
      6: ["COOLER","SUNTAN"],
      7: ["FISHING","FRISBEE","MUSSELS","SANDBAR","SEAWEED","SNORKEL","SUNBURN"],
    },
  },
  {
    themeId: "en-c-baby-earthlings",
    label: "Baby Earthlings",
    difficultyTier: "C",
    wordsByLength: {
      4: ["CALF","COLT","FAWN","PUPA"],
      5: ["ELVER","LARVA","OWLET","POULT","PUPPY","SHOAT","SQUAB"],
      6: ["CYGNET","EAGLET","KITTEN","MAGGOT","GOSLIN"],
      7: ["LAMBKIN","TADPOLE"],
    },
  },
  {
    themeId: "en-c-boats-and-sailing",
    label: "Boats and sailing",
    difficultyTier: "C",
    wordsByLength: {
      4: ["AHOY","BAIL","BEAM","BUOY","CREW","DOCK","FURL","KEEL","KNOT","MAST","PUNT","RAFT","TACK","YAWL"],
      5: ["ABEAM","ALOFT","BILGE","HOIST","SCULL","SLOOP","STERN","WINCH","PIRAT"],
      6: ["ANCHOR","ASTERN","BARQUE","BOATER","CUTTER","DINGHY","DUGOUT","LAUNCH","MIZZEN","PADDLE","RUDDER","WHALER"],
      7: ["AGROUND","BALLAST","CAPSIZE","CARRIER","CLIPPER","DOCKING","GANGWAY","GUNWALE","LEEWARD","MOORING","ONBOARD","PASSAGE","PENNANT","RIGGING","ROWBOAT","SEASICK","TOPSAIL","TOWBOAT","TRANSOM","TRAWLER"],
    },
  },
  {
    themeId: "en-c-bones",
    label: "Bones",
    difficultyTier: "C",
    wordsByLength: {
      4: ["RIBS","ULNA"],
      5: ["INCUS","TALUS","VOMER"],
      6: ["COCCYX","FIBULA","SACRUM","STAPES","TARSUS"],
      7: ["MALLEUS","MAXILLA","PATELLA","SCAPULA"],
    },
  },
  {
    themeId: "en-c-chemical-elements",
    label: "Chemical elements",
    difficultyTier: "C",
    wordsByLength: {
      4: ["GOLD","LEAD","ZINC"],
      5: ["ARGON","BORON","RADON","XENON"],
      6: ["BARIUM","CARBON","CERIUM","COBALT","CURIUM","ERBIUM","HELIUM","INDIUM","IODINE","OXYGEN","RADIUM","SODIUM","SULFUR"],
      7: ["ARSENIC","BISMUTH","BOHRIUM","BROMINE","CADMIUM","CALCIUM","DUBNIUM","IRIDIUM","KRYPTON","LITHIUM","MERCURY","SILICON","THORIUM","URANIUM"],
    },
  },
  {
    themeId: "en-c-communication",
    label: "Communication",
    difficultyTier: "C",
    wordsByLength: {
      4: ["BAUD","CALL","CODE","DIAL","MAIL","POST","TONE"],
      5: ["HERTZ","PAGER","PHONE","RADIO","STAMP"],
      6: ["BEEPER","LETTER","MAILER","MEDIUM","MOBILE","SIGNAL"],
      7: ["ADDRESS","ANTENNA","CHANNEL","DECODER","HEADSET","MAILBOX","MESSAGE","POSTAGE"],
    },
  },
  {
    themeId: "en-c-elections",
    label: "Elections",
    difficultyTier: "C",
    wordsByLength: {
      4: ["POLL","VOTE"],
      5: ["ELECT","PARTY","TALLY","VOTER"],
      6: ["BALLOT","CAUCUS","RUNOFF"],
      7: ["ELECTOR","MANDATE","PRIMARY","RECOUNT"],
    },
  },
  {
    themeId: "en-c-energy",
    label: "Energy",
    difficultyTier: "C",
    wordsByLength: {
      4: ["PEAT","VOLT","WATT"],
      5: ["JOULE","POWER","SHALE","THERM","WASTE"],
      6: ["ABSORB","BOILER","DYNAMO","ENERGY","PETROL","PHOTON"],
      7: ["BIOFUEL","BIOMASS","ENTROPY","ETHANOL","METHANE","NUCLEAR","NUCLEUS","PROPANE","RADIANT","REACTOR","WATTAGE"],
    },
  },
  {
    themeId: "en-c-geometry",
    label: "Geometry",
    difficultyTier: "C",
    wordsByLength: {
      4: ["CONE","DISC","OVAL","SIDE"],
      5: ["HELIX","PLANE","POINT","ROUND","SHAPE","SINUS","TORUS"],
      6: ["CENTER","CUBOID","LENGTH","SECTOR"],
      7: ["ANNULUS","DECAGON","ELLIPSE","LOZENGE","NONAGON","OCTAGON"],
    },
  },
  {
    themeId: "en-c-group-of-animals",
    label: "Group of animals",
    difficultyTier: "C",
    wordsByLength: {
      4: ["BEVY","HERD","PACK"],
      5: ["BROOD","FLOCK","HORDE","SHOAL","SWARM"],
      6: ["COLONY"],
      7: ["ROOKERY"],
    },
  },
  {
    themeId: "en-c-human-head",
    label: "Human Head",
    difficultyTier: "C",
    wordsByLength: {
      4: ["CHIN","LIPS"],
      5: ["CHEEK","SKULL"],
      6: ["ARTERY","CORNEA","PALATE"],
      7: ["FRECKLE","NOSTRIL"],
    },
  },
  {
    themeId: "en-c-legal-terms",
    label: "Legal Terms",
    difficultyTier: "C",
    wordsByLength: {
      4: ["JURY","PLEA","TORT","WRIT"],
      5: ["CLAIM","FRAUD","ORDER","PROXY","THEFT","TRIAL","USURY","VENUE","WAIVE"],
      6: ["ACQUIT","ARREST","DECREE","DOCKET","ESTATE","ETHICS","FELONY","PAROLE","REVOKE","VACATE"],
      7: ["CONFESS","COUNSEL","CUSTODY","HEARING","JUSTICE","LARCENY","LAWSUIT","PERJURY","VERDICT","WARRANT","WITNESS"],
    },
  },
  {
    themeId: "en-c-liquid-containers",
    label: "Liquid Containers",
    difficultyTier: "C",
    wordsByLength: {
      4: ["CASK","EWER","TANK","VIAL"],
      5: ["CRUET","FLASK","STEIN","BARRE"],
      6: ["BEAKER","GOBLET"],
      7: ["AMPHORA"],
    },
  },
  {
    themeId: "en-c-mammals",
    label: "Mammals",
    difficultyTier: "C",
    wordsByLength: {
      4: ["BOAR","HARE"],
      5: ["CAMEL","LEMUR","OKAPI"],
      6: ["BEAVER","COYOTE","MARMOT","WAPITI"],
      7: ["BUFFALO","CHEETAH","MACAQUE","WALLABY"],
    },
  },
  {
    themeId: "en-c-on-a-shooting-set",
    label: "On a shooting set",
    difficultyTier: "C",
    wordsByLength: {
      4: ["FILM","LENS","ROLE","ZOOM"],
      5: ["DOLLY","FLICK","FOCAL","FOCUS","PIXEL","SCENE","SPOOL","STUNT"],
      6: ["CAMERA","GAFFER","RUSHES"],
      7: ["EDITING","FOOTAGE","PICTURE","SHUTTER","STARDOM"],
    },
  },
  {
    themeId: "en-c-outer-space",
    label: "Outer space",
    difficultyTier: "C",
    wordsByLength: {
      4: ["MARS","NOVA","VOID"],
      5: ["EARTH","LUNAR","ORBIT","PLUTO","SOLAR","VENUS"],
      6: ["COSMOS","GALAXY","NEBULA","PLANET","SATURN","URANUS","ZODIAC"],
      7: ["GRAVITY","JUPITER","NEPTUNE","SHUTTLE"],
    },
  },
  {
    themeId: "en-c-time",
    label: "Time",
    difficultyTier: "C",
    wordsByLength: {
      4: ["HOUR","LATE","PAST","SOON","THEN","WEEK","YEAR","ZONE"],
      5: ["AFTER","DELAY","EARLY","EPOCH","MONTH","TARDY","TODAY"],
      6: ["ANNUAL","BEFORE","DECADE","FUTURE","MINUTE","MOMENT","PERIOD","SECOND"],
      7: ["CENTURY","JUBILEE","MORNING","PRESENT","SUNDIAL","TONIGHT"],
    },
  },
  {
    themeId: "en-c-war-army",
    label: "War & Army",
    difficultyTier: "C",
    wordsByLength: {
      4: ["AMMO","BASE","BOMB","CAMP","MINE","NAVY","UNIT"],
      5: ["ARMOR","ENEMY","FIGHT","FLEET","MAJOR","MEDAL","RIFLE","SIEGE","SQUAD","TRUCE"],
      6: ["ATTACK","BATTLE","BULLET","CANNON","COMBAT","DEFEAT","ENLIST","GUNNER","MORTAR","MUSKET","TACTIC","TARGET","TROOPS","WEAPON"],
      7: ["ADMIRAL","ARSENAL","CAVALRY","COLONEL","DEFENSE","GRENADE","MISSILE","OFFICER","RECRUIT","RETREAT","TORPEDO"],
    },
  },
  {
    themeId: "en-c-yard-and-backyard",
    label: "Yard and Backyard",
    difficultyTier: "C",
    wordsByLength: {
      4: ["BUSH","HOSE","LAWN","PATH"],
      5: ["EDGER","PATIO","PORCH","SHRUB","STOOP"],
      6: ["AWNING"],
      7: ["ORCHARD","PLANTER","TERRACE","WALKWAY"],
    },
  },
  {
    themeId: "en-c-calendar",
    label: "Calendar",
    difficultyTier: "C",
    wordsByLength: {
      4: ["JULY","JUNE"],
      5: ["ARIES","LIBRA","MARCH","APRIL","VIRGO"],
      6: ["GEMINI","TAURUS","AUGUST","FRIDAY","MONDAY","PISCES","SUNDAY"],
      7: ["SCORPIO","TUESDAY"],
    },
  },
  {
    themeId: "en-d-african-cities",
    label: "African Cities",
    difficultyTier: "D",
    wordsByLength: {
      4: ["KANO","LAMU","MAUN","SUEZ"],
      5: ["ACCRA","AKURE","BENIN","CAIRO","DAKAR","GIZEH","LAGOS","RABAT","WARRI"],
      6: ["AGADIR","BANGUI","DOUALA","DURBAN","HARARE","IBADAN","ILORIN","KADUNA","KIGALI","KUMASI","LUSAKA","MATOLA","NIAMEY","SOWETO"],
      7: ["ABIDJAN","ALGIERS","CONAKRY","KAMPALA","MOMBASA","NAIROBI","TANGIER","TRIPOLI","YAOUNDE"],
    },
  },
  {
    themeId: "en-d-asian-cities",
    label: "Asian Cities",
    difficultyTier: "D",
    wordsByLength: {
      4: ["DOHA","OMAN","XIAN"],
      5: ["DELHI","DHAKA","DUBAI","KABUL","MOSUL","OSAKA","SANAA","SEOUL","SURAT","TOKYO","WUHAN"],
      6: ["ALEPPO","ANKARA","BEIRUT","BOMBAY","JAIPUR","JEDDAH","LAHORE","MADRAS","MANILA","MOSCOW","RIYADH","TEHRAN"],
      7: ["BAGHDAD","BANGKOK","BEIJING","BISHKEK","JAKARTA","KARACHI","MASHHAD","RANGOON","TIANJIN"],
    },
  },
  {
    themeId: "en-d-capitals-of-the-world",
    label: "Capitals of the World",
    difficultyTier: "D",
    wordsByLength: {
      4: ["APIA","BAKU","BERN","KIEV","LIMA","LOME","OSLO","RIGA","ROME"],
      5: ["ABUJA","ALOFI","AMMAN","HANOI","MINSK","PARIS","PRAIA","QUITO","SOFIA","TUNIS"],
      6: ["ASMARA","ASTANA","ATHENS","AVARUA","BAMAKO","BERLIN","BISSAU","BOGOTA","DUBLIN","HAVANA","LISBON","LONDON","LUANDA","MADRID","MANAMA","MAPUTO","MASERU","MONACO","MUSCAT","NASSAU","OTTAWA","PRAGUE","TALLIN","VIENNA","WARSAW","ZAGREB"],
      7: ["CARACAS","CAYENNE","MANAGUA","NICOSIA","PAPEETE","VILNIUS","YEREVAN"],
    },
  },
  {
    themeId: "en-d-countries",
    label: "Countries",
    difficultyTier: "D",
    wordsByLength: {
      4: ["CUBA","FIJI","IRAN","IRAQ","MALI","NIUE","PERU","TOGO"],
      5: ["BURMA","CHILE","CHINA","CONGO","EGYPT","GABON","GHANA","HAITI","INDIA","ITALY","JAPAN","KENYA","LIBYA","MALTA","NAURU","NEPAL","NIGER","PALAU","QATAR","SAMOA","SPAIN","SUDAN","SYRIA","TONGA","YEMEN"],
      6: ["ANGOLA","BELIZE","BHUTAN","BRAZIL","BRUNEI","CANADA","CYPRUS","FRANCE","GAMBIA","GREECE","GUINEA","GUYANA","ISRAEL","JORDAN","KOSOVO","KUWAIT","LATVIA","MALAWI","MEXICO","NORWAY","PANAMA","POLAND","RUSSIA","RWANDA","SERBIA","SWEDEN","TAIWAN","TUVALU","UGANDA","ZAMBIA"],
      7: ["ALBANIA","ALGERIA","ANDORRA","ARMENIA","AUSTRIA","BAHAMAS","BAHRAIN","BELARUS","BELGIUM","BOLIVIA","BURUNDI","COMOROS","CROATIA","DENMARK","ECUADOR","ERITREA","ESTONIA","FINLAND","GEORGIA","GERMANY","GRENADA","HUNGARY","ICELAND","IRELAND","JAMAICA","LEBANON","LESOTHO","LIBERIA","MOLDOVA","MOROCCO","NAMIBIA","NIGERIA","ROMANIA","SENEGAL","SOMALIA","TUNISIA","UKRAINE","URUGUAY","VANUATU","VIETNAM"],
    },
  },
  {
    themeId: "en-d-european-cities",
    label: "European Cities",
    difficultyTier: "D",
    wordsByLength: {
      4: ["BONN","HAMM","LYON","NICE","VIGO","YORK"],
      5: ["BRAGA","BREDA","BREST","DIJON","ESPOO","ESSEN","GENOA","LAHTI","LEEDS","LILLE","MILAN","NAMUR","PADUA","REIMS","VARNA"],
      6: ["ANGERS","BOLTON","BREMEN","BRUGES","CANNES","DUDLEY","FOGGIA","KAUNAS","KRAKOW","MALAGA","MUNICH","NAPOLI","RENNES","RIJEKA","TORINO","TOULON","VENICE","VERONA"],
      7: ["BELFAST","BOLOGNA","BRESCIA","BRISTOL","CARDIFF","CATANIA","COLOGNE","CORDOBA","CRAIOVA","DRESDEN","GLASGOW","GRANADA","HAARLEM","HAMBURG","HANOVER","LEIPZIG","NEWPORT","PALERMO","RAVENNA","ROSTOCK","SALERNO","SEVILLE","TALLINN","TAMPERE"],
    },
  },
  {
    themeId: "en-d-cities-of-the-world",
    label: "Cities of the World",
    difficultyTier: "D",
    wordsByLength: {
      4: ["OMSK","PISA"],
      5: ["KYOTO","LUXOR","MECCA","MIAMI","TURIN"],
      6: ["AUSTIN","BILBAO","BOSTON","CANCUN","DALLAS","DENVER","GENOVA","MILANO","MUMBAI","OXFORD","QUEBEC","RHODES","SYDNEY","TAIPEI","ZURICH"],
      7: ["ATLANTA","CHESTER","CHICAGO","DETROIT","HOUSTON","KOLKATA","LARNACA","MEMPHIS","MYKONOS","ORLANDO","SEATTLE","TORONTO"],
    },
  },
  {
    themeId: "en-d-south-american-cities",
    label: "South American Cities",
    difficultyTier: "D",
    wordsByLength: {
      4: ["CALI","LEON"],
      5: ["BELEM","NATAL"],
      6: ["MANAUS","RECIFE","SANTOS"],
      7: ["MARACAY","MENDOZA","ROSARIO"],
    },
  },
  {
    themeId: "en-d-us-states",
    label: "US States",
    difficultyTier: "D",
    wordsByLength: {
      4: ["IOWA","OHIO","UTAH"],
      5: ["IDAHO","MAINE","TEXAS"],
      6: ["ALASKA","HAWAII","KANSAS","NEVADA","OREGON"],
      7: ["ALABAMA","ARIZONA","FLORIDA","INDIANA","MONTANA","VERMONT","WYOMING"],
    },
  },
  {
    themeId: "en-d-currencies",
    label: "Currencies",
    difficultyTier: "D",
    wordsByLength: {
      4: ["BATH","DRAM","EURO","HWAN","INTI","KUNA","LIRA","MARK","PESO","REAL","YANG","YUAN"],
      5: ["BUDJU","DINAR","FRANC","KRONA","LIVRE","PAISA","RIYAL","RUBLE","RUPEE","SCUDO","SUCRE","ZLOTY"],
      6: ["DENIER","DINERO","DIRHAM","DOLLAR","ESCUDO","FLORIN","GINEIH","GOURDE","KORUNA","PESETA","SHEKEL","TANGKA","THALER"],
      7: ["AFGHANI","AUSTRAL","BOLIVAR","CRUZADO","DRACHMA","PENNING","PIASTRA"],
    },
  },
  {
    themeId: "en-d-languages",
    label: "Languages",
    difficultyTier: "D",
    wordsByLength: {
      4: ["THAI","URDU","ZULU"],
      5: ["CZECH","DUTCH","GREEK","HAKKA","HINDI","IRISH","MALAY","MAORI","MAYAN","SWATI","TAJIK","TAMIL","UZBEK","WELSH","XIANG"],
      6: ["ABKHAZ","ARABIC","BASQUE","BERBER","DANISH","FRENCH","GAELIC","GERMAN","HEBREW","KAZAKH","KOREAN","KYRGYZ","NEPALI","SLOVAK","SOMALI","MALTES"],
      7: ["AMHARIC","BENGALI","BOSNIAN","BURMESE","CATALAN","CHINESE","ENGLISH","FINNISH","FRISIAN","ITALIAN","KURDISH","LATVIAN","PERSIAN","PUNJABI","QUECHUA","RUSSIAN","SERBIAN","SLOVENE","SPANISH","SWAHILI","SWEDISH","TIBETAN","TURKISH","TURKMEN","YIDDISH"],
    },
  },
  {
    themeId: "en-d-lakes-rivers",
    label: "Lakes & Rivers",
    difficultyTier: "D",
    wordsByLength: {
      4: ["NESS","NILE","ERIE"],
      5: ["LEMAN","INDUS","HURON","VOLTA","RHINE","SEINE","LOIRE","VOLGA"],
      6: ["BAIKAL","LOMOND","GANGES","MEKONG","THAMES","DANUBE"],
      7: ["YANGTZE","ZAMBEZI","ONTARIO","WHEATON"],
    },
  },
  {
    themeId: "en-e-cars",
    label: "Cars",
    difficultyTier: "E",
    wordsByLength: {
      4: ["AUDI","FIAT","FORD","OPEL","SAAB","SEAT"],
      5: ["BUICK","DACIA","DODGE","HONDA","ISUZU","LEXUS","LOTUS","MAZDA","SKODA","SMART","VOLVO"],
      6: ["HUMMER","LANCIA","NISSAN","SUBARU","SUZUKI","TOYOTA"],
      7: ["BENTLEY","BUGATTI","CITROEN","FERRARI","HYUNDAI","PEUGEOT","PONTIAC","PORSCHE","RENAULT"],
    },
  },
  {
    themeId: "en-e-famous-brands",
    label: "Famous Brands",
    difficultyTier: "E",
    wordsByLength: {
      4: ["ACER","AVON","BOSE","DELL","DIOR","FILA","FUJI","LEGO","NIKE","OLAY","OREO","SONY","TWIX"],
      5: ["ASICS","CASIO","CREST","DOLBY","EVIAN","FANTA","GUCCI","HALLS","HEINZ","KNORR","KRAFT","LINDT","MAGGI","NIKON","NIVEA","NOKIA","PEPSI","PRADA","ROLEX","SANYO","SHARP","TEFAL","TWIRL","UMBRO","VICHY","WELLA","XEROX"],
      6: ["ADIDAS","ARMANI","BOUNTY","CHANEL","CRUNCH","GIBSON","GODIVA","HENKEL","HERMES","HOOVER","LIPTON","MATTEL","MENTOS","RAYBAN","REEBOK","REVLON","REXONA","SMACKS","TAMPAX","VIAGRA"],
      7: ["AIRNESS","BARILLA","BUITONI","CADBURY","CARTIER","CLARINS","COLGATE","CRAYOLA","GRUNDIG","HISENSE","KENWOOD","KICKERS","KLEENEX","LACOSTE","LANCOME","MAIZENA","MIRINDA","NESCAFE","NUTELLA","PAMPERS","PANTENE","PERRIER","PHILIPS","SAMSUNG","SUNSILK","TOSHIBA","VERSACE"],
    },
  },
  {
    themeId: "en-e-fictional-characters",
    label: "Fictional Characters",
    difficultyTier: "E",
    wordsByLength: {
      4: ["HULK","NEMO","YODA","YOGI"],
      5: ["AKIRA","ALICE","ARIEL","BALOO","BAMBI","DARIA","DUMBO","JERRY","KENNY","LINUS","MULAN","PONGO","ROBIN","SHREK","SIMBA","ZORRO"],
      6: ["ARTHUR","BATMAN","BEAVIS","BENDER","CASPER","DEXTER","DROOPY","GOOFEY","GROMIT","HAMLET","HECKLE","JECKLE","KERMIT","MERLIN","MOWGLI","POPEYE","SNOOPY","TARZAN","TINTIN","TWEETY"],
      7: ["ARAGORN","GANDALF","MAFALDA","WALLACE"],
    },
  },
  {
    themeId: "en-e-fictional-places",
    label: "Fictional Places",
    difficultyTier: "E",
    wordsByLength: {
      4: ["ARDA","URAK"],
      5: ["ARGUS","ASHAN","NABOO","NEXUS","OERTH","ELRIO"],
      6: ["ASGARD","ATREIA","NARNIA","THEDAS","UTOPIA","XANADU"],
      7: ["AZEROTH","CAMELOT","ETERNIA","ETHERIA","PANDORA"],
    },
  },
  {
    themeId: "en-e-gods-and-goddesses",
    label: "Gods and Goddesses",
    difficultyTier: "E",
    wordsByLength: {
      4: ["ARIS","HERA","JUNO","ODIN","RAMA","THOR","ZEUS","CIRC"],
      5: ["CERES","DIANA","HADES","JANUS","SHIVA","VESTA","HESTI"],
      6: ["APOLLO","ATHENA","ISHTAR","VISHNU","VULCAN"],
      7: ["ARTEMIS","DEMETER","KRISHNA","MINERVA"],
    },
  },
  {
    themeId: "en-e-greek-mythology",
    label: "Greek mythology",
    difficultyTier: "E",
    wordsByLength: {
      4: ["EROS","GAIA","RHEA","STYX"],
      5: ["CIRCE","CREON","HELEN","JASON","LETHE","MEDEA","MIDAS","MINOS","PELOP","TITAN"],
      6: ["CASTOR","DAPHNE","EUROPA","FURIES","HELIOS","ICARUS","MEDUSA","MENTOR","PALLAS","POLLUX","PSYCHE","SCYLLA","SELENE","TETHYS"],
      7: ["ARACHNE","ELECTRA","GALATEA","IAPETUS","JOCASTA","NEMESIS","OCEANUS","ORPHEUS","THESEUS","ULYSSES"],
    },
  },
  {
    themeId: "en-e-famous-movies",
    label: "Famous Movies",
    difficultyTier: "E",
    wordsByLength: {
      4: ["CARS","CUJO","DUEL","FAME","JAWS","TRON","TROY"],
      5: ["ABYSS","ALIEN","ANNIE","BENJI","BORAT","BRUNO","BUGSY","CRASH","DOGMA","EVITA","FARGO","FRIDA","RAMBO","ROCKY","SEVEN","TAKEN","ZELIG"],
      6: ["AVATAR","CARRIE","CASINO","CLERKS","FREAKS","FRENZY","GREASE","LOLITA","MISERY","PSYCHO","SCREAM","SNATCH"],
      7: ["ALADDIN","AMADEUS","AVIATOR","CABARET","DRACULA","FRANTIC","GATTACA","JUMANJI","MEMENTO","PERSONA","PIRATES","PLATOON","RAINMAN","REBECCA","ROBOCOP","SHINING","SOLARIS","STALKER","STARMAN","TITANIC","TOOTSIE","TRAFFIC","VERTIGO"],
    },
  },
  {
    themeId: "en-e-tv-series",
    label: "TV Series",
    difficultyTier: "E",
    wordsByLength: {
      4: ["GLEE","LOST"],
      5: ["ALIAS","CHIPS","GRIMM","KOJAK","WEEDS"],
      6: ["CHEERS","FRINGE","HEROES"],
      7: ["BONANZA","COLUMBO","FRASIER","FRIENDS"],
    },
  },
  {
    themeId: "en-e-world-mythologies",
    label: "World Mythologies",
    difficultyTier: "E",
    wordsByLength: {
      4: ["ANKU","JINN","NAGA","SITA"],
      5: ["AMRIT","ARTIO","BALOR","GANGA","INDRA","JUNON"],
      6: ["AIRMID","BHADRA","BRAHMA","CHAKRA","ENKIDU","GHOULS","HESTIA","HUWAWA","PELOPS","RAVANA","SANKHA"],
      7: ["BAHAMUT","BELENUS","HANUMAN"],
    },
  },
];
