import type { SampleThemeWords } from '../types.js';

/**
 * Generated from docs/design/word-lists — do not hand-edit.
 * Regenerate with `node scripts/generate-word-lists.mjs` after the source
 * JSON files change (rebuild the engine first: `npm run build`).
 */
export const ENGLISH_WORD_LIST_THEMES: readonly SampleThemeWords[] = [
  {
    themeId: "en-a-anatomy",
    label: "Anatomy",
    difficultyTier: "A",
    wordsByLength: {
      4: ["BONE","CHIN","HAIR","HAND","IRIS","KNEE","LUNG","NAIL","NECK","NOSE","SKIN","ULNA","VEIN"],
      5: ["ANKLE","AORTA","BLOOD","BRAIN","CHEEK","COLON","ELBOW","FEMUR","GLAND","HEART","JOINT","LIVER","MOLAR","MOUTH","NERVE","OVARY","PUPIL","SCALP","THIGH","THUMB","TIBIA","TOOTH","WRIST"],
      6: ["ARTERY","BREAST","CORNEA","EYELID","FIBULA","FINGER","KIDNEY","LARYNX","MUSCLE","PALATE","PELVIS","RADIUS","RECTUM","RETINA","SPLEEN","TENDON","THORAX","THROAT","TONGUE","URETER","UTERUS"],
      7: ["ABDOMEN","BLADDER","CRANIUM","EARDRUM","EYELASH","FOREARM","HUMERUS","KNEECAP","NOSTRIL","PATELLA","PHARYNX","STERNUM","STOMACH","TRACHEA"],
    },
  },
  {
    themeId: "en-a-animals",
    label: "Animals",
    difficultyTier: "A",
    wordsByLength: {
      4: ["CRAB","CROW","DEER","DOVE","DUCK","FLEA","FROG","GOAT","GULL","HAWK","IBEX","IBIS","KIWI","LAMB","LARK","LION","LYNX","MARE","MITE","MOLE","MOTH","MULE","NEWT","ORCA","PONY","PUMA","SEAL","SLUG","SWAN","TICK","TOAD","TUNA","WASP","WOLF","WORM","ZEBU"],
      5: ["COBRA","CRANE","DINGO","EAGLE","GECKO","GOOSE","HERON","HORSE","HUSKY","HYENA","HYRAX","KOALA","LEMUR","LLAMA","LOUSE","MACAW","MOOSE","MOUSE","OTTER","PANDA","QUAIL","RAVEN","SHARK","SHEEP","SHREW","SKUNK","SNAIL","SNAKE","SNIPE","SQUID","STORK","TAPIR","TIGER","TROUT","VIPER","WHALE","ZEBRA"],
      6: ["BADGER","BEETLE","BOBCAT","CAIMAN","CONDOR","COUGAR","COYOTE","CUCKOO","DONKEY","ERMINE","FALCON","FERRET","GERBIL","GROUSE","HORNET","IGUANA","JACKAL","JAGUAR","LIZARD","LOCUST","MAGPIE","MARTIN","MONKEY","MUSSEL","OCELOT","OYSTER","PARROT","PIGEON","RABBIT","SALMON","SCARAB","SHRIMP","SPIDER","SPONGE","TOUCAN","TURKEY","TURTLE","URCHIN","WALRUS","WEASEL"],
      7: ["BUZZARD","CRICKET","DOLPHIN","FIREFLY","GAZELLE","GIRAFFE","GORILLA","GRIZZLY","HAMSTER","LADYBUG","LEOPARD","LOBSTER","MAMMOTH","MANATEE","MUSTANG","NARWHAL","OPOSSUM","OSTRICH","PANTHER","PEACOCK","PEAFOWL","PECCARY","PELICAN","PENGUIN","PIRANHA","PITBULL","RACCOON","ROOSTER","SARDINE","SEAGULL","SPARROW","TERMITE","VULTURE","WARBLER"],
    },
  },
  {
    themeId: "en-a-clothes-accessories",
    label: "Clothes & Accessories",
    difficultyTier: "A",
    wordsByLength: {
      4: ["BELT","BOOT","CAPE","CLOG","COAT","CUFF","GARB","GOWN","JEAN","KEPI","KILT","MASK","MITT","RING","ROBE","SARI","SASH","SHOE","SOCK","SUIT","TOGA","TUTU","VEIL","VEST"],
      5: ["APRON","BERET","BURQA","CLOAK","DRESS","FROCK","GILET","GLOVE","HEELS","JEANS","KIPPA","NIQAB","PANTS","PARKA","PURSE","SCARF","SHAWL","SHIRT","SKIRT","SMOCK","TIARA","TUNIC","WATCH"],
      6: ["ANORAK","ATTIRE","BANGLE","BIKINI","BLAZER","BLOUSE","BONNET","BOXERS","BRIEFS","BROOCH","BUCKLE","BUTTON","CAFTAN","CLOTHE","COLLAR","CORSET","COTTON","CRAVAT","FEDORA","FLEECE","GIRDLE","HELMET","HOODIE","JACKET","JERSEY","KIMONO","LOAFER","MOHAIR","OUTFIT","POCKET","PONCHO","PYJAMA","ROMPER","SANDAL","SARONG","SCRUBS","SHORTS","SLACKS","SLEEVE","STRAPS","TIGHTS","TRUNKS","TURBAN","TUXEDO","VELVET","WALLET","ZIPPER"],
      7: ["APPAREL","CATSUIT","CHEMISE","EARRING","FASHION","GARMENT","HANDBAG","HOMBURG","MITTENS","MUFFLER","NECKTIE","SLIPPER","SNEAKER","STYLIST","SWEATER","TOPCOAT","TROUSER","UNIFORM"],
    },
  },
  {
    themeId: "en-a-famous-world-capitals",
    label: "Famous World Capitals",
    difficultyTier: "A",
    wordsByLength: {
      4: ["DOHA","KYIV","LIMA","OSLO","ROME"],
      5: ["ABUJA","AMMAN","CAIRO","DAKAR","DHAKA","HANOI","KABUL","PARIS","QUITO","RABAT","SEOUL","SOFIA","TOKYO","TUNIS"],
      6: ["ANKARA","ATHENS","BEIRUT","BERLIN","BOGOTA","DUBLIN","HARARE","HAVANA","KIGALI","LISBON","LONDON","LUSAKA","MADRID","MANILA","MAPUTO","MOSCOW","OTTAWA","PRAGUE","RIYADH","TEHRAN","VIENNA","WARSAW","ZAGREB"],
      7: ["ALGIERS","BAGHDAD","BEIJING","CARACAS","JAKARTA","NAIROBI","TRIPOLI","YEREVAN"],
    },
  },
  {
    themeId: "en-a-fruits",
    label: "Fruits",
    difficultyTier: "A",
    wordsByLength: {
      4: ["DATE","LIME","PEAR","PLUM"],
      5: ["APPLE","BERRY","GRAPE","GUAVA","LEMON","MANGO","MELON","OLIVE","PEACH","PECAN"],
      6: ["BANANA","CHERRY","CITRON","JUJUBE","LOQUAT","LYCHEE","ORANGE","PAPAYA","POMELO","TOMATO"],
      7: ["APRICOT","AVOCADO","COCONUT","CURRANT","KUMQUAT","PUMPKIN"],
    },
  },
  {
    themeId: "en-a-vegetables",
    label: "Vegetables",
    difficultyTier: "A",
    wordsByLength: {
      4: ["BEET","CORN","GUAR","KALE","KELP","LEEK","OKRA","PEAS","RAMP","TARO"],
      5: ["CHARD","CRESS","ONION","SWEDE"],
      6: ["BAMBOO","CARROT","CELERY","CHIVES","DAIKON","ENDIVE","FENNEL","GARLIC","GINGER","LENTIL","MANIOC","PEPPER","POTATO","RADISH","SPROUT","SQUASH","TURNIP"],
      7: ["ARUGULA","CABBAGE","LETTUCE","PARSNIP","SHALLOT","SOYBEAN","SPINACH","TRUFFLE"],
    },
  },
  {
    themeId: "en-a-musical-instruments",
    label: "Musical Instruments",
    difficultyTier: "A",
    wordsByLength: {
      4: ["BASS","DRUM","GONG","HARP","HORN","LUTE","LYRE","OBOE","TUBA"],
      5: ["BANJO","BONGO","CELLO","CONGA","DRUMS","FLUTE","KAZOO","ORGAN","PIANO","PIPES","SITAR","VIOLA"],
      6: ["CYMBAL","FIDDLE","GUITAR","VIOLIN"],
      7: ["BAGPIPE","BASSOON","DARBUKA","MARIMBA","OCARINA","PICCOLO","TRUMPET","UKULELE"],
    },
  },
  {
    themeId: "en-a-occupations",
    label: "Occupations",
    difficultyTier: "A",
    wordsByLength: {
      4: ["CHEF","COOK","KING","MAID","MONK","POET"],
      5: ["ACTOR","BAKER","CLERK","CLOWN","COACH","CODER","DIVER","GUARD","GUIDE","JUDGE","MASON","MAYOR","MINER","MODEL","NURSE","PILOT","QUEEN","RABBI","SCOUT","SMITH","TILER","TUTOR","USHER","VALET","VICAR"],
      6: ["ARCHER","ARTIST","AUTHOR","BANKER","BARBER","BARMAN","BISHOP","BREWER","BROKER","BUTLER","CONSUL","DEPUTY","DOCTOR","DRIVER","EDITOR","FARMER","GOLFER","HUNTER","INTERN","JAILER","JESTER","JOCKEY","LAWYER","PASTOR","POTTER","PRIEST","PRINCE","RANGER","SAILOR","SAWYER","SCRIBE","SELLER","SINGER","TAILOR","TELLER","TRADER","TYPIST","VENDOR","WAITER","WARDEN","WEAVER","WELDER","WRITER"],
      7: ["ADVISER","ANALYST","ATHLETE","BARISTA","BASSIST","BUILDER","BURGLAR","BUTCHER","CAPTAIN","CASHIER","CATERER","CELLIST","CHEMIST","CLEANER","COBBLER","CORONER","COURIER","CURATOR","DENTIST","DOORMAN","DRAFTER","DRUMMER","EMPEROR","FIREMAN","FLORIST","FLUTIST","FOREMAN","GENERAL","HARPIST","HOSTESS","JANITOR","JEWELER","LABORER","MAILMAN","MANAGER","MIDWIFE","PAINTER","PEDDLER","PIANIST","PLUMBER","POSTMAN","RANCHER","REFEREE","RETIREE","SENATOR","SHERIFF","SOLDIER","STEWARD","STUDENT","SURGEON","SWIMMER","TEACHER","VETERAN","WARRIOR"],
    },
  },
  {
    themeId: "en-a-sports",
    label: "Sports",
    difficultyTier: "A",
    wordsByLength: {
      4: ["GOLF","JUDO","POLO","SUMO"],
      5: ["DARTS","RUGBY"],
      6: ["AIKIDO","BASKET","BIKING","BOXING","DIVING","HOCKEY","KARATE","RACING","ROWING","SKIING","SOCCER","SPRINT","SQUASH","TENNIS"],
      7: ["ARCHERY","BOWLING","CRICKET","CROQUET","CURLING","CYCLING","FENCING","FISHING","HURLING","NETBALL","PARKOUR","RUNNING","SAILING","SKATING","SNOOKER","SURFING"],
    },
    wordLengthComposition: [{"length":4,"count":3},{"length":6,"count":2},{"length":7,"count":1}],
  },
  {
    themeId: "en-a-modes-of-transport",
    label: "Modes of Transport",
    difficultyTier: "A",
    wordsByLength: {
      4: ["BIKE","BOAT","CART","JEEP","LIMO","RAFT","SHIP","TANK","TAXI","TRAM"],
      5: ["BARGE","BUGGY","CANOE","FERRY","LORRY","METRO","PLANE","TRAIN","TRUCK","WAGON","YACHT"],
      6: ["DINGHY","GALLEY","GLIDER","LITTER","ROCKET","SLEIGH","SUBWAY","TANKER","VESSEL"],
      7: ["BICYCLE","CARAVAN","CRUISER","FRIGATE","GONDOLA","MINIBUS","SCOOTER","TRAMWAY","TROLLEY"],
    },
  },
  {
    themeId: "en-a-countries",
    label: "Countries",
    difficultyTier: "A",
    wordsByLength: {
      4: ["CHAD","CUBA","FIJI","IRAN","IRAQ","LAOS","MALI","NIUE","OMAN","PERU","TOGO"],
      5: ["BENIN","CHILE","CHINA","CONGO","EGYPT","GABON","GHANA","HAITI","INDIA","ITALY","JAPAN","KENYA","LIBYA","MALTA","NAURU","NEPAL","NIGER","PALAU","QATAR","SAMOA","SPAIN","SUDAN","SYRIA","TONGA","YEMEN"],
      6: ["ANGOLA","BELIZE","BHUTAN","BRAZIL","BRUNEI","CANADA","CYPRUS","FRANCE","GAMBIA","GREECE","GUINEA","GUYANA","ISRAEL","JORDAN","KOSOVO","KUWAIT","LATVIA","MALAWI","MEXICO","MONACO","NORWAY","PANAMA","POLAND","RUSSIA","RWANDA","SERBIA","SWEDEN","TAIWAN","TURKEY","TUVALU","UGANDA","ZAMBIA"],
      7: ["ALBANIA","ALGERIA","ANDORRA","ARMENIA","AUSTRIA","BAHAMAS","BAHRAIN","BELARUS","BELGIUM","BOLIVIA","BURUNDI","COMOROS","CROATIA","DENMARK","ECUADOR","ERITREA","ESTONIA","FINLAND","GEORGIA","GERMANY","GRENADA","HUNGARY","ICELAND","IRELAND","JAMAICA","LEBANON","LESOTHO","LIBERIA","MOLDOVA","MOROCCO","MYANMAR","NAMIBIA","NIGERIA","ROMANIA","SENEGAL","SOMALIA","TUNISIA","UKRAINE","URUGUAY","VANUATU","VIETNAM"],
    },
  },
  {
    themeId: "en-a-vegan-food",
    label: "Vegan Food",
    difficultyTier: "A",
    wordsByLength: {
      4: ["CORN","GUAR","KALE","LEEK","LIME","MINT","MISO","OATS","PEAR","PLUM","RICE","SAGE","SALT","TOFU"],
      5: ["ACORN","AGAVE","ANISE","APPLE","BAGEL","BASIL","BEANS","BREAD","CLOVE","COCOA","CRESS","CUMIN","FLOUR","GRAPE","GUAVA","LEMON","MANGO","MAPLE","MELON","OLIVE","ONION","PEACH","PECAN","SUGAR","SUMAC","THYME","WHEAT"],
      6: ["ALMOND","BANANA","BARLEY","BULGUR","CARROT","CASHEW","CELERY","CHERRY","CHIVES","CITRON","ENDIVE","FENNEL","GARLIC","GINGER","HUMMUS","JUJUBE","LENTIL","LOQUAT","LYCHEE","MANIOC","NOODLE","ORANGE","PAPAYA","PEANUT","PEPPER","PICKLE","POMELO","POTATO","QUINOA","RADISH","RAISIN","SEITAN","SESAME","SORBET","SPROUT","TAHINI","TEMPEH","TOMATO","TURNIP","WALNUT","WASABI"],
      7: ["APRICOT","ARUGULA","AVOCADO","CABBAGE","CARAWAY","CHICORY","CHUTNEY","COCONUT","FALAFEL","KETCHUP","KUMQUAT","LETTUCE","MUSTARD","OATMEAL","OREGANO","PAPRIKA","PARSLEY","PARSNIP","PUMPKIN","RHUBARB","SAFFRON","SHALLOT","SOYBEAN","SPINACH","TRUFFLE","VANILLA","VINEGAR"],
    },
  },
  {
    themeId: "en-a-non-vegan-food",
    label: "Non-Vegan Food",
    difficultyTier: "A",
    wordsByLength: {
      4: ["BEEF","CLAM","CRAB","CURD","DUCK","GHEE","LAMB","LARD","MILK","PORK","TUNA","VEAL","WHEY"],
      5: ["BACON","CREAM","GOOSE","KEFIR","LIVER","QUAIL","SQUAB","SQUID","STEAK","TROUT"],
      6: ["BUTTER","CAVIAR","CHEESE","MUSSEL","MUTTON","OMELET","OYSTER","PIGEON","PRAWNS","RABBIT","SALAMI","SALMON","SHRIMP","TALLOW","TURKEY","YOGURT"],
      7: ["BRISKET","CHEDDAR","CHICKEN","CHORIZO","CUSTARD","GELATIN","LOBSTER","SARDINE","SAUSAGE","VENISON"],
    },
  },
  {
    themeId: "en-a-mammals",
    label: "Mammals",
    difficultyTier: "A",
    wordsByLength: {
      4: ["BEAR","BOAR","DEER","GOAT","HARE","LION","MOLE","PUMA","SEAL"],
      5: ["BISON","CAMEL","HORSE","HYENA","KOALA","LEMUR","LLAMA","MOOSE","MOUSE","OKAPI","OTTER","PANDA","SHEEP","SHREW","SKUNK","SLOTH","TAPIR","TIGER","WHALE","ZEBRA"],
      6: ["BABOON","BADGER","BEAGLE","BEAVER","BOBCAT","BONOBO","COUGAR","COYOTE","DONKEY","FERRET","GERBIL","GIBBON","JAGUAR","MARMOT","MONKEY","OCELOT","RABBIT","WAPITI","WEASEL","WOMBAT"],
      7: ["BUFFALO","CARIBOU","CHEETAH","DOLPHIN","GAZELLE","GIRAFFE","GORILLA","HAMSTER","LEOPARD","MACAQUE","MAMMOTH","MANATEE","NARWHAL","OPOSSUM","RACCOON","WALLABY"],
    },
  },
  {
    themeId: "en-b-herbs-spices",
    label: "Herbs & Spices",
    difficultyTier: "B",
    wordsByLength: {
      4: ["DILL","MACE","MINT","SAGE"],
      5: ["ANISE","BASIL","CUMIN","SUMAC","THYME"],
      6: ["CLOVES","FENNEL","GINGER","NUTMEG","PEPPER","SAVORY"],
      7: ["CARAWAY","CHERVIL","OREGANO","PAPRIKA","PARSLEY","SAFFRON"],
    },
  },
  {
    themeId: "en-b-human-habitats",
    label: "Human Habitats",
    difficultyTier: "B",
    wordsByLength: {
      4: ["JAIL"],
      5: ["ABBEY","CABIN","HOTEL","HOUSE","IGLOO","LODGE","MANOR","MOTEL","RANCH","TOWER","VILLA"],
      6: ["ASYLUM","CASTLE","CHALET","DUPLEX","FAVELA","HOSTEL","PALACE","PRISON"],
      7: ["COTTAGE","SHELTER"],
    },
    wordLengthComposition: [{"length":4,"count":1},{"length":5,"count":3},{"length":6,"count":1},{"length":7,"count":1}],
  },
  {
    themeId: "en-b-alcoholic-beverages",
    label: "Alcoholic Beverages",
    difficultyTier: "B",
    wordsByLength: {
      4: ["ARAK","BEER","MEAD","OUZO","RAKI","SAKE","WINE"],
      5: ["CIDER","LAGER","PORTO","STOUT","VODKA"],
      6: ["BRANDY","COGNAC","GRAPPA","KIRSCH","LIQUOR","PASTIS","SHERRY"],
      7: ["BOURBON","CACHACA","MARTINI","MASTIKA","SAMBUCA","SANGRIA","TEQUILA","WHISKEY"],
    },
  },
  {
    themeId: "en-b-non-alcoholic-beverages",
    label: "Non-Alcoholic Beverages",
    difficultyTier: "B",
    wordsByLength: {
      4: ["CHAI","COLA","MATE","MILK","SODA"],
      5: ["BROTH","COCOA","JUICE","KEFIR","LASSI","LATTE","MOCHA","PUNCH","SHAKE","SLUSH","SYRUP","TONIC","WATER"],
      6: ["COFFEE","MATCHA","NECTAR","SQUASH"],
      7: [],
    },
    wordLengthComposition: [{"length":4,"count":3},{"length":5,"count":2},{"length":6,"count":1}],
  },
  {
    themeId: "en-b-hand-tools",
    label: "Hand Tools",
    difficultyTier: "B",
    wordsByLength: {
      4: ["FILE"],
      5: ["CLAMP","DRILL","RULER"],
      6: ["CHISEL","HAMMER","JIGSAW","MALLET","PLIERS","SOCKET","TROWEL","WRENCH"],
      7: ["HACKSAW","SCRAPER","SPANNER","STAPLER"],
    },
    wordLengthComposition: [{"length":4,"count":1},{"length":5,"count":3},{"length":6,"count":1},{"length":7,"count":1}],
  },
  {
    themeId: "en-b-furniture",
    label: "Furniture",
    difficultyTier: "B",
    wordsByLength: {
      4: ["CRIB","DESK","SOFA"],
      5: ["BENCH","CHAIR","COUCH","FUTON","STOOL","TABLE"],
      6: ["BUFFET","CRADLE","DAYBED","THRONE"],
      7: ["CABINET","DRESSER","HAMMOCK","HASSOCK"],
    },
  },
  {
    themeId: "en-b-tableware-kitchen-utensils",
    label: "Tableware & Kitchen Utensils",
    difficultyTier: "B",
    wordsByLength: {
      4: ["BOWL","FORK","MOLD"],
      5: ["GLASS","KNIFE","LADLE","PLATE","RICER","SHEAR","SIEVE","SPOON","TONGS","WHISK"],
      6: ["BOTTLE","CARAFE","FUNNEL","GRATER","KETTLE","NAPKIN","PEELER","SAUCER","SKEWER","SLICER","TEAPOT","ZESTER"],
      7: ["COASTER","CUTLERY","INFUSER","PITCHER","PLATTER","POACHER","SPATULA"],
    },
  },
  {
    themeId: "en-b-sports-equipment",
    label: "Sports Equipment",
    difficultyTier: "B",
    wordsByLength: {
      4: ["BALL","BIKE","CLUB","CONE","DART","DISC","FINS","GOAL","HOOP","POLE","PUCK","ROPE","SHOE"],
      5: ["ARROW","BATON","BLADE","DARTS","GLOVE","SKATE","STICK"],
      6: ["BASKET","CLEATS","HELMET","HURDLE","JERSEY","PADDLE","RACKET","SADDLE","TARGET","TRUNKS","WICKET"],
      7: ["BARBELL","BICYCLE","GOGGLES","SHINPAD","SNEAKER","WHISTLE"],
    },
  },
  {
    themeId: "en-b-bodies-of-water",
    label: "Bodies of Water",
    difficultyTier: "B",
    wordsByLength: {
      4: ["GULF","LAKE","MARE","POND","POOL"],
      5: ["CANAL","CREEK","FJORD","OASIS","OCEAN","RIVER","SWAMP"],
      6: ["LAGOON","RAPIDS","SOURCE","SPRING","STRAIT","STREAM"],
      7: ["ESTUARY","GLACIER","ICEBERG","RIVULET","TORRENT"],
    },
  },
  {
    themeId: "en-b-sports-facilities",
    label: "Sports Facilities",
    difficultyTier: "B",
    wordsByLength: {
      4: ["DOJO","HALL","LANE","POOL","RING","RINK"],
      5: ["ARENA","COURT","FIELD","PISTE","RANGE","TRACK"],
      6: ["COURSE"],
      7: ["CIRCUIT","SAUSAGE","STADIUM"],
    },
    wordLengthComposition: [{"length":4,"count":3},{"length":5,"count":2},{"length":7,"count":1}],
  },
  {
    themeId: "en-c-jewelry",
    label: "Jewelry",
    difficultyTier: "C",
    wordsByLength: {
      4: ["JADE","ONYX","OPAL","RING","RUBY","TORC"],
      5: ["AGATE","AMBER","BERYL","CHAIN","PEARL","TIARA","TOPAZ"],
      6: ["AMULET","ANKLET","BANGLE","BROOCH","CHOKER","DIADEM","GARNET","JASPER","LOCKET","SIGNET","SPINEL","ZIRCON"],
      7: ["APATITE","CITRINE","DIAMOND","EARRING","EMERALD","PENDANT"],
    },
  },
  {
    themeId: "en-c-garden-tools",
    label: "Garden Tools",
    difficultyTier: "C",
    wordsByLength: {
      4: ["FORK","HOSE","RAKE"],
      5: ["EDGER","MOWER","SPADE"],
      6: ["LOPPER","PRUNER","SHEARS","SHOVEL","SICKLE","TROWEL","WEEDER"],
      7: [],
    },
    wordLengthComposition: [{"length":4,"count":3},{"length":5,"count":2},{"length":6,"count":1}],
  },
  {
    themeId: "en-c-cleaning-supplies",
    label: "Cleaning Supplies",
    difficultyTier: "C",
    wordsByLength: {
      4: ["SOAP"],
      5: ["BROOM","BRUSH","CLOTH","SPRAY","WIPES"],
      6: ["BLEACH","BUCKET","DUSTER","GLOVES","POLISH","SPONGE","TISSUE","VACUUM"],
      7: ["CLEANER","DUSTPAN","PLUNGER","SCOURER","SCRAPER"],
    },
    wordLengthComposition: [{"length":4,"count":1},{"length":5,"count":3},{"length":6,"count":1},{"length":7,"count":1}],
  },
  {
    themeId: "en-c-gemstones",
    label: "Gemstones",
    difficultyTier: "C",
    wordsByLength: {
      4: ["JADE","ONYX","OPAL","RUBY"],
      5: ["AGATE","AMBER","BERYL","CORAL","LAPIS","PEARL","TOPAZ"],
      6: ["GARNET","IOLITE","JASPER","QUARTZ","SPINEL","ZIRCON"],
      7: ["APATITE","AZURITE","CITRINE","DIAMOND","EMERALD","KYANITE","PERIDOT"],
    },
  },
  {
    themeId: "en-c-trees",
    label: "Trees",
    difficultyTier: "C",
    wordsByLength: {
      4: ["PALM","PINE"],
      5: ["ALDER","BEECH","BIRCH","CEDAR","HAZEL","LARCH","MAPLE","OLIVE"],
      6: ["ACACIA","BANYAN","BAOBAB","LOCUST","POPLAR","SPRUCE","WALNUT","WILLOW"],
      7: ["CYPRESS","DOGWOOD","HICKORY","JUNIPER","REDWOOD","SEQUOIA"],
    },
    wordLengthComposition: [{"length":5,"count":3},{"length":6,"count":2},{"length":7,"count":1}],
    allowFreeDirections: true,
  },
  {
    themeId: "en-c-weaponry",
    label: "Weaponry",
    difficultyTier: "C",
    wordsByLength: {
      4: ["AMMO","BOMB","MINE"],
      5: ["RIFLE","SABER","SPEAR","SWORD"],
      6: ["BULLET","CANNON","DAGGER","MORTAR","MUSKET","PISTOL"],
      7: ["BAYONET","GRENADE","MISSILE","TORPEDO"],
    },
  },
  {
    themeId: "en-c-beach-accessories",
    label: "Beach Accessories",
    difficultyTier: "C",
    wordsByLength: {
      4: ["BALL","FINS"],
      5: ["TOWEL","VISOR"],
      6: ["COOLER","SUNHAT"],
      7: ["FRISBEE","GOGGLES","LOUNGER","SANDALS","SNORKEL"],
    },
    wordLengthComposition: [{"length":4,"count":1},{"length":5,"count":1},{"length":6,"count":2},{"length":7,"count":2}],
    allowFreeDirections: true,
  },
  {
    themeId: "en-c-sweets-and-desserts",
    label: "Sweets and Desserts",
    difficultyTier: "C",
    wordsByLength: {
      4: ["FLAN"],
      5: ["CANDY","CREPE","DONUT","FUDGE","JELLY","SCONE","TORTE"],
      6: ["CHURRO","COOKIE","ECLAIR","GELATO","MOUSSE","MUFFIN","NOUGAT","PASTRY","SORBET","SUNDAE","TOFFEE","WAFFLE"],
      7: ["BAKLAVA","BISCUIT","BROWNIE","CANNOLI","COBBLER","CUPCAKE","CUSTARD","FRITTER","MACARON","PARFAIT","POPOVER","PRALINE","PUDDING","SHERBET","SOUFFLE","SPUMONI","STRUDEL","TRUFFLE"],
    },
    wordLengthComposition: [{"length":4,"count":1},{"length":5,"count":3},{"length":6,"count":1},{"length":7,"count":1}],
  },
  {
    themeId: "en-c-time-timekeeping",
    label: "Time & Timekeeping",
    difficultyTier: "C",
    wordsByLength: {
      4: ["HOUR","LATE","PAST","SOON","THEN","WEEK","YEAR"],
      5: ["AFTER","CLOCK","DELAY","EARLY","EPOCH","MONTH","TARDY","TIMER","TODAY","WATCH"],
      6: ["ANNUAL","BEFORE","DECADE","FUTURE","MINUTE","MOMENT","PERIOD","SEASON","SECOND"],
      7: ["CENTURY","MORNING","PRESENT","SUNDIAL","TONIGHT"],
    },
  },
  {
    themeId: "en-c-flowers",
    label: "Flowers",
    difficultyTier: "C",
    wordsByLength: {
      4: ["IRIS","LILY","ROSE"],
      5: ["ASTER","DAISY","LILAC","LOTUS","PANSY","PEONY","PHLOX","POPPY","TULIP"],
      6: ["AZALEA","COSMOS","CROCUS","DAHLIA","ORCHID","VIOLET","ZINNIA"],
      7: ["BEGONIA","FREESIA","JASMINE","PETUNIA","VERBENA"],
    },
  },
  {
    themeId: "en-c-the-calendar",
    label: "The Calendar",
    difficultyTier: "C",
    wordsByLength: {
      4: ["DATE","JULY","JUNE","LEAP"],
      5: ["APRIL","ARIES","LIBRA","MARCH","VIRGO"],
      6: ["AUGUST","AUTUMN","CANCER","FRIDAY","GEMINI","MONDAY","PISCES","SPRING","SUMMER","SUNDAY","TAURUS","WINTER"],
      7: ["EQUINOX","JANUARY","OCTOBER","SCORPIO","TUESDAY"],
    },
  },
  {
    themeId: "en-d-musical-styles",
    label: "Musical Styles",
    difficultyTier: "D",
    wordsByLength: {
      4: ["ACID","FOLK","FUNK","JAZZ","PUNK","ROCK","SOCA","SOUL","ZOUK"],
      5: ["BLUES","CONGA","DISCO","HOUSE","MAMBO","METAL","OPERA","SALSA","SAMBA","SWING"],
      6: ["BOLERO","GARAGE","GOSPEL","GRUNGE","HIPHOP","MOTOWN","REGGAE","TECHNO","TRANCE"],
      7: ["BAROQUE","BRITPOP","CALYPSO","COUNTRY","DUBSTEP","ELECTRO","RAGTIME"],
    },
  },
  {
    themeId: "en-d-light-sources",
    label: "Light Sources",
    difficultyTier: "D",
    wordsByLength: {
      4: ["BULB","FIRE","LAMP","MOON","NEON","STAR"],
      5: ["COMET","EMBER","FLAME","FLARE","FLASH","LASER","MATCH","SPARK","TORCH"],
      6: ["BEACON","CANDLE","METEOR"],
      7: ["FIREFLY","LANTERN","LIGHTER"],
    },
  },
  {
    themeId: "en-d-leaders",
    label: "Leaders",
    difficultyTier: "D",
    wordsByLength: {
      4: ["DOGE","EMIR","GURU","KHAN","KING","POPE","SHAH","TSAR"],
      5: ["QUEEN","SHEIK"],
      6: ["CALIPH","PRINCE","REGENT","SHOGUN","SULTAN","VIZIER"],
      7: ["CZARINA","EMPRESS","MONARCH","PHARAOH","TSARINA"],
    },
    wordLengthComposition: [{"length":4,"count":3},{"length":6,"count":2},{"length":7,"count":1}],
  },
  {
    themeId: "en-d-car-parts",
    label: "Car Parts",
    difficultyTier: "D",
    wordsByLength: {
      4: ["AXLE","DOOR","FUSE","HOOD","HORN","LOCK","RIMS","TIRE"],
      5: ["ALARM","GAUGE","MOTOR","PEDAL","WHEEL"],
      6: ["AIRBAG","BONNET","BRAKES","BUMPER","CLUTCH","ENGINE","FILTER","GASKET","HEATER","MIRROR","PISTON","WINDOW"],
      7: ["CHASSIS","CONSOLE","GEARBOX","MUFFLER","SPOILER","STARTER","SUNROOF"],
    },
  },
  {
    themeId: "en-d-animal-body-parts",
    label: "Animal Body Parts",
    difficultyTier: "D",
    wordsByLength: {
      4: ["BEAK","CLAW","FANG","FOOT","GILL","HOOF","HORN","HUMP","MANE","TAIL","TUSK","WING"],
      5: ["SHELL","SNOUT","TRUNK"],
      6: ["SCALES"],
      7: ["ANTENNA","CUTICLE","FEATHER","FLIPPER","STINGER"],
    },
    wordLengthComposition: [{"length":4,"count":3},{"length":5,"count":2},{"length":7,"count":1}],
  },
  {
    themeId: "en-d-animal-babies",
    label: "Animal Babies",
    difficultyTier: "D",
    wordsByLength: {
      4: ["CALF","COLT","CRIA","FAWN","FOAL","JOEY","PUPA"],
      5: ["CHICK","ELVER","LARVA","NYMPH","OWLET","POULT","PUPPY","SHOAT","SQUAB"],
      6: ["CYGNET","EAGLET","KITTEN","MAGGOT","PIGLET"],
      7: ["GOSLING","LAMBKIN","TADPOLE"],
    },
  },
  {
    themeId: "en-d-pizza-toppings",
    label: "Pizza Toppings",
    difficultyTier: "D",
    wordsByLength: {
      4: ["BEEF","BRIE","FETA","PEAS","TUNA"],
      5: ["BACON","BASIL","FUNGI","PESTO"],
      6: ["CAPERS","CHEESE","CHIVES","GARLIC","OLIVES","ONIONS","PEPPER","SALAMI","SALMON","TOMATO","TURKEY"],
      7: ["AVOCADO","CHEDDAR","CHICKEN","CHORIZO","OREGANO","RICOTTA","SAUSAGE","SPINACH"],
    },
  },
  {
    themeId: "en-d-dog-breeds",
    label: "Dog Breeds",
    difficultyTier: "D",
    wordsByLength: {
      4: [],
      5: ["AKITA","BOXER","CORGI","HUSKY","SPITZ"],
      6: ["BEAGLE","BRIARD","COLLIE","POODLE","WESTIE"],
      7: ["BASENJI","HARRIER","MALTESE","POINTER","SAMOYED","SPANIEL","TERRIER"],
    },
    wordLengthComposition: [{"length":5,"count":3},{"length":6,"count":2},{"length":7,"count":1}],
    allowFreeDirections: true,
  },
  {
    themeId: "en-d-weather-climate",
    label: "Weather & Climate",
    difficultyTier: "D",
    wordsByLength: {
      4: ["COLD","HAIL","HEAT","RAIN","SNOW","WIND"],
      5: ["CLOUD","FROST","SLEET","STORM"],
      6: ["AUTUMN","BREEZE","SEASON","SPRING","SUMMER","WINTER"],
      7: ["CYCLONE","DROUGHT","TEMPEST","THUNDER","TORNADO","TWISTER","TYPHOON"],
    },
  },
  {
    themeId: "en-d-fish",
    label: "Fish",
    difficultyTier: "D",
    wordsByLength: {
      4: ["BASS","CARP","PIKE","SOLE","TUNA"],
      5: ["PERCH","SHARK","TROUT"],
      6: ["MARLIN","SALMON","TURBOT"],
      7: ["ANCHOVY","CATFISH","HADDOCK","HERRING","PIRANHA","SARDINE"],
    },
  },
  {
    themeId: "en-d-famous-brands",
    label: "Famous Brands",
    difficultyTier: "D",
    wordsByLength: {
      4: ["ACER","AVON","BOSE","DELL","DIOR","DOVE","FILA","FUJI","LEGO","MARS","NIKE","OLAY","OREO","PUMA","SONY","TWIX","VISA"],
      5: ["APPLE","ASICS","CANON","CASIO","CREST","DOLBY","EVIAN","FANTA","GUCCI","HALLS","HEINZ","HONDA","INTEL","KNORR","KRAFT","LINDT","MAGGI","NIKON","NIVEA","NOKIA","PEPSI","PRADA","ROLEX","SANYO","SHARP","TEFAL","TESLA","TWIRL","UMBRO","VICHY","WELLA","XEROX"],
      6: ["ADIDAS","AMAZON","ARMANI","BOUNTY","CHANEL","CRUNCH","GALAXY","GIBSON","GODIVA","GOOGLE","HENKEL","HERMES","HOOVER","LIPTON","MATTEL","MENTOS","ORACLE","RAYBAN","REEBOK","REVLON","REXONA","SIGNAL","SMACKS","SPRITE","TAMPAX","VIAGRA"],
      7: ["AIRNESS","BARILLA","BUITONI","CADBURY","CARTIER","CLARINS","COLGATE","CRAYOLA","GRUNDIG","HISENSE","KENWOOD","KICKERS","KLEENEX","LACOSTE","LANCOME","MAIZENA","MIRINDA","NESCAFE","NUTELLA","PAMPERS","PANTENE","PERRIER","PHILIPS","SAMSUNG","SUNSILK","TOSHIBA","VERSACE"],
    },
  },
  {
    themeId: "en-d-music",
    label: "Music",
    difficultyTier: "D",
    wordsByLength: {
      4: ["ALTO","ARIA","BAND","BASS","BEAT","CLEF","DUET","NOTE","SOLO","SONG","TRIO","TUNE"],
      5: ["CANON","CHORD","LYRIC","OPERA","PITCH","TEMPO","TENOR","THEME","VERSE"],
      6: ["ADAGIO","ANTHEM","ATONAL","AUBADE","BALLAD","CHORUS","MELODY","OCTAVE","RHYTHM","SONATA","TIMBRE","UNISON"],
      7: ["CADENCE","CANTATA","CONCERT","HARMONY","PRELUDE","QUARTET","QUINTET","SOLFEGE","SOPRANO"],
    },
  },
  {
    themeId: "en-e-plant-anatomy",
    label: "Plant Anatomy",
    difficultyTier: "E",
    wordsByLength: {
      4: ["BARK","BUDS","BULB","LEAF","NODE","PORE","ROOT","SEED","STEM","TWIG"],
      5: ["FRUIT","PETAL","SEPAL","SPINE","THORN"],
      6: ["BRANCH","FLOWER","NECTAR","PISTIL","POLLEN","STAMEN","STIGMA"],
      7: ["COROLLA","TENDRIL"],
    },
  },
  {
    themeId: "en-e-liquid-containers",
    label: "Liquid Containers",
    difficultyTier: "E",
    wordsByLength: {
      4: ["CASK","EWER","TANK","VASE","VIAL"],
      5: ["CROCK","CRUET","FLASK","GLASS","STEIN"],
      6: ["BARREL","BEAKER","BOTTLE","BUCKET","CARAFE","GOBLET","KETTLE","TEAPOT"],
      7: ["AMPHORA","CANTEEN"],
    },
  },
  {
    themeId: "en-e-solid-containers",
    label: "Solid Containers",
    difficultyTier: "E",
    wordsByLength: {
      4: ["CASE"],
      5: ["CADDY","CHEST","CRATE","PURSE","TRUNK"],
      6: ["BASKET","CARTON","DRAWER","PACKET","PARCEL","POCKET","SACHET","WALLET"],
      7: ["LUGGAGE"],
    },
    wordLengthComposition: [{"length":4,"count":1},{"length":5,"count":3},{"length":6,"count":2}],
  },
  {
    themeId: "en-e-colors",
    label: "Colors",
    difficultyTier: "E",
    wordsByLength: {
      4: ["AQUA","BLUE","CYAN","GOLD","GRAY","JADE","PINK"],
      5: ["AMBER","AZURE","BEIGE","BLACK","BROWN","GREEN","IVORY","LILAC","MAUVE","OLIVE","PEACH","SEPIA","WHITE"],
      6: ["ALMOND","CHERRY","COPPER","INDIGO","MAROON","ORANGE","PURPLE","SILVER","VIOLET","YELLOW"],
      7: ["APRICOT","EMERALD","MAGENTA"],
    },
  },
  {
    themeId: "en-e-chemical-elements",
    label: "Chemical Elements",
    difficultyTier: "E",
    wordsByLength: {
      4: ["GOLD","IRON","LEAD","NEON","ZINC"],
      5: ["ARGON","BORON","RADON","XENON"],
      6: ["BARIUM","CARBON","CERIUM","COBALT","COPPER","CURIUM","ERBIUM","HELIUM","INDIUM","IODINE","NICKEL","OSMIUM","OXYGEN","RADIUM","SILVER","SODIUM","SULFUR"],
      7: ["ARSENIC","BISMUTH","BOHRIUM","BROMINE","CADMIUM","CALCIUM","DUBNIUM","GALLIUM","HAFNIUM","IRIDIUM","KRYPTON","LITHIUM","MERCURY","SILICON","THORIUM","URANIUM"],
    },
  },
  {
    themeId: "en-e-animal-groups",
    label: "Animal Groups",
    difficultyTier: "E",
    wordsByLength: {
      4: ["BEVY","HERD","PACK"],
      5: ["BROOD","FLOCK","HORDE","PRIDE","SHOAL","SWARM","TROOP"],
      6: ["CLUTCH","COLONY","LITTER"],
      7: [],
    },
    wordLengthComposition: [{"length":4,"count":3},{"length":5,"count":2},{"length":6,"count":1}],
  },
  {
    themeId: "en-e-human-bones",
    label: "Human Bones",
    difficultyTier: "E",
    wordsByLength: {
      4: ["RIBS","ULNA"],
      5: ["FEMUR","INCUS","SKULL","TALUS","TIBIA","VOMER"],
      6: ["COCCYX","FIBULA","PELVIS","RADIUS","SACRUM","STAPES"],
      7: ["HUMERUS","MALLEUS","MAXILLA","PATELLA","SCAPULA","STERNUM"],
    },
    wordLengthComposition: [{"length":5,"count":3},{"length":6,"count":2},{"length":7,"count":1}],
    allowFreeDirections: true,
  },
  {
    themeId: "en-e-metals",
    label: "Metals",
    difficultyTier: "E",
    wordsByLength: {
      4: ["GOLD","IRON","ZINC"],
      5: ["BRASS","STEEL"],
      6: ["BRONZE","CHROME","COBALT","COPPER","NICKEL","SILVER"],
      7: ["LITHIUM","MERCURY","THORIUM","URANIUM"],
    },
    wordLengthComposition: [{"length":4,"count":3},{"length":6,"count":2},{"length":7,"count":1}],
  },
  {
    themeId: "en-e-works-of-art",
    label: "Works of Art",
    difficultyTier: "E",
    wordsByLength: {
      4: ["EPIC","HYMN","PLAY","POEM","SONG"],
      5: ["ALBUM","DANCE","ELEGY","MOVIE","MURAL","NOVEL","OPERA","PHOTO","PROSE","PSALM"],
      6: ["ANTHEM","BALLAD","COMEDY","EFFIGY","MOSAIC","SKETCH","SONATA","SONNET","STATUE","TATTOO"],
      7: ["CONCERT","EPIGRAM","MUSICAL","POTTERY","REQUIEM"],
    },
  },
  {
    themeId: "en-e-birds",
    label: "Birds",
    difficultyTier: "E",
    wordsByLength: {
      4: ["CROW","DUCK","GULL","HAWK","IBIS","KIWI","SWAN"],
      5: ["CRANE","EAGLE","FINCH","GOOSE","HERON","MACAW","QUAIL","RAVEN","STORK"],
      6: ["CONDOR","CUCKOO","FALCON","GROUSE","MAGPIE","MARTIN","OSPREY","PARROT","PIGEON","TOUCAN","TURKEY"],
      7: ["BUZZARD","HARRIER","KESTREL","PEAFOWL","PELICAN","PENGUIN","SPARROW","SWALLOW","VULTURE","WARBLER"],
    },
  },
  {
    themeId: "en-e-lakes-and-rivers",
    label: "Lakes and Rivers",
    difficultyTier: "E",
    wordsByLength: {
      4: ["ARAL","AVON","ERIE","NESS","NILE"],
      5: ["CONGO","HURON","INDUS","LEMAN","LOIRE","NIGER","RHINE","SEINE","VOLGA","VOLTA"],
      6: ["AMAZON","BAIKAL","DANUBE","GANGES","JORDAN","LOMOND","MALAWI","MEKONG","THAMES","TIGRIS"],
      7: ["CASPIAN","ONTARIO","ORINOCO","YANGTZE","ZAMBEZI"],
    },
  },
  {
    themeId: "en-e-currencies",
    label: "Currencies",
    difficultyTier: "E",
    wordsByLength: {
      4: ["BAHT","DIME","DRAM","EURO","HWAN","INTI","KUNA","LIRA","MARK","PESO","REAL","YANG","YUAN"],
      5: ["BUDJU","DINAR","FRANC","KRONA","LIBRA","LIVRE","PAISA","POUND","RIYAL","RUBLE","RUPEE","SCUDO","SUCRE","ZLOTY"],
      6: ["DENIER","DINERO","DIRHAM","DOLLAR","ESCUDO","FLORIN","GINEIH","GOURDE","KORUNA","PESETA","SHEKEL","TANGKA","THALER"],
      7: ["AFGHANI","AUSTRAL","BOLIVAR","CRUZADO","DRACHMA","PENNING","PIASTRA"],
    },
  },
  {
    themeId: "en-e-languages",
    label: "Languages",
    difficultyTier: "E",
    wordsByLength: {
      4: ["THAI","URDU","ZULU"],
      5: ["CZECH","DUTCH","FARSI","GREEK","HAKKA","HINDI","IRISH","LATIN","MALAY","MAORI","SWATI","TAJIK","TAMIL","UZBEK","WELSH","XIANG"],
      6: ["ABKHAZ","ARABIC","BASQUE","BERBER","DANISH","FRENCH","GAELIC","GERMAN","HEBREW","KAZAKH","KOREAN","KYRGYZ","NEPALI","POLISH","SLOVAK","SOMALI"],
      7: ["AMHARIC","BENGALI","BOSNIAN","BURMESE","CATALAN","CHINESE","ENGLISH","FINNISH","FRISIAN","ITALIAN","KURDISH","LATVIAN","MALTESE","PERSIAN","PUNJABI","QUECHUA","RUSSIAN","SERBIAN","SLOVENE","SPANISH","SWAHILI","SWEDISH","TIBETAN","TURKISH","TURKMEN","YIDDISH"],
    },
  },
  {
    themeId: "en-e-african-cities",
    label: "African Cities",
    difficultyTier: "E",
    wordsByLength: {
      4: ["KANO","LAMU","MAUN","SUEZ"],
      5: ["ACCRA","AKURE","BENIN","CAIRO","DAKAR","GIZEH","LAGOS","RABAT","TUNIS","WARRI"],
      6: ["AGADIR","BAMAKO","BANGUI","DOUALA","DURBAN","HARARE","IBADAN","ILORIN","KADUNA","KIGALI","KUMASI","LUSAKA","MAPUTO","MATOLA","NIAMEY","SOWETO"],
      7: ["ABIDJAN","ALGIERS","CONAKRY","KAMPALA","MOMBASA","NAIROBI","TANGIER","TRIPOLI","YAOUNDE"],
    },
  },
  {
    themeId: "en-e-asian-cities",
    label: "Asian Cities",
    difficultyTier: "E",
    wordsByLength: {
      4: ["DOHA","XIAN"],
      5: ["DELHI","DHAKA","DUBAI","HANOI","KABUL","KYOTO","MACAU","MOSUL","OSAKA","SANAA","SEOUL","SURAT","TOKYO","WUHAN"],
      6: ["ALEPPO","ANKARA","BEIRUT","BOMBAY","JAIPUR","JEDDAH","LAHORE","MADRAS","MANILA","MOSCOW","RIYADH","TAIPEI","TEHRAN"],
      7: ["BAGHDAD","BANGKOK","BEIJING","BISHKEK","JAKARTA","KARACHI","MASHHAD","RANGOON","TIANJIN"],
    },
    wordLengthComposition: [{"length":5,"count":3},{"length":6,"count":2},{"length":7,"count":1}],
    allowFreeDirections: true,
  },
  {
    themeId: "en-e-european-cities",
    label: "European Cities",
    difficultyTier: "E",
    wordsByLength: {
      4: ["BERN","BONN","HAMM","LYON","NICE","OSLO","RIGA","ROME","VIGO","YORK"],
      5: ["BRAGA","BREDA","BREST","DIJON","ESPOO","ESSEN","GENOA","LAHTI","LEEDS","LIEGE","LILLE","MILAN","NAMUR","PADUA","PARIS","PORTO","REIMS","SOFIA","TURIN","VARNA"],
      6: ["ANGERS","ATHENS","BERLIN","BOLTON","BREMEN","BRUGES","CANNES","DUBLIN","DUDLEY","FOGGIA","KAUNAS","KRAKOW","LISBON","LONDON","MADRID","MALAGA","MUNICH","NAPOLI","ODESSA","PRAGUE","RENNES","RIJEKA","SLOUGH","TORINO","TOULON","VENICE","VERONA","VIENNA","WARSAW","ZURICH"],
      7: ["BELFAST","BOLOGNA","BRESCIA","BRISTOL","CARDIFF","CATANIA","COLOGNE","CORDOBA","CRAIOVA","DRESDEN","GLASGOW","GRANADA","HAARLEM","HAMBURG","HANOVER","LEIPZIG","NEWPORT","NICOSIA","PALERMO","RAVENNA","ROSTOCK","SALERNO","SEVILLE","TALLINN","TAMPERE","VILNIUS"],
    },
  },
  {
    themeId: "en-e-north-american-cities",
    label: "North-American Cities",
    difficultyTier: "E",
    wordsByLength: {
      4: [],
      5: ["MIAMI"],
      6: ["AUSTIN","BOSTON","CANCUN","DALLAS","DENVER","HAVANA","MERIDA","MEXICO","NASSAU","OTTAWA","PUEBLA","QUEBEC","TOLUCA"],
      7: ["ATLANTA","CALGARY","CHICAGO","DETROIT","HOUSTON","MANAGUA","MEMPHIS","ORLANDO","PHOENIX","SEATTLE","TIJUANA","TORONTO","ZAPOPAN"],
    },
    wordLengthComposition: [{"length":5,"count":1},{"length":6,"count":3},{"length":7,"count":2}],
    allowFreeDirections: true,
  },
  {
    themeId: "en-e-south-american-cities",
    label: "South-American Cities",
    difficultyTier: "E",
    wordsByLength: {
      4: ["CALI","LIMA"],
      5: ["BELEM","CUSCO","NATAL","QUITO","SUCRE"],
      6: ["BOGOTA","MANAUS","RECIFE","SANTOS"],
      7: ["CARACAS","CORDOBA","MARACAY","MENDOZA","ROSARIO"],
    },
    wordLengthComposition: [{"length":5,"count":3},{"length":6,"count":2},{"length":7,"count":1}],
    allowFreeDirections: true,
  },
  {
    themeId: "en-e-world-cities",
    label: "World Cities",
    difficultyTier: "E",
    wordsByLength: {
      4: ["BERN","BONN","DOHA","KIEV","LIMA","LOME","LYON","NICE","OMSK","OSLO","PISA","RIGA","ROME","YORK"],
      5: ["ACCRA","AMMAN","CAIRO","DAKAR","DELHI","DHAKA","DUBAI","HANOI","KABUL","KYOTO","LAGOS","LIEGE","LUXOR","MECCA","MIAMI","MINSK","OSAKA","PARIS","QUITO","RABAT","REIMS","SANAA","SEOUL","SOFIA","TOKYO","TUNIS","TURIN","VARNA"],
      6: ["ALEPPO","ANKARA","ASMARA","ASTANA","ATHENS","AUSTIN","BAMAKO","BANGUI","BEIRUT","BERLIN","BILBAO","BISSAU","BOGOTA","BOSTON","CANCUN","CANNES","DALLAS","DENVER","DUBLIN","GENOVA","HARARE","HAVANA","KIGALI","LISBON","LONDON","LUANDA","MADRID","MANAMA","MANILA","MAPUTO","MASERU","MILANO","MONACO","MOSCOW","MUMBAI","MUNICH","NAPOLI","NASSAU","NIAMEY","OTTAWA","OXFORD","PRAGUE","QUEBEC","RHODES","RIYADH","SYDNEY","TAIPEI","TEHRAN","VENICE","VERONA","VIENNA","WARSAW","ZAGREB","ZURICH"],
      7: ["ABIDJAN","ALGIERS","ATLANTA","BAGHDAD","BANGKOK","BEIJING","BISHKEK","BRISTOL","CARACAS","CARDIFF","CAYENNE","CHESTER","CHICAGO","CONAKRY","DETROIT","DRESDEN","GLASGOW","GRANADA","HAMBURG","HOUSTON","JAKARTA","KAMPALA","KOLKATA","LARNACA","MANAGUA","MEMPHIS","MYKONOS","NAIROBI","NICOSIA","ORLANDO","PAPEETE","SEATTLE","SEVILLE","TALLINN","TORONTO","TRIPOLI","VILNIUS","YAOUNDE","YEREVAN"],
    },
  },
  {
    themeId: "en-e-world-capitals",
    label: "World Capitals",
    difficultyTier: "E",
    wordsByLength: {
      4: ["APIA","BAKU","BERN","DILI","DOHA","KIEV","LIMA","LOME","OSLO","RIGA","ROME","SUVA"],
      5: ["ABUJA","ACCRA","ALOFI","AMMAN","CAIRO","DAKAR","DHAKA","HANOI","KABUL","MINSK","PARIS","PRAIA","QUITO","RABAT","SANAA","SEOUL","SOFIA","SUCRE","TOKYO","TUNIS"],
      6: ["ANKARA","ASMARA","ASTANA","ATHENS","AVARUA","BAMAKO","BANGUI","BEIRUT","BERLIN","BISSAU","BOGOTA","DUBLIN","HARARE","HAVANA","KIGALI","LISBON","LONDON","LUANDA","LUSAKA","MADRID","MANAMA","MANILA","MAPUTO","MASERU","MONACO","MOSCOW","MUSCAT","NASSAU","NIAMEY","OTTAWA","PRAGUE","RIYADH","SKOPJE","TEHRAN","TIRANA","VIENNA","WARSAW","ZAGREB"],
      7: ["ALGIERS","BAGHDAD","BANGKOK","BEIJING","BISHKEK","CARACAS","CAYENNE","CONAKRY","JAKARTA","KAMPALA","MANAGUA","NAIROBI","NICOSIA","PAPEETE","TALLINN","TRIPOLI","VILNIUS","YAOUNDE","YEREVAN"],
    },
  },
  {
    themeId: "en-e-god-goddesses",
    label: "God & Goddesses",
    difficultyTier: "E",
    wordsByLength: {
      4: ["ARES","HERA","JUNO","LOKI","MARS","ODIN","RAMA","THOR","ZEUS"],
      5: ["CERES","CIRCE","DIANA","FREYA","HADES","JANUS","SHIVA","VENUS","VESTA"],
      6: ["APOLLO","ATHENA","HERMES","HESTIA","ISHTAR","OSIRIS","SATURN","VISHNU","VULCAN"],
      7: ["ARTEMIS","DEMETER","JUPITER","KRISHNA","MERCURY","MINERVA","NEPTUNE"],
    },
  },
  {
    themeId: "en-e-famous-bands",
    label: "Famous Bands",
    difficultyTier: "E",
    wordsByLength: {
      4: ["BLUR","KISS","MUSE"],
      5: ["OASIS","QUEEN","WILCO"],
      6: ["EAGLES","PIXIES","WEEZER"],
      7: ["BAUHAUS","GARBAGE","GENESIS","MISFITS","NIRVANA","PANTERA","PLACEBO","RAINBOW","RAMONES","ROXETTE","SEETHER"],
    },
  },
  {
    themeId: "en-e-car-manufacturers",
    label: "Car Manufacturers",
    difficultyTier: "E",
    wordsByLength: {
      4: ["AUDI","FIAT","FORD","JEEP","OPEL","SAAB","SEAT"],
      5: ["BUICK","DACIA","DODGE","HONDA","ISUZU","LEXUS","LOTUS","MAZDA","SKODA","SMART","TESLA","VOLVO"],
      6: ["AUSTIN","HUMMER","JAGUAR","LANCIA","NISSAN","SUBARU","SUZUKI","TOYOTA"],
      7: ["BENTLEY","BUGATTI","CITROEN","FERRARI","HYUNDAI","MCLAREN","PEUGEOT","PONTIAC","PORSCHE","RENAULT"],
    },
  },
];
