/** Known avatar ids, matching the PNG filenames shared in the design library (no extension). */
export const AVATAR_IDS = [
  'Alonzo',
  'Angela',
  'Angelo',
  'Annabel',
  'Belle',
  'Blake',
  'Bob',
  'Bozo',
  'Chester',
  'Dracul',
  'Emma',
  'Fabio',
  'Fred',
  'George',
  'Gordon',
  'Gustave',
  'Hannah',
  'Henry',
  'Hulda',
  'Ike',
  'Imhotep',
  'Jasper',
  'Jesse',
  'Kirk',
  'Linda',
  'Lisa',
  'Luke',
  'Marcos',
  'Martin',
  'Matt',
  'Maximillian',
  'Mindy',
  'Pam',
  'Raj',
  'Ranjit',
  'Raymond',
  'Robert',
  'Rose',
  'Roy',
  'Rupert',
  'Sheila',
  'Shroom',
  'Spott-avatars',
  'Terry',
  'Victor',
  'Zorro',
] as const;

export type AvatarId = (typeof AVATAR_IDS)[number];

export function isValidAvatarId(value: string): value is AvatarId {
  return (AVATAR_IDS as readonly string[]).includes(value);
}
