import type { SampleThemeWords } from '../types.js';

/**
 * Generated from docs/design/word-lists — do not hand-edit.
 * Regenerate with `node scripts/generate-word-lists.mjs` after the source
 * JSON files change (rebuild the engine first: `npm run build`).
 */
export const FRENCH_WORD_LIST_THEMES: readonly SampleThemeWords[] = [
  {
    themeId: "fr-a-anatomie",
    label: "Anatomie",
    difficultyTier: "A",
    wordsByLength: {
      4: ["DENT","FOIE","IRIS","MAIN","NERF","PEAU","PIED","REIN","SANG","SEIN"],
      5: ["COEUR","AORTE","COUDE","DOIGT","FEMUR","ONGLE","TIBIA","VEINE"],
      6: ["ARTERE","BASSIN","BOUCHE","CHEVEU","CUISSE","GLANDE","LANGUE","LARYNX","MUSCLE","OVAIRE","POUMON","RADIUS","RETINE","ROTULE","THORAX","TYMPAN","VESSIE"],
      7: ["ABDOMEN","CERVEAU","ESTOMAC","HUMERUS","PHARYNX","STERNUM","TRACHEE"],
    },
  },
  {
    themeId: "fr-a-animaux",
    label: "Animaux",
    difficultyTier: "A",
    wordsByLength: {
      4: ["BUSE","CERF","ELAN","GRUE","IBIS","KIWI","LAMA","LION","LOUP","LYNX","MITE","MULE","PAON","PUCE","PUMA","THON","ZEBU"],
      5: ["AIGLE","CRABE","CYGNE","DINDE","DINGO","GUEPE","HERON","HYENE","KOALA","LAPIN","MORSE","MOULE","ORQUE","PANDA","PONEY","SINGE","TAPIR","TAUPE","TIGRE","TIQUE","ZEBRE"],
      6: ["AGNEAU","BAUDET","CAILLE","CALMAR","CANARD","CHACAL","CHEVAL","CHEVRE","CONDOR","COUCOU","EPONGE","FAUCON","FRELON","GIRAFE","HOMARD","HUITRE","IGUANE","JAGUAR","JUMENT","LEZARD","LIMACE","MOUTON","PHOQUE","PIGEON","REQUIN","SAUMON","SOURIS","TORTUE","TOUCAN","TRUITE","VIPERE"],
      7: ["BALEINE","BELETTE","CIGOGNE","COLOMBE","CORBEAU","CRAPAUD","CRIQUET","DAUPHIN","GAZELLE","GORILLE","GRIZZLY","HAMSTER","HERMINE","LEOPARD","LUCIOLE","MANCHOT","MOINEAU","MOUETTE","MUSTANG","OPOSSUM","PELICAN","PHALENE","PIRANHA","PITBULL","SARDINE","SERPENT","TERMITE","VAUTOUR"],
    },
  },
  {
    themeId: "fr-a-botanique",
    label: "Botanique",
    difficultyTier: "A",
    wordsByLength: {
      4: ["ARUM","AUNE","MAIS","ORGE","ROSE","THYM","TIGE"],
      5: ["ANETH","BULBE","CEDRE","CHENE","EPINE","FLEUR","FRUIT","GENET","HETRE","LILAS","NOYER","PAVOT","SAPIN","SAUGE","SAULE"],
      6: ["ACACIA","AVOINE","AZALEE","BAOBAB","CYPRES","EPICEA","ERABLE","JASMIN","MELEZE","MENTHE","MIMOSA","NECTAR","PERSIL","PETALE","PISTIL","POIVRE","POLLEN","QUINOA","RACINE","RESINE","SEIGLE","TULIPE"],
      7: ["BASILIC","BOULEAU","BRANCHE","CAMELIA","CHARDON","COROLLE","FEUILLE","GIROFLE","LAURIER","PALMIER","PIVOINE","POIRIER"],
    },
  },
  {
    themeId: "fr-a-constructions-humaines",
    label: "Constructions Humaines",
    difficultyTier: "A",
    wordsByLength: {
      4: ["ABRI","FORT","PONT","PORT","SILO","TOUR"],
      5: ["ARENE","ASILE","DIGUE","ECOLE","FERME","FORUM","HOTEL","IGLOO","MOTEL","MUSEE","RANCH","STADE","USINE","VILLA"],
      6: ["ABBAYE","BANQUE","BUNKER","CAMPUS","CINEMA","DUPLEX","EGLISE","ETABLE","FAVELA","GARAGE","GRANGE","HANGAR","MAISON","MARINA","MOULIN","PAGODE","PALAIS","PRISON","TEMPLE","TUNNEL"],
      7: ["CHATEAU","COLLEGE","MOSQUEE","THEATRE","TOMBEAU"],
    },
  },
  {
    themeId: "fr-a-instruments-de-musique",
    label: "Instruments de musique",
    difficultyTier: "A",
    wordsByLength: {
      4: ["ALTO","GONG","LUTH","LYRE","TUBA"],
      5: ["BANJO","BASSE","FLUTE","HARPE","KAZOO","ORGUE","PIANO","SITAR"],
      6: ["BASSON","DJEMBE","VIOLON"],
      7: ["GUITARE","MARIMBA","OCARINA","TAMBOUR","UKULELE"],
    },
  },
  {
    themeId: "fr-a-la-planete-terre",
    label: "La Planète Terre",
    difficultyTier: "A",
    wordsByLength: {
      4: ["AUBE","COTE","DUNE","LAVE","NUIT","VENT"],
      5: ["ATOLL","BRISE","BUTTE","CANAL","CRETE","DELTA","ETANG","FJORD","FLORE","FORET","GOLFE","HERBE","HIVER","LAGON","MAGMA","MAREE","NUAGE","OASIS","OCEAN","OZONE","PLAGE","PLUIE","RAVIN","RECIF","SABLE","SILEX","VAGUE"],
      6: ["AURORE","BRUINE","CANYON","CHUTES","CORAIL","CRIQUE","DESERT","FLAQUE","GADOUE","GEYSER","GRANIT","GROTTE","JUNGLE","MARAIS","PLAINE","RIVAGE","ROCHER","SAISON","SAVANE","SOMMET","SOURCE","STEPPE","TYPHON","VALLEE","VALLON","VAPEUR","VOLCAN"],
      7: ["AUTOMNE","BASALTE","BOSQUET","CAILLOU","CAVERNE","CHALEUR","COLLINE","COURANT","CRATERE","CYCLONE","ECLIPSE","FALAISE","FOSSILE","GLACIER","ICEBERG","RAPIDES","RIVIERE","TEMPETE","TORNADE","TORRENT","TOUNDRA","TSUNAMI","VERGLAS"],
    },
  },
  {
    themeId: "fr-a-nourriture-vegetalienne",
    label: "Nourriture Végétalienne",
    difficultyTier: "A",
    wordsByLength: {
      4: ["ANIS","CHOU","GUAR","LIME","NOIX"],
      5: ["AIOLI","CAJOU","CARVI","CUMIN","MELON","NAVET","NEFLE","OLIVE","PECAN","PECHE","POIRE","POMME","PRUNE","RADIS","SUMAC"],
      6: ["AMANDE","AVOCAT","BANANE","CELERI","CERISE","CITRON","ENDIVE","GOYAVE","JUJUBE","LAITUE","LITCHI","MANGUE","MANIOC","OIGNON","ORANGE","ORIGAN","PANAIS","PAPAYE","POMELO","RAISIN","SAFRAN","TOMATE","TRUFFE","WASABI"],
      7: ["ABRICOT","CAROTTE","CHUTNEY","CRESSON","EPINARD","FENOUIL","KETCHUP","KUMQUAT","PAPRIKA","POIREAU","VANILLE"],
    },
  },
  {
    themeId: "fr-a-sports",
    label: "Sports",
    difficultyTier: "A",
    wordsByLength: {
      4: ["AXEL","BOXE","CLUB","GOLF","JUDO","LUGE","POLO","SAUT"],
      5: ["BALLE","CATCH","PALET","POIDS","RUGBY","SKATE"],
      6: ["ARCEAU","AVIRON","COURSE","EQUIPE","HOCKEY","JOUEUR","KARATE","RELAIS","SLALOM","SQUASH","STRIKE","TENNIS","VOLLEY"],
      7: ["BOWLING","CERCEAU","COUREUR","CRICKET","CROQUET","CURLING","ESCRIME","JOGGING","LANCEUR","MAILLET","PLONGEE","RAFTING"],
    },
  },
  {
    themeId: "fr-a-transports",
    label: "Transports",
    difficultyTier: "A",
    wordsByLength: {
      4: ["AUTO","JEEP","MOTO","TAXI","VELO"],
      5: ["BARGE","CANOE","FERRY","METRO","TRAIN","WAGON","YACHT"],
      6: ["BALLON","BATEAU","CAMION","GALERE","NAVIRE"],
      7: ["CHARIOT","FREGATE","GONDOLE","MINIBUS","PLANEUR","SCOOTER"],
    },
  },
  {
    themeId: "fr-a-vetements-et-accessoires",
    label: "Vêtements et Accessoires",
    difficultyTier: "A",
    wordsByLength: {
      4: ["CAPE","GANT","JEAN","JUPE","KEPI","KILT","PULL","ROBE","SARI","SLIP","TOGE","TUTU"],
      5: ["BERET","BOTTE","BOXER","BURQA","CHALE","GAINE","GILET","HABIT","KIPPA","NIQAB","PARKA","POCHE","SHORT","SWEAT","TENUE","VOILE"],
      6: ["ANORAK","BIKINI","BLAZER","BLOUSE","BONNET","BOUCLE","BOUTON","CAFTAN","CASQUE","CORSET","FEUTRE","JERSEY","KIMONO","MANCHE","MASQUE","PONCHO","PYJAMA","SARONG","TURBAN"],
      7: ["CHEMISE","COLLIER","COSTUME","CRAVATE","ECHARPE","FOULARD","MAILLOT","MANTEAU","POLAIRE","SANDALE","SMOKING","TABLIER","TUNIQUE"],
    },
  },
  {
    themeId: "fr-b-a-l-ecole",
    label: "A l'Ecole",
    difficultyTier: "B",
    wordsByLength: {
      4: ["MATH","PROF","TEST"],
      5: ["ATLAS","COLLE","CRAIE","ELEVE","GLOBE","GOMME","LECON","LIVRE","RECRE"],
      6: ["CLASSE","COMPAS","CRAYON","EXAMEN","PAPIER","PROJET"],
      7: ["ALGEBRE","DOSSIER","REPONSE","SCIENCE","TABLEAU"],
    },
  },
  {
    themeId: "fr-b-a-la-ferme",
    label: "A la ferme",
    difficultyTier: "B",
    wordsByLength: {
      4: ["LAIT","SEAU","VEAU"],
      5: ["BECHE","PELLE","POULE","VACHE"],
      6: ["FUMIER","GRAINS","POULET","RATEAU"],
      7: ["CLOTURE","FERMIER","FOURCHE","POULAIN","POUSSIN","RECOLTE"],
    },
  },
  {
    themeId: "fr-b-a-table",
    label: "A table!",
    difficultyTier: "B",
    wordsByLength: {
      4: ["PAIN","PLAT","VASE"],
      5: ["COUPE","NAPPE","REPAS","TASSE","VERRE"],
      6: ["CARAFE","LOUCHE","PANIER","PICHET"],
      7: ["COUTEAU","SPATULE"],
    },
  },
  {
    themeId: "fr-b-argent-et-affaires",
    label: "Argent et Affaires",
    difficultyTier: "B",
    wordsByLength: {
      4: ["BRUT","EURO","GAIN","PRET","PRIX","TAUX"],
      5: ["DEBIT","DEPOT","DETTE","FONDS","FRAIS","FRANC","MARGE","OFFRE","PERTE","RICHE","TARIF","VENTE"],
      6: ["BUDGET","CHEQUE","CREDIT","EXPORT","IMPORT","PAUVRE","REVENU","VALEUR"],
      7: ["BALANCE","CAPITAL","CENTIME","DEFICIT","DEPENSE","ECONOME","ESPECES","FACTURE","MONNAIE","RESERVE"],
    },
  },
  {
    themeId: "fr-b-boissons",
    label: "Boissons",
    difficultyTier: "B",
    wordsByLength: {
      4: ["ARAK","CAFE","COLA","MATE","RAKI","SAKE","SODA"],
      5: ["BIERE","CIDRE","PORTO","VODKA"],
      6: ["BRANDY","COGNAC","GRAPPA","KIRSCH","TISANE","WHISKY"],
      7: ["BOURBON","CACHACA","LIQUEUR","SANGRIA","TEQUILA"],
    },
  },
  {
    themeId: "fr-b-bricolage",
    label: "Bricolage",
    difficultyTier: "B",
    wordsByLength: {
      4: ["CLOU","RAPE","SCIE"],
      5: ["PINCE","REGLE","RIVET"],
      6: ["CISEAU"],
      7: ["ABRASIF","MARTEAU"],
    },
  },
  {
    themeId: "fr-b-chefs-et-leaders",
    label: "Chefs et Leaders",
    difficultyTier: "B",
    wordsByLength: {
      4: ["KHAN","PAPE","SHAH","TSAR"],
      5: ["CHEIK","VIZIR"],
      6: ["CALIFE","GOUROU","INFANT","REGENT","SHOGUN","SULTAN"],
      7: ["INFANTE","PHARAON","TSARINE"],
    },
  },
  {
    themeId: "fr-b-chez-le-bijoutier",
    label: "Chez le Bijoutier",
    difficultyTier: "B",
    wordsByLength: {
      4: ["JADE","ONYX"],
      5: ["AGATE","AMBRE","BERYL","JASPE","OPALE","PERLE","RUBIS","TIARE"],
      6: ["ANNEAU","BROCHE","CHAINE","GRENAT","QUARTZ","TOPAZE","ZIRCON"],
      7: ["APATITE","AZURITE","CITRINE","CRISTAL","DIADEME","DIAMANT"],
    },
  },
  {
    themeId: "fr-b-cirques-et-forains",
    label: "Cirques et Forains",
    difficultyTier: "B",
    wordsByLength: {
      4: ["CAGE","OURS"],
      5: ["CLOWN","FOUET","MAGIE","STAND","TENTE"],
      6: ["BILLET","PARADE","TROUPE"],
      7: ["ECUYERE","TRAPEZE"],
    },
  },
  {
    themeId: "fr-b-contes-de-fees",
    label: "Contes de Fées",
    difficultyTier: "B",
    wordsByLength: {
      4: ["EPEE","NAIN","OGRE","SORT","VOEU"],
      5: ["GNOME","HEROS","LUTIN","TROLL"],
      6: ["DRAGON","SIRENE"],
      7: ["FANTOME","LICORNE"],
    },
  },
  {
    themeId: "fr-b-danses",
    label: "Danses",
    difficultyTier: "B",
    wordsByLength: {
      4: ["ACRO","HULA"],
      5: ["CONGA","DISCO","LIMBO","MAMBO","POLKA","RUMBA","SALSA","SAMBA","SWING","TANGO","TWIST","VALSE"],
      6: ["BALLET","BOLERO","DABKEH","MENUET"],
      7: ["BACHATA","BIGUINE","LAMBADA","MAZURKA","SIRTAKI"],
    },
  },
  {
    themeId: "fr-b-feodalite",
    label: "Féodalité",
    difficultyTier: "B",
    wordsByLength: {
      4: ["COUR","DAME","DIME","PAGE","SERF"],
      5: ["BARON","COMTE","DUCHE","REGNE"],
      6: ["DONJON","ECUYER","ONAGRE"],
      7: ["DOMAINE","MARQUIS","ROYAUME","SCEPTRE"],
    },
  },
  {
    themeId: "fr-b-jeux-et-equipement-de-jeu",
    label: "Jeux et Equipement de jeu",
    difficultyTier: "B",
    wordsByLength: {
      4: ["PION","RAMI"],
      5: ["CARTE","DAMES","ECRAN","JETON","POKER"],
      6: ["BRIDGE","DOMINO","ECHECS","MIKADO","PAQUET"],
      7: ["SABLIER"],
    },
  },
  {
    themeId: "fr-b-la-famille",
    label: "La Famille",
    difficultyTier: "B",
    wordsByLength: {
      4: ["BEBE","FILS","MARI","MERE","PERE"],
      5: ["EPOUX","FEMME","FILLE","FRERE","NEVEU","NIECE","ONCLE","SOEUR","TANTE"],
      6: ["COUSIN","ENFANT","EPOUSE","GENDRE"],
      7: ["COUSINE"],
    },
  },
  {
    themeId: "fr-b-mathematiques",
    label: "Mathématiques",
    difficultyTier: "B",
    wordsByLength: {
      4: ["CUBE","PLUS"],
      5: ["ANGLE","CARRE","MOINS","TOTAL"],
      6: ["CERCLE","COURBE","NOMBRE","PRISME","RADIAN","VOLUME"],
      7: ["BINAIRE","CHIFFRE","CONCAVE","CONVEXE","DECIMAL","DIVISER","FORMULE","MEDIANE","MOYENNE","OBLIQUE","RAPPORT","SEGMENT","VECTEUR"],
    },
  },
  {
    themeId: "fr-b-musique",
    label: "Musique",
    difficultyTier: "B",
    wordsByLength: {
      4: ["CLEF","NOTE","SOLO","TRIO"],
      5: ["CANON","HYMNE","OPERA","TEMPO","TENOR","THEME"],
      6: ["ACCORD","ADAGIO","ATONAL","AUBADE","CHOEUR","GROUPE","OCTAVE","RYTHME","TIMBRE"],
      7: ["BALLADE","CADENCE","CANTATE","CHANSON","CONCERT","MELODIE","QUATUOR","SOLFEGE","SOPRANO","UNISSON"],
    },
  },
  {
    themeId: "fr-b-ordinateurs-et-internet",
    label: "Ordinateurs et Internet",
    difficultyTier: "B",
    wordsByLength: {
      4: ["BLOG","LIEN","SCAN","SPAM","UNDO"],
      5: ["DEBUG","EMAIL","ICONE","MODEM","OCTET","VIRUS"],
      6: ["COOKIE","FORMAT","HACKER","RESEAU"],
      7: ["CLAVIER","PORTAIL"],
    },
  },
  {
    themeId: "fr-b-pieces-de-voiture",
    label: "Pièces de voiture",
    difficultyTier: "B",
    wordsByLength: {
      4: ["PNEU","ROUE"],
      5: ["CAPOT","FREIN","JANTE","JAUGE","PORTE"],
      6: ["AIRBAG","ALARME","ESSIEU","FILTRE","MOTEUR","PEDALE","PISTON"],
      7: ["CHASSIS","CONSOLE","FENETRE","FUSIBLE","SERRURE"],
    },
  },
  {
    themeId: "fr-b-sante-medecine",
    label: "Santé - Médecine",
    difficultyTier: "B",
    wordsByLength: {
      4: ["ACNE","CURE","RAGE","SIDA","TOUX"],
      5: ["GERME","KYSTE","OTITE","PLAIE","RHUME"],
      6: ["ANEMIE","ASTHME","CANCER","CRAMPE","ECZEMA","FIEVRE","PILULE","POISON","REGIME","SPASME","TOXINE","VERRUE"],
      7: ["AMNESIE","AMPOULE","ANXIETE","BANDAGE","BIOPSIE","CALORIE","DOULEUR","ENTORSE","ESCARRE","HYGIENE","MALADIE","OBESITE","PATIENT","TENSION"],
    },
  },
  {
    themeId: "fr-b-sources-de-lumiere",
    label: "Sources de lumière",
    difficultyTier: "B",
    wordsByLength: {
      4: ["LUNE","NEON","SPOT"],
      5: ["FLASH","LAMPE","LASER"],
      6: ["BALISE","BOUGIE","COMETE","ECLAIR","ETOILE","FLAMME","SOLEIL","TORCHE"],
      7: ["BRIQUET","METEORE"],
    },
  },
  {
    themeId: "fr-b-styles-musicaux",
    label: "Styles musicaux",
    difficultyTier: "B",
    wordsByLength: {
      4: ["ACID","FOLK","FUNK","JAZZ","PUNK","ROCK","SOCA","SOUL","ZOUK"],
      5: ["BLUES","HOUSE","METAL"],
      6: ["GOSPEL","GRUNGE","MOTOWN","REGGAE","TECHNO","TRANSE"],
      7: ["BAROQUE","BRITPOP","CALYPSO","COUNTRY","DUBSTEP","RAGTIME"],
    },
  },
  {
    themeId: "fr-c-a-l-armee-et-a-la-guerre",
    label: "A l'Armée et à la guerre",
    difficultyTier: "C",
    wordsByLength: {
      4: ["ARME","BASE","CAMP","MINE"],
      5: ["BOMBE","CIBLE","FUSIL","MAJOR","SIEGE","TREVE","UNITE"],
      6: ["AMIRAL","ARMURE","COMBAT","ENNEMI","FLOTTE","MARINE","RECRUE"],
      7: ["ARSENAL","ATTAQUE","COLONEL","DEFAITE","DEFENSE","GENERAL","GRENADE","MISSILE","MORTIER","SECTION","TROUPES","VETERAN"],
    },
  },
  {
    themeId: "fr-c-aeroports-et-avions",
    label: "Aéroports et avions",
    difficultyTier: "C",
    wordsByLength: {
      4: ["AILE","VISA"],
      5: ["PISTE","QUEUE"],
      6: ["CABINE","DOUANE","HUBLOT"],
      7: ["AILERON","COCKPIT","HORIZON","HOTESSE","TURBINE"],
    },
  },
  {
    themeId: "fr-c-anatomie-animale",
    label: "Anatomie animale",
    difficultyTier: "C",
    wordsByLength: {
      4: ["BRAS","CROC","DARD","POIL"],
      5: ["BOSSE","COQUE","CORNE","PALME","PATTE","PLUME","SABOT","TRONC"],
      6: ["GRIFFE","MUSEAU"],
      7: ["ANTENNE","ECAILLE"],
    },
  },
  {
    themeId: "fr-c-anatomie-de-la-tete",
    label: "Anatomie de la tête",
    difficultyTier: "C",
    wordsByLength: {
      4: ["JOUE","OEIL"],
      5: ["CRANE","LEVRE"],
      6: ["CANINE","CORNEE","MENTON","NARINE"],
      7: ["MOLAIRE","OREILLE","SOURCIL"],
    },
  },
  {
    themeId: "fr-c-bebes-terriens",
    label: "Bébés Terriens",
    difficultyTier: "C",
    wordsByLength: {
      4: ["FAON","PUPE"],
      5: ["CHIOT","LARVE","OISON"],
      6: ["AIGLON","CHATON","CYGNON","OURSON","TETARD"],
      7: ["ASTICOT"],
    },
  },
  {
    themeId: "fr-c-communication",
    label: "Communication",
    difficultyTier: "C",
    wordsByLength: {
      4: ["BAUD","CODE","ONDE"],
      5: ["APPEL","HERTZ","MEDIA","POSTE","RADIO"],
      6: ["CACHET","LETTRE","MOBILE","SIGNAL"],
      7: ["ADRESSE","MESSAGE","POSTIER"],
    },
  },
  {
    themeId: "fr-c-elements-chimiques",
    label: "Elements chimiques",
    difficultyTier: "C",
    wordsByLength: {
      4: ["BORE","IODE","ZINC"],
      5: ["ARGON","BROME","PLOMB","RADON","XENON"],
      6: ["BARYUM","CERIUM","COBALT","CURIUM","ERBIUM","HELIUM","INDIUM","NICKEL","RADIUM","SODIUM","SOUFRE"],
      7: ["ARSENIC","BISMUTH","BOHRIUM","CADMIUM","CALCIUM","CARBONE","DUBNIUM","IRIDIUM","KRYPTON","LITHIUM","MERCURE","OXYGENE","THORIUM","URANIUM"],
    },
  },
  {
    themeId: "fr-c-geometrie",
    label: "Géométrie",
    difficultyTier: "C",
    wordsByLength: {
      4: ["CONE","PLAN","ROND","TORE"],
      5: ["ARETE","FORME","OVALE","POINT","RAYON","SINUS"],
      6: ["CENTRE","DISQUE","HELICE"],
      7: ["CUBOIDE","ELLIPSE","LOSANGE","SECTEUR"],
    },
  },
  {
    themeId: "fr-c-l-espace",
    label: "L'Espace",
    difficultyTier: "C",
    wordsByLength: {
      4: ["MARS","NOVA","VIDE"],
      5: ["FUSEE","TERRE","VENUS"],
      6: ["COSMOS","ORBITE","PLUTON","URANUS"],
      7: ["GALAXIE","JUPITER","NAVETTE","NEPTUNE","PLANETE","SATURNE"],
    },
  },
  {
    themeId: "fr-c-le-calendrier",
    label: "Le Calendrier",
    difficultyTier: "C",
    wordsByLength: {
      4: ["AOUT","JUIN"],
      5: ["AVRIL","JEUDI","LUNDI","MARDI"],
      6: ["BELIER","SAMEDI","VIERGE"],
      7: ["FEVRIER","GEMEAUX","JANVIER","JUILLET","OCTOBRE","TAUREAU"],
    },
  },
  {
    themeId: "fr-c-le-temps",
    label: "Le Temps",
    difficultyTier: "C",
    wordsByLength: {
      4: ["JOUR","MIDI","MOIS","ZONE"],
      5: ["ANNEE","APRES","AVANT","HEURE","MATIN"],
      6: ["AVENIR","EPOQUE","MINUTE","MOMENT","RETARD","SIECLE","TARDIF"],
      7: ["BIENTOT","PERIODE","PRESENT","SEMAINE"],
    },
  },
  {
    themeId: "fr-c-mythes-legendes",
    label: "Mythes & Légendes",
    difficultyTier: "C",
    wordsByLength: {
      4: ["ANGE","ELFE","YETI"],
      5: ["DEMON","DJINN","GENIE","GOLEM","HYDRE"],
      6: ["DRYADE","HARPIE","INCUBE","NAIADE","NYMPHE","PEGASE","PHENIX","SATYRE","SPHINX","SYLPHE","ZOMBIE"],
      7: ["CHIMERE","CYCLOPE","DIBBOUK","GOBELIN","GORGONE","GREMLIN","VAMPIRE","VOUIVRE"],
    },
  },
  {
    themeId: "fr-c-sur-un-plateau-de-tournage",
    label: "Sur un plateau de tournage",
    difficultyTier: "C",
    wordsByLength: {
      4: ["ROLE","ZOOM"],
      5: ["PIXEL","SCENE"],
      6: ["BOBINE","CAMERA","FOCALE","PERCHE","RUSHES"],
      7: ["CASCADE","MONTAGE"],
    },
  },
  {
    themeId: "fr-c-textiles",
    label: "Textiles",
    difficultyTier: "C",
    wordsByLength: {
      4: ["CUIR","SOIE"],
      5: ["COTON","DENIM","LAINE","LYCRA","NYLON"],
      6: ["MOHAIR"],
      7: ["VELOURS"],
    },
  },
  {
    themeId: "fr-c-tribunal-code-civil",
    label: "Tribunal & Code Civil",
    difficultyTier: "C",
    wordsByLength: {
      4: ["AVEU","BAIL","JURY","LEGS","TORT"],
      5: ["CRIME","DELIT"],
      6: ["DECRET","FRAUDE","PROCES","TEMOIN"],
      7: ["JUSTICE","PARJURE","PLAINTE","VERDICT"],
    },
  },
  {
    themeId: "fr-d-capitales-du-monde",
    label: "Capitales du monde",
    difficultyTier: "D",
    wordsByLength: {
      4: ["APIA","DILI","DOHA","KIEV","LIMA","LOME","MALE","OSLO","RIGA","ROME","SUVA"],
      5: ["ABUJA","ACCRA","ALGER","AMMAN","BAKOU","BERNE","DACCA","DAKAR","DAMAS","HANOI","MINSK","PARIS","PEKIN","PRAIA","QUITO","RABAT","RIYAD","SANAA","SEOUL","SOFIA","TOKYO","TUNIS","VADUZ","YAREN"],
      6: ["ANKARA","ASMARA","ASTANA","BAGDAD","BAMAKO","BANGUI","BANJUL","BERLIN","BISSAU","BOGOTA","DODOMA","DUBLIN","EREVAN","HARARE","KABOUL","KIGALI","KOWEIT","LUANDA","LUSAKA","MADRID","MALABO","MANAMA","MAPUTO","MASERU","MEXICO","MONACO","MORONI","MOSCOU","NASSAU","NIAMEY","OTTAWA","PANAMA","PRAGUE","ROSEAU","SKOPJE","TIRANA","VIENNE","ZAGREB"],
      7: ["ATHENES","BANGKOK","BICHKEK","CARACAS","CONAKRY","HAGATNA","HONIARA","JAKARTA","KAMPALA","LONDRES","MANAGUA","MANILLE","MASCATE","MBABANE","NAIROBI","NICOSIE","PALIKIR","TALLINN","TEHERAN","TRIPOLI","VATICAN","VILNIUS","YAOUNDE"],
    },
  },
  {
    themeId: "fr-d-lacs-fleuves",
    label: "Lacs & Fleuves",
    difficultyTier: "D",
    wordsByLength: {
      4: ["ELBE","EYRE","RHIN","TAGE"],
      5: ["AMOUR","CONGO","GANGE","HURON","INDUS","LEMAN","LOIRE","NIGER","RHONE","SEINE","VOLGA","YUKON"],
      6: ["BAIKAL","DANUBE","LADOGA","MAJEUR","MEKONG"],
      7: ["ZAMBEZE"],
    },
  },
  {
    themeId: "fr-d-langues",
    label: "Langues",
    difficultyTier: "D",
    wordsByLength: {
      4: ["GREC","THAI","TURC"],
      5: ["ARABE","FARSI","HINDI","KURDE","RUSSE","SERBE"],
      6: ["BASQUE","BIRMAN","COREEN","CROATE","DANOIS","HEBREU","MALAIS","MONGOL","NEPALI","OURDOU","OUZBEK","TAMOUL"],
      7: ["ANGLAIS","BENGALI","BERBERE","CHINOIS","ITALIEN","ROUMAIN","TCHEQUE"],
    },
  },
  {
    themeId: "fr-d-monnaies",
    label: "Monnaies",
    difficultyTier: "D",
    wordsByLength: {
      4: ["BAHT","DONG","LIRE","MARK","PESO","YUAN"],
      5: ["DINAR","RIYAL"],
      6: ["DIRHAM","DOLLAR","ESCUDO","FLORIN","PESETA","ROUBLE","ROUPIE","SHEKEL"],
      7: ["DRACHME"],
    },
  },
  {
    themeId: "fr-d-pays",
    label: "Pays",
    difficultyTier: "D",
    wordsByLength: {
      4: ["CUBA","INDE","IRAN","IRAQ","LAOS","MALI","OMAN","TOGO"],
      5: ["ARUBA","BELAU","BENIN","CHILI","CHINE","GABON","GHANA","GRECE","HAITI","JAPON","KENYA","LIBAN","LIBYE","MACAO","MALTE","MAROC","MONDE","NAURU","NEPAL","PEROU","QATAR","SAMOA","SUEDE","SYRIE","TCHAD","TONGA","YEMEN"],
      6: ["ANGOLA","BELIZE","BRESIL","BRUNEI","CANADA","CHYPRE","EGYPTE","FRANCE","GAMBIE","GUINEE","GUYANA","ISRAEL","ITALIE","MALAWI","RUSSIE","RWANDA","SERBIE","SOUDAN","SUISSE","TAIWAN","TUVALU","ZAMBIE"],
      7: ["ALBANIE","ALGERIE","ANDORRE","ARMENIE","BAHAMAS","BAHREIN","BARBADE","BHOUTAN","BOLIVIE","BURUNDI","COMORES","CROATIE","ESPAGNE","ESTONIE","GEORGIE","HONGRIE","IRLANDE","ISLANDE","LESOTHO","LIBERIA","MAURICE","MAYOTTE","MEXIQUE","NAMIBIE","NIGERIA","NORVEGE","OUGANDA","POLOGNE","SENEGAL","SOMALIE","TUNISIE","TURQUIE","UKRAINE","URUGUAY","VANUATU"],
    },
  },
  {
    themeId: "fr-d-villes-asiatiques",
    label: "Villes Asiatiques",
    difficultyTier: "D",
    wordsByLength: {
      4: ["AGRA","ALEP","OMSK"],
      5: ["DELHI","DHAKA","HAIFA","IZMIR","KIRIN","KYOTO","LHASA","MEDAN","OSAKA"],
      6: ["BOMBAY","CHIRAZ","HEBRON","JAIPUR","KANPUR","MADRAS","TAIPEI"],
      7: ["BASSORA","BENARES","COLOMBO","DJEDDAH","ISPAHAN","KARACHI","MOSSOUL","RANGOON"],
    },
  },
  {
    themeId: "fr-d-villes-du-monde",
    label: "Villes du monde",
    difficultyTier: "D",
    wordsByLength: {
      4: ["BONN","LYON","NICE","PISE","YORK"],
      5: ["DUBAI","LIEGE","MIAMI","MILAN","REIMS","TURIN","VARNA"],
      6: ["AUSTIN","BILBAO","BOSTON","CANCUN","CANNES","DALLAS","DENVER","DRESDE","GENEVE","LOUXOR","MUMBAI","MUNICH","NAPLES","OXFORD","QUEBEC","RHODES","SYDNEY","VENISE","VERONE","ZURICH"],
      7: ["ATLANTA","BRISTOL","CARDIFF","CHESTER","CHICAGO","DETROIT","GLASGOW","HOUSTON","LARNACA","MEMPHIS","MYKONOS","ORLANDO","SEATTLE","SEVILLE","SHENZEN","TORONTO"],
    },
  },
  {
    themeId: "fr-d-villes-europeennes",
    label: "Villes Europeennes",
    difficultyTier: "D",
    wordsByLength: {
      4: ["BALE","CORK"],
      5: ["BREME","DIJON","GENES","LEEDS"],
      6: ["ANVERS","BRUGES","GDANSK","MALAGA","ODESSA","TALLIN"],
      7: ["BELFAST","COLOGNE","VALENCE"],
    },
  },
  {
    themeId: "fr-e-dieux-et-deesses",
    label: "Dieux et Deesses",
    difficultyTier: "E",
    wordsByLength: {
      4: ["HERA","ODIN","RAMA","THOR","ZEUS"],
      5: ["CERES","CIRCE","DIANE","HADES","JANUS","JUNON","SHIVA","VESTA"],
      6: ["ATHENA","HERMES","HESTIA","ISHTAR"],
      7: ["APOLLON","ARTEMIS","DEMETER","KRISHNA","MINERVE","VISHNOU","VULCAIN"],
    },
  },
  {
    themeId: "fr-e-groupes-de-musiques-celebres",
    label: "Groupes de musiques celebres",
    difficultyTier: "E",
    wordsByLength: {
      4: ["BLUR","KISS","MUSE"],
      5: ["QUEEN","WILCO"],
      6: ["PIXIES","WEEZER"],
      7: ["BAUHAUS","DRUMMER","GARBAGE","GENESIS","MISFITS","NIRVANA","PANTERA","PLACEBO","RAINBOW","RAMONES","ROXETTE","SEETHER"],
    },
  },
  {
    themeId: "fr-e-lieux-imaginaires",
    label: "Lieux Imaginaires",
    difficultyTier: "E",
    wordsByLength: {
      4: ["ARDA","URAK"],
      5: ["ARGUS","ASHAN","NABOO","NEXUS","OERTH"],
      6: ["ASGARD","ATREIA","ELRIOS","NARNIA","THEDAS","UTOPIA","XANADU"],
      7: ["AZEROTH","CAMELOT","ETERNIA","ETHERIA","PANDORA"],
    },
  },
  {
    themeId: "fr-e-marques-celebres",
    label: "Marques Celebres",
    difficultyTier: "E",
    wordsByLength: {
      4: ["ACER","AVON","BOSE","DELL","DIOR","DOVE","FILA","FUJI","LEGO","NIKE","OLAY","OREO","SONY","TWIX"],
      5: ["APPLE","ASICS","CASIO","CREST","DOLBY","EVIAN","FANTA","GUCCI","HALLS","HEINZ","KNORR","KRAFT","LINDT","MAGGI","NIKON","NIVEA","NOKIA","PEPSI","PRADA","ROLEX","SANYO","SHARP","TEFAL","TWIRL","UMBRO","VICHY","WELLA","XEROX"],
      6: ["ADIDAS","ARMANI","BOUNTY","CHANEL","CRUNCH","GALAXY","GIBSON","GODIVA","HENKEL","HOOVER","LIPTON","MATTEL","MENTOS","RAYBAN","REEBOK","REVLON","REXONA","SMACKS","SPRITE","TAMPAX","VIAGRA"],
      7: ["AIRNESS","BARILLA","BUITONI","CADBURY","CARTIER","CLARINS","COLGATE","CRAYOLA","GRUNDIG","HISENSE","KENWOOD","KICKERS","KLEENEX","LACOSTE","LANCOME","MAIZENA","MIRINDA","NESCAFE","NUTELLA","PAMPERS","PANTENE","PERRIER","PHILIPS","SAMSUNG","SUNSILK","TOSHIBA","VERSACE"],
    },
  },
  {
    themeId: "fr-e-marques-de-voiture",
    label: "Marques de voiture",
    difficultyTier: "E",
    wordsByLength: {
      4: ["AUDI","FIAT","FORD","OPEL","SAAB","SEAT"],
      5: ["BUICK","DACIA","DODGE","HONDA","ISUZU","LEXUS","LOTUS","MAZDA","SKODA","SMART","VOLVO"],
      6: ["HUMMER","LANCIA","NISSAN","SUBARU","SUZUKI","TOYOTA"],
      7: ["BENTLEY","BUGATTI","CITROEN","FERRARI","HYUNDAI","PEUGEOT","PONTIAC","PORSCHE","RENAULT"],
    },
  },
  {
    themeId: "fr-e-mythologie-grecque",
    label: "Mythologie Grecque",
    difficultyTier: "E",
    wordsByLength: {
      4: ["EROS","GAIA","RHEA","STYX"],
      5: ["CREON","ICARE","JASON","LETHE","MEDEE","MIDAS","MINOS","ORION","TITAN"],
      6: ["APOLLO","DAPHNE","EUROPE","FURIES","HELENE","HELIOS","MEDUSE","MENTOR","ORPHEE","PALLAS","PERSEE","POLLUX","PSYCHE","SCYLLA","SELENE","TETHYS","THESEE","ULYSSE"],
      7: ["ARACHNE","ELECTRA","GALATEE","IAPETUS","JOCASTE","NEMESIS","OCEANUS","PANDORE","TANTALE"],
    },
  },
  {
    themeId: "fr-e-mythologies-du-monde",
    label: "Mythologies du monde",
    difficultyTier: "E",
    wordsByLength: {
      4: ["NAGA","SITA"],
      5: ["AMRIT","ANKOU","ARTIO","BALOR","GANGA","GOULE","INDRA"],
      6: ["BHADRA","BRAHMA","CHAKRA","ENKIDU","RAVANA","SANKHA"],
      7: ["BAHAMUT","BELENUS","HANUMAN","HUMBABA"],
    },
  },
  {
    themeId: "fr-e-personnages-de-fiction",
    label: "Personnages de fiction",
    difficultyTier: "E",
    wordsByLength: {
      4: ["HULK","NEMO","YOGI"],
      5: ["AKIRA","ALICE","ARIEL","BALOO","BAMBI","DARIA","DUMBO","JERRY","KENNY","MILOU","MULAN","PLUTO","PONGO","ROBIN","SHREK","SIMBA"],
      6: ["ARTHUR","BATMAN","BEAVIS","BENDER","CASPER","DEXTER","DROOPY","GROMIT","IDEFIX","KERMIT","MERLIN","MOWGLI","OBELIX","POPEYE","SNOOPY","SPIROU","TARZAN","TINTIN","TWEETY"],
      7: ["ASTERIX","CHEETAH","MAFALDA","WALLACE"],
    },
  },
  {
    themeId: "fr-e-series-tv",
    label: "Series TV",
    difficultyTier: "E",
    wordsByLength: {
      4: ["GLEE","LOST"],
      5: ["ALIAS","CHIPS","FARGO","GRIMM","KOJAK","WEEDS"],
      6: ["CHEERS","FRINGE","HEROES","SCRUBS"],
      7: ["BONANZA","COLUMBO","DYNASTY","FRASIER","FRIENDS"],
    },
  },
  {
    themeId: "fr-e-titres-de-films",
    label: "Titres de Films",
    difficultyTier: "E",
    wordsByLength: {
      4: ["DUEL","JUNO","TRON","WOLF"],
      5: ["ABYSS","ALIEN","ANNIE","BENJI","BORAT","BRUNO","BUGSY","CRASH","DOGMA","EVITA","FRIDA","RAMBO","ROCKY","ROUGE","SEVEN","TAKEN","ZELIG","ZORRO"],
      6: ["AVATAR","BRAZIL","CASINO","GREASE","LOLITA","MATRIX","MISERY","SCREAM","WILLOW"],
      7: ["ALADDIN","AMADEUS","AVIATOR","CABARET","DRACULA","FRANTIC","JUMANJI","MEMENTO","PERSONA","PIRATES","PLATOON","REBECCA","RESPIRO","ROBOCOP","SHINING","SOLARIS","TITANIC","TOOTSIE","TRAFFIC"],
    },
  },
];
