import type { SampleThemeWords } from '../types.js';

/**
 * Generated from docs/design/word-lists — do not hand-edit.
 * Regenerate with `node scripts/generate-word-lists.mjs` after the source
 * JSON files change (rebuild the engine first: `npm run build`).
 */
export const FRENCH_WORD_LIST_THEMES: readonly SampleThemeWords[] = [
  {
    themeId: "fr-a-anatomie",
    label: "Anatomie",
    difficultyTier: "A",
    wordsByLength: {
      4: ["BRAS","CILS","CÔTE","DENT","FOIE","IRIS","JOUE","MAIN","NERF","PEAU","RATE","REIN","SANG","SEIN","TÊTE"],
      5: ["AORTE","COEUR","COUDE","CRÂNE","DOIGT","FÉMUR","GENOU","GORGE","JAMBE","LÈVRE","NUQUE","ONGLE","PAUME","POUCE","TALON","TIBIA","VEINE"],
      6: ["ARTÈRE","BASSIN","BOUCHE","CUISSE","ÉPAULE","HANCHE","LANGUE","LARYNX","MENTON","MOLLET","MUSCLE","NARINE","ORTEIL","OVAIRE","POUMON","RADIUS","RÉTINE","ROTULE","THORAX","TYMPAN","VESSIE"],
      7: ["ABDOMEN","CERVEAU","CHEVEUX","ESTOMAC","HUMÉRUS","OREILLE","PHARYNX","POIGNET","SOURCIL","STERNUM","TRACHÉE"],
    },
  },
  {
    themeId: "fr-a-animaux",
    label: "Animaux",
    difficultyTier: "A",
    wordsByLength: {
      4: ["BUSE","CERF","CHAT","ÉLAN","GRUE","IBIS","KIWI","LAMA","LION","LOUP","LYNX","MITE","OURS","PAON","PORC","PUCE","PUMA","THON","VEAU","ZÉBU"],
      5: ["AIGLE","BISON","CHIEN","CRABE","CYGNE","DINGO","FURET","GUÊPE","HÉRON","HIBOU","HUSKY","HYÈNE","KOALA","LAPIN","MORSE","MOULE","MULET","ORQUE","PANDA","PONEY","SINGE","TAPIR","TAUPE","TIGRE","TIQUE","ZÈBRE"],
      6: ["AGNEAU","AUTOUR","BAUDET","CAFARD","CAILLE","CALMAR","CANARD","CASTOR","CHACAL","CHEVAL","CHÈVRE","CIGALE","COBAYE","COUCOU","DINDON","ÉPONGE","FAISAN","FAUCON","FOURMI","FRELON","GIRAFE","HOMARD","HUÎTRE","IGUANE","JAGUAR","JUMENT","LÉZARD","LIMACE","LOUTRE","MOUTON","NARVAL","OCELOT","OTARIE","OURSIN","PAONNE","PHOQUE","PIGEON","PUTOIS","RENARD","REQUIN","SOURIS","TÉTRAS","TORTUE","TOUCAN","TRUITE","VIPÈRE"],
      7: ["ABEILLE","ACARIEN","BALEINE","BELETTE","CHAMOIS","CIGOGNE","COLOMBE","CORBEAU","COUGUAR","CRAPAUD","CRIQUET","DAUPHIN","GAZELLE","GOÉLAND","GORILLE","GRILLON","GRIZZLI","HAMSTER","HERMINE","LÉOPARD","LOMBRIC","LUCIOLE","MANCHOT","MOINEAU","MOUETTE","MUSTANG","OPOSSUM","PÉLICAN","PERDRIX","PIRANHA","PITBULL","SERPENT","TERMITE","VAUTOUR"],
    },
  },
  {
    themeId: "fr-a-vetements-accesssoires",
    label: "Vêtements & Accesssoires",
    difficultyTier: "A",
    wordsByLength: {
      4: ["BODY","CAPE","GANT","JEAN","JUPE","KÉPI","KILT","PULL","ROBE","SARI","SLIP","TONG","TUTU"],
      5: ["BAGUE","BÉRET","BOTTE","BOXER","BURQA","CHÂLE","GAINE","GILET","HABIT","KIPPA","MANTE","NIQAB","NOEUD","PARKA","POCHE","SABOT","SHORT","SWEAT","TENUE","VESTE","VOILE"],
      6: ["ANORAK","BASKET","BIKINI","BLAZER","BLOUSE","BONNET","BOUCLE","BOURSE","BOUTON","CAFTAN","CASQUE","CORSET","JERSEY","KIMONO","MANCHE","MASQUE","MONTRE","PONCHO","PYJAMA","SANGLE","SARONG","TURBAN"],
      7: ["BOTTINE","CAGOULE","CALEÇON","CHAPEAU","CHEMISE","COLLANT","COLLIER","COSTUME","CRAVATE","ÉCHARPE","FOULARD","HOMBURG","LEGGING","MAILLOT","MANTEAU","MITAINE","MOUFLES","POLAIRE","SACOCHE","SANDALE","SMOKING","SOULIER","TABLIER","TUNIQUE"],
    },
  },
  {
    themeId: "fr-a-capitales-celebres",
    label: "Capitales célèbres",
    difficultyTier: "A",
    wordsByLength: {
      4: ["DOHA","LIMA","OSLO","ROME"],
      5: ["ACCRA","ALGER","AMMAN","BERNE","CAIRE","DAKAR","HANOI","PARIS","PEKIN","QUITO","RABAT","RIYAD","SEOUL","SOFIA","TOKYO","TUNIS"],
      6: ["ANKARA","BERLIN","BOGOTA","DUBLIN","HAVANE","MADRID","MEXICO","MOSCOU","OTTAWA","PRAGUE","VIENNE"],
      7: ["ATHENES","BANGKOK","CARACAS","JAKARTA","LONDRES","MANILLE","NAIROBI"],
    },
  },
  {
    themeId: "fr-a-fruits",
    label: "Fruits",
    difficultyTier: "A",
    wordsByLength: {
      4: ["COCO","KAKI","KIWI","MÛRE"],
      5: ["DATTE","FIGUE","MELON","NÈFLE","OLIVE","PÊCHE","POIRE","POMME","PRUNE"],
      6: ["ANANAS","AVOCAT","BANANE","CASSIS","CÉDRAT","CERISE","CITRON","FRAISE","GOYAVE","JUJUBE","LITCHI","MANGUE","ORANGE","PAPAYE","POMELO","RAISIN","TOMATE"],
      7: ["ABRICOT","GRENADE","KUMQUAT"],
    },
  },
  {
    themeId: "fr-a-legumes-legumineuses",
    label: "Légumes & Légumineuses",
    difficultyTier: "A",
    wordsByLength: {
      4: ["CHOU","FÈVE","GUAR","MAÏS","OKRA","POIS","SOJA"],
      5: ["BETTE","NAVET","RADIS"],
      6: ["BLETTE","CÉLERI","COURGE","ENDIVE","LAITUE","MANIOC","OIGNON","PANAIS"],
      7: ["CAROTTE","CRESSON","ÉPINARD","FENOUIL","HARICOT","OSEILLE","POIREAU","POIVRON","POTIRON","ROMAINE"],
    },
  },
  {
    themeId: "fr-a-instruments-de-musique",
    label: "Instruments de musique",
    difficultyTier: "A",
    wordsByLength: {
      4: ["ALTO","GONG","LUTH","LYRE","TUBA"],
      5: ["BANJO","BASSE","CELLO","FLÛTE","HARPE","KAZOO","ORGUE","PIANO","SITAR"],
      6: ["BASSON","CORNET","DJEMBÉ","GRELOT","PIPEAU","VIOLON"],
      7: ["CLAVIER","CYMBALE","DARBUKA","GUITARE","MARIMBA","OCARINA","TAMBOUR","UKULÉLÉ"],
    },
  },
  {
    themeId: "fr-a-metiers",
    label: "Métiers",
    difficultyTier: "A",
    wordsByLength: {
      4: ["CHEF","JUGE"],
      5: ["BONNE","CLOWN","COACH","GARDE","GUIDE","MAÇON","MAIRE","MARIN","MOINE","POÈTE","REINE","VALET"],
      6: ["ACTEUR","ARCHER","AUTEUR","AVOCAT","BARMAN","CONSUL","DÉPUTÉ","ESPION","EXPERT","GÉRANT","JOCKEY","MAÎTRE","MINEUR","MODÈLE","NAGEUR","PILOTE","PRÊTRE","PRINCE","RABBIN","SCRIBE","SHÉRIF","SOLDAT","TRADER"],
      7: ["ACTRICE","ARBITRE","ARTISTE","ATHLÈTE","ATTACHÉ","BARBIER","BATTEUR","BOUCHER","BOUFFON","CUISTOT","DACTYLO","DANSEUR","ÉDITEUR","ÉLEVEUR","EMPLOYÉ","FACTEUR","FERMIER","GARDIEN","GÉNÉRAL","GEÔLIER","GOLFEUR","HÔTESSE","LIVREUR","MÉDECIN","NOTAIRE","ORFÈVRE","OUVRIER","PASTEUR","PÊCHEUR","PEINTRE","POMPIER","PORTIER","ROUTIER","SERVEUR","SOUDEUR","STEWARD","VENDEUR","VICAIRE"],
    },
    wordLengthComposition: [{"length":5,"count":3},{"length":6,"count":2},{"length":7,"count":1}],
    allowFreeDirections: true,
  },
  {
    themeId: "fr-a-sports",
    label: "Sports",
    difficultyTier: "A",
    wordsByLength: {
      4: ["BOXE","GOLF","JUDO","SURF"],
      5: ["LUTTE","PADEL","RUGBY","VOILE"],
      6: ["AVIRON","BASKET","COURSE","HOCKEY","KARATE","MARCHE","SQUASH","TENNIS","VOLLEY"],
      7: ["BOWLING","CRICKET","CURLING","ESCRIME","KARTING","PLONGEE"],
    },
  },
  {
    themeId: "fr-a-moyens-de-transport",
    label: "Moyens de Transport",
    difficultyTier: "A",
    wordsByLength: {
      4: ["AUTO","JEEP","LIMO","MOTO","TAXI","VÉLO"],
      5: ["AVION","BUGGY","CANOË","FERRY","FUSÉE","MÉTRO","SKATE","TRAIN","WAGON","YACHT"],
      6: ["BARQUE","BATEAU","CAMION","GALÈRE","HÉLICO","NAVIRE","RADEAU"],
      7: ["BERLINE","CALÈCHE","CHARIOT","FRÉGATE","GONDOLE","LITIÈRE","MINIBUS","PÉNICHE","PIROGUE","PLANEUR","SCOOTER","TRAMWAY","VOILIER","VOITURE"],
    },
  },
  {
    themeId: "fr-a-pays",
    label: "Pays",
    difficultyTier: "A",
    wordsByLength: {
      4: ["CUBA","INDE","IRAK","IRAN","LAOS","MALI","NIUE","OMAN","TOGO"],
      5: ["BÉNIN","CHILI","CHINE","CONGO","FIDJI","GABON","GHANA","GRÈCE","HAÏTI","JAPON","KENYA","LIBAN","LIBYE","MALTE","MAROC","NAURU","NIGER","NÉPAL","PÉROU","QATAR","SAMOA","SUÈDE","SYRIE","TCHAD","TONGA","YÉMEN"],
      6: ["ANGOLA","BELIZE","BRUNEI","BRÉSIL","CANADA","CHYPRE","FRANCE","GAMBIE","GUINÉE","GUYANA","ISRAËL","ITALIE","KOSOVO","KOWEÏT","MALAWI","MONACO","PALAOS","PANAMA","RUSSIE","RWANDA","SERBIE","SOUDAN","SUISSE","TAÏWAN","TUVALU","ZAMBIE","ÉGYPTE"],
      7: ["ALBANIE","ALGÉRIE","ANDORRE","ARMÉNIE","BAHAMAS","BAHREÏN","BARBADE","BHOUTAN","BOLIVIE","BURUNDI","COMORES","CROATIE","ESPAGNE","ESTONIE","GRENADE","GÉORGIE","HONGRIE","IRLANDE","ISLANDE","LESOTHO","LIBÉRIA","MAURICE","MEXIQUE","MYANMAR","NAMIBIE","NIGÉRIA","NORVÈGE","OUGANDA","POLOGNE","SOMALIE","SÉNÉGAL","TUNISIE","TURQUIE","UKRAINE","URUGUAY","VANUATU","VIETNAM"],
    },
  },
  {
    themeId: "fr-a-aliments-vegetaliens",
    label: "Aliments végétaliens",
    difficultyTier: "A",
    wordsByLength: {
      4: ["ANIS","CHOU","COCO","FÈVE","GUAR","KAKI","MAÏS","MÛRE","NOIX","OKRA","POIS","SOJA","THYM","TOFU"],
      5: ["BETTE","CAJOU","CARVI","CUMIN","DATTE","FIGUE","MELON","NAVET","NÈFLE","OLIVE","PÊCHE","POIRE","POMME","PRUNE","RADIS","SAUGE","SUMAC"],
      6: ["AMANDE","ANANAS","AVOCAT","AVOINE","BANANE","CASSIS","CÉDRAT","CÉLERI","CERISE","CITRON","ENDIVE","FRAISE","GOYAVE","JUJUBE","LAITUE","LITCHI","MANGUE","MANIOC","MENTHE","MILLET","OIGNON","ORANGE","ORIGAN","PACANE","PANAIS","PAPAYE","PATATE","PERSIL","POIVRE","POMELO","QUINOA","RAISIN","SAFRAN","SEITAN","SÉSAME","TOMATE","TRUFFE","WASABI"],
      7: ["ABRICOT","BASILIC","CAROTTE","CHUTNEY","CRESSON","ÉPINARD","FENOUIL","GIROFLE","HARICOT","KETCHUP","KUMQUAT","PAPRIKA","POIREAU","POIVRON","VANILLE"],
    },
  },
  {
    themeId: "fr-a-aliments-non-vegetaliens",
    label: "Aliments non-végétaliens",
    difficultyTier: "A",
    wordsByLength: {
      4: ["LAIT","LARD","OEUF","PORC","THON","VEAU"],
      5: ["BACON","BOEUF","CRABE","CRÈME","DINDE","MORUE","MOULE","STEAK"],
      6: ["AGNEAU","BEURRE","CAILLE","CALMAR","CANARD","CAVIAR","DINDON","GIBIER","HOMARD","HUÎTRE","JAMBON","MERLAN","MOUTON","PIGEON","POULET","SAUMON","YAOURT"],
      7: ["ANCHOIS","CHEDDAR","CHORIZO","FROMAGE","SARDINE"],
    },
  },
  {
    themeId: "fr-a-mammiferes",
    label: "Mammifères",
    difficultyTier: "A",
    wordsByLength: {
      4: ["CERF","CHAT","ÉLAN","LION","LOUP","LYNX","OURS","PORC","PUMA","VEAU"],
      5: ["BISON","CHIEN","FURET","HYÈNE","KOALA","LAPIN","LÉMUR","MORSE","OKAPI","PANDA","SINGE","TAPIR","TAUPE","TIGRE","VISON","ZÈBRE"],
      6: ["BAUDET","BUFFLE","CASTOR","CHACAL","CHEVAL","CHÈVRE","COYOTE","GIRAFE","JAGUAR","LIÈVRE","LOUTRE","MOUTON","OTARIE","PHOQUE","RENARD","SOURIS","WAPITI"],
      7: ["BALEINE","BELETTE","CARIBOU","CHAMEAU","DAUPHIN","GAZELLE","GORILLE","GUÉPARD","HAMSTER","LÉOPARD","MACAQUE","OPOSSUM","WALLABY"],
    },
  },
  {
    themeId: "fr-b-herbes-epices",
    label: "Herbes & Épices",
    difficultyTier: "B",
    wordsByLength: {
      4: ["ANIS","THYM"],
      5: ["ANETH","CARVI","CUMIN","CURRY","SAUGE","SUMAC"],
      6: ["MENTHE","ORIGAN","PERSIL","POIVRE","SAFRAN"],
      7: ["BASILIC","FENOUIL","GIROFLE","LAURIER","MUSCADE","PAPRIKA","ROMARIN","VANILLE"],
    },
    wordLengthComposition: [{"length":5,"count":3},{"length":6,"count":2},{"length":7,"count":1}],
    allowFreeDirections: true,
  },
  {
    themeId: "fr-b-habitations-humaines",
    label: "Habitations Humaines",
    difficultyTier: "B",
    wordsByLength: {
      4: ["TOUR"],
      5: ["ASILE","GEÔLE","HÔTEL","HUTTE","IGLOO","MOTEL","RANCH","TENTE","VILLA"],
      6: ["ABBAYE","CABANE","CHALET","DUPLEX","FAVELA","MAISON","MANOIR","PALAIS","PRISON","REFUGE"],
      7: ["CHÂTEAU","COTTAGE"],
    },
    wordLengthComposition: [{"length":4,"count":1},{"length":5,"count":3},{"length":6,"count":1},{"length":7,"count":1}],
  },
  {
    themeId: "fr-b-boissons-alcoolisees",
    label: "Boissons alcoolisées",
    difficultyTier: "B",
    wordsByLength: {
      4: ["ARAK","GROG","OUZO","RAKI","RHUM","SAKÉ"],
      5: ["BIÈRE","CIDRE","LAGER","PORTO","PUNCH","STOUT","VODKA","XÉRÈS"],
      6: ["BRANDY","COGNAC","GRAPPA","KIRSCH","MADÈRE","MOJITO","MUSCAT","PASTIS","WHISKY"],
      7: ["BOURBON","CACHACA","LIQUEUR","MARTINI","MASTIKA","SAMBUCA","SANGRIA","TEQUILA"],
    },
  },
  {
    themeId: "fr-b-boissons-sans-alcool",
    label: "Boissons sans alcool",
    difficultyTier: "B",
    wordsByLength: {
      4: ["CAFE","COLA","LAIT","SODA"],
      5: ["KÉFIR","SIROP"],
      6: ["NECTAR"],
      7: ["TONIQUE"],
    },
    wordLengthComposition: [{"length":4,"count":4},{"length":5,"count":1},{"length":6,"count":1}],
  },
  {
    themeId: "fr-b-boite-a-outil",
    label: "Boîte à outil",
    difficultyTier: "B",
    wordsByLength: {
      4: ["CLEF","ÉTAU","LIME","SCIE"],
      5: ["FORET","PINCE","RABOT","RÈGLE"],
      6: ["CISEAU","NIVEAU","VRILLE"],
      7: ["MAILLET","MARTEAU","PINCEAU"],
    },
  },
  {
    themeId: "fr-b-meubles",
    label: "Meubles",
    difficultyTier: "B",
    wordsByLength: {
      4: ["BANC","POUF","SOFA"],
      5: ["DIVAN","FUTON","HAMAC","TABLE","TRÔNE"],
      6: ["BUFFET","BUREAU","CANAPÉ","CHAISE","COFFRE"],
      7: ["ARMOIRE","BERCEAU","COMMODE","ÉTAGÈRE","PLACARD"],
    },
  },
  {
    themeId: "fr-b-vaisselles-et-couverts",
    label: "Vaisselles et Couverts",
    difficultyTier: "B",
    wordsByLength: {
      4: ["RÂPE"],
      5: ["FOUET","MOULE","PINCE","PIQUE","POÊLE","TAMIS","TASSE","VERRE"],
      6: ["CARAFE","LOUCHE","MOULIN","PICHET"],
      7: ["CISEAUX","COUTEAU","GOBELET","MARMITE","PLANCHE","PLATEAU","SPATULE","THÉIÈRE"],
    },
    wordLengthComposition: [{"length":4,"count":1},{"length":5,"count":3},{"length":6,"count":1},{"length":7,"count":1}],
  },
  {
    themeId: "fr-b-equipement-sportif",
    label: "Équipement sportif",
    difficultyTier: "B",
    wordsByLength: {
      4: ["CLUB","GANT","LUGE","SURF","VELO"],
      5: ["BATON","CANNE","CIBLE","CORDE","FILET","PATIN","SELLE","TAPIS"],
      6: ["AVIRON","BALLON","CASQUE","DISQUE","PAGAIE","PANIER","SANGLE","VOLANT"],
      7: ["CRAMPON","HALTERE","HARNAIS","JAVELOT","MAILLET","PLANCHE","SIFFLET"],
    },
  },
  {
    themeId: "fr-b-etendues-aquatiques",
    label: "Étendues aquatiques",
    difficultyTier: "B",
    wordsByLength: {
      4: ["BAIE","MARE"],
      5: ["CANAL","ÉTANG","FJORD","GOLFE","OASIS","OCÉAN"],
      6: ["BASSIN","CRIQUE","FLEUVE","LAGUNE","MARAIS","RAPIDE","SOURCE"],
      7: ["CASCADE","DÉTROIT","GLACIER","ICEBERG","RIVIÈRE","TORRENT"],
    },
    wordLengthComposition: [{"length":5,"count":3},{"length":6,"count":2},{"length":7,"count":1}],
    allowFreeDirections: true,
  },
  {
    themeId: "fr-b-on-y-fait-du-sport",
    label: "On y fait du sport",
    difficultyTier: "B",
    wordsByLength: {
      4: ["DOJO","RING"],
      5: ["ARÈNE","COURT","PISTE","SALLE","STADE"],
      6: ["MANÈGE","TATAMI"],
      7: ["CIRCUIT","GYMNASE","PISCINE","TERRAIN"],
    },
    wordLengthComposition: [{"length":5,"count":3},{"length":6,"count":2},{"length":7,"count":1}],
    allowFreeDirections: true,
  },
  {
    themeId: "fr-c-bijouterie",
    label: "Bijouterie",
    difficultyTier: "C",
    wordsByLength: {
      4: ["CLIP","JADE","JONC","ONYX"],
      5: ["AGATE","AMBRE","BAGUE","BÉRYL","CAMÉE","JASPE","OPALE","PERLE","RUBIS","TIARE"],
      6: ["ANNEAU","ARGENT","BROCHE","CHAÎNE","GRENAT","SAPHIR","TOPAZE","TORQUE","ZIRCON"],
      7: ["APATITE","CITRINE","COLLIER","DIADÈME","DIAMANT","FERMOIR"],
    },
  },
  {
    themeId: "fr-c-outils-de-jardinage",
    label: "Outils de jardinage",
    difficultyTier: "C",
    wordsByLength: {
      4: ["HOUE"],
      5: ["BÊCHE","PELLE","SERPE"],
      6: ["GRIFFE","PIOCHE","RÂTEAU"],
      7: ["BINETTE","FOURCHE"],
    },
    wordLengthComposition: [{"length":4,"count":1},{"length":5,"count":3},{"length":6,"count":1},{"length":7,"count":1}],
  },
  {
    themeId: "fr-c-materiel-de-menage",
    label: "Matériel de ménage",
    difficultyTier: "C",
    wordsByLength: {
      4: ["SEAU"],
      5: ["BALAI","GANTS","JAVEL","SAVON","SPRAY"],
      6: ["BROSSE","CIRAGE","ÉPONGE"],
      7: ["BASSINE","CHAMOIS","CHIFFON","LAVETTE","LESSIVE","PLUMEAU","TORCHON"],
    },
    wordLengthComposition: [{"length":4,"count":1},{"length":5,"count":3},{"length":6,"count":1},{"length":7,"count":1}],
  },
  {
    themeId: "fr-c-pierres-precieuses",
    label: "Pierres précieuses",
    difficultyTier: "C",
    wordsByLength: {
      4: ["JADE","ONYX"],
      5: ["AGATE","AMBRE","BÉRYL","JASPE","LAPIS","OPALE","PERLE","RUBIS"],
      6: ["CORAIL","GRENAT","IOLITE","QUARTZ","SAPHIR","TOPAZE","ZIRCON"],
      7: ["APATITE","AZURITE","CALCITE","CITRINE","PÉRIDOT"],
    },
    wordLengthComposition: [{"length":5,"count":3},{"length":6,"count":2},{"length":7,"count":1}],
    allowFreeDirections: true,
  },
  {
    themeId: "fr-c-arbres",
    label: "Arbres",
    difficultyTier: "C",
    wordsByLength: {
      4: ["BUIS","HOUX","ORME"],
      5: ["AULNE","CHÊNE","CÈDRE","FRÊNE","HÊTRE","NOYER","SAPIN","SAULE"],
      6: ["ACACIA","BANIAN","CHARME","CYPRÈS","MÉLÈZE","ÉPICÉA","ÉRABLE"],
      7: ["BOULEAU","OLIVIER","PALMIER","PLATANE","SORBIER","SÉQUOIA","TILLEUL"],
    },
  },
  {
    themeId: "fr-c-armement",
    label: "Armement",
    difficultyTier: "C",
    wordsByLength: {
      4: ["MINE","ÉPÉE"],
      5: ["BALLE","BOMBE","CANON","DAGUE","FUSIL","LANCE","MASSE","SABRE"],
      6: ["FLÈCHE"],
      7: ["COUTEAU","FLEURET","GRENADE","MISSILE","MORTIER"],
    },
    wordLengthComposition: [{"length":5,"count":4},{"length":7,"count":2}],
    allowFreeDirections: true,
  },
  {
    themeId: "fr-c-accessoires-de-plage",
    label: "Accessoires de plage",
    difficultyTier: "C",
    wordsByLength: {
      4: ["SEAU","TUBA"],
      5: ["BOUÉE","CRÈME","NATTE","TONGS"],
      6: ["BALLON","CHAISE","PALMES"],
      7: ["FRISBEE","MAILLOT","PARASOL","VISIÈRE"],
    },
    wordLengthComposition: [{"length":5,"count":3},{"length":6,"count":2},{"length":7,"count":1}],
    allowFreeDirections: true,
  },
  {
    themeId: "fr-c-desserts-et-sucreries",
    label: "Desserts et sucreries",
    difficultyTier: "C",
    wordsByLength: {
      4: ["FLAN"],
      5: ["CRÊPE","DONUT","FUDGE","GELÉE","GLACE","SABLÉ","SCONE","TARTE"],
      6: ["BONBON","CHURRO","COOKIE","GAUFRE","MOUSSE","MUFFIN","NOUGAT","SORBET","TRUFFE","ÉCLAIR"],
      7: ["BAKLAVA","BEIGNET","BISCUIT","BROWNIE","CANNELÉ","CARAMEL","COMPOTE","CRUMBLE","CUPCAKE","MACARON","PARFAIT","PRALINE","PUDDING","SOUFFLÉ","STRUDEL"],
    },
    wordLengthComposition: [{"length":4,"count":1},{"length":5,"count":3},{"length":6,"count":1},{"length":7,"count":1}],
  },
  {
    themeId: "fr-c-le-temps-et-ses-mesures",
    label: "Le temps et ses mesures",
    difficultyTier: "C",
    wordsByLength: {
      4: ["AUBE","HIER","MIDI","MOIS","SOIR","TARD"],
      5: ["ANNÉE","APRÈS","AVANT","DURÉE","DÉLAI","FUTUR","HEURE","MATIN","PASSÉ"],
      6: ["ACTUEL","ANNUEL","CADRAN","DEMAIN","MINUIT","MINUTE","MOMENT","MONTRE","RETARD","SAISON","SIÈCLE","ÉPOQUE"],
      7: ["BIENTÔT","HORAIRE","HORLOGE","INSTANT","PRÉSENT","PÉRIODE","SECONDE","SEMAINE"],
    },
  },
  {
    themeId: "fr-c-fleurs",
    label: "Fleurs",
    difficultyTier: "C",
    wordsByLength: {
      4: ["ARUM","IRIS","ROSE"],
      5: ["LILAS","LOTUS","PAVOT"],
      6: ["AZALEE","BLEUET","COSMOS","DAHLIA","JASMIN","MUGUET","PENSEE","TULIPE"],
      7: ["BEGONIA","CAMELIA","FREESIA","GERBERA","GLAIEUL","LAVANDE","PETUNIA","PIVOINE"],
    },
  },
  {
    themeId: "fr-c-le-calendrier",
    label: "Le calendrier",
    difficultyTier: "C",
    wordsByLength: {
      4: ["AOÛT","JUIN","LION","MARS"],
      5: ["AVRIL","HIVER","JEUDI","LUNDI","MARDI"],
      6: ["BÉLIER","CANCER","SAMEDI","VIERGE"],
      7: ["AUTOMNE","BALANCE","FÉVRIER","GÉMEAUX","JANVIER","JUILLET","OCTOBRE","TAUREAU","VERSEAU"],
    },
  },
  {
    themeId: "fr-d-styles-musicaux",
    label: "Styles musicaux",
    difficultyTier: "D",
    wordsByLength: {
      4: ["FOLK","FUNK","JAZZ","PUNK","ROCK","SOCA","SOUL","ZOUK"],
      5: ["BLUES","CONGA","DISCO","HOUSE","MAMBO","MÉTAL","OPÉRA","RUMBA","SALSA","SAMBA","SWING","TANGO","VALSE"],
      6: ["BOLÉRO","GARAGE","GOSPEL","GRUNGE","HIPHOP","MOTOWN","REGGAE","TECHNO","TRANSE"],
      7: ["BAROQUE","BRITPOP","CALYPSO","COUNTRY","DUBSTEP","RAGTIME","ÉLECTRO"],
    },
  },
  {
    themeId: "fr-d-sources-de-lumiere",
    label: "Sources de lumière",
    difficultyTier: "D",
    wordsByLength: {
      4: ["HALO","LUNE","NÉON"],
      5: ["FANAL","FLASH","LAMPE","LASER","LUEUR","PHARE"],
      6: ["BOUGIE","BRAISE","COMÈTE","FLAMME","SOLEIL","TORCHE","ÉCLAIR","ÉTOILE"],
      7: ["AMPOULE","BRIQUET","LAMPION","LUCIOLE","MÉTÉORE"],
    },
  },
  {
    themeId: "fr-d-chefs-leaders",
    label: "Chefs & Leaders",
    difficultyTier: "D",
    wordsByLength: {
      4: ["CHAH","DOGE","KHAN","PAPE","TSAR","ÉMIR"],
      5: ["BARON","COMTE","NÉGUS","REINE","TYRAN","VIZIR"],
      6: ["CALIFE","CHEIKH","GOUROU","PRINCE","RÉGENT","SHOGUN","SULTAN"],
      7: ["PHARAON","TSARINE"],
    },
  },
  {
    themeId: "fr-d-pieces-de-voiture",
    label: "Pièces de voiture",
    difficultyTier: "D",
    wordsByLength: {
      4: ["PNEU","ROUE"],
      5: ["BOÎTE","CAPOT","JAUGE","JOINT","PHARE","PORTE","RÉTRO","VITRE"],
      6: ["AIRBAG","ALARME","ESSIEU","FILTRE","FREINS","JANTES","KLAXON","LEVIER","MOTEUR","PISTON","PÉDALE","VOLANT"],
      7: ["AILERON","CAPTEUR","CHÂSSIS","CONSOLE","FUSIBLE","SERRURE"],
    },
    wordLengthComposition: [{"length":5,"count":3},{"length":6,"count":2},{"length":7,"count":1}],
    allowFreeDirections: true,
  },
  {
    themeId: "fr-d-anatomie-animale",
    label: "Anatomie animale",
    difficultyTier: "D",
    wordsByLength: {
      4: ["AILE","BRAS","CROC","DARD","OEIL","POIL"],
      5: ["BOSSE","CORNE","DUVET","ERGOT","PATTE","PLUME","QUEUE","SABOT","SERRE"],
      6: ["GRIFFE","MUSEAU","PATTES","PELAGE","TROMPE","ÉLYTRE"],
      7: ["ANTENNE","DÉFENSE","ÉCAILLE"],
    },
  },
  {
    themeId: "fr-d-bebes-animaux",
    label: "Bébés animaux",
    difficultyTier: "D",
    wordsByLength: {
      4: ["FAON","VEAU"],
      5: ["CHIOT","LARVE","OISON","TACON"],
      6: ["AIGLON","ALEVIN","CHATON","NYMPHE","OURSON","TÊTARD"],
      7: ["AGNELET","ASTICOT","CANETON","CIVELLE","CYGNEAU","GIRAFON","LEVRAUT","POULAIN","POUSSIN"],
    },
    wordLengthComposition: [{"length":5,"count":3},{"length":6,"count":2},{"length":7,"count":1}],
    allowFreeDirections: true,
  },
  {
    themeId: "fr-d-garnitures-de-pizza",
    label: "Garnitures de pizza",
    difficultyTier: "D",
    wordsByLength: {
      4: ["BRIE","FETA","POIS","THON"],
      5: ["BACON","BOEUF","CRÈME","DINDE","PESTO"],
      6: ["ANANAS","AVOCAT","CÂPRES","JAMBON","OLIVES","ORIGAN","POULET","SALAMI","SAUMON","TOMATE"],
      7: ["ANCHOIS","BASILIC","CHEDDAR","CHORIZO","FROMAGE","OIGNONS","POIVRON","RICOTTA"],
    },
  },
  {
    themeId: "fr-d-races-de-chiens",
    label: "Races de chiens",
    difficultyTier: "D",
    wordsByLength: {
      4: [],
      5: ["AKITA","BOXER","CORGI","DINGO","HUSKY","SPITZ"],
      6: ["BEAGLE","BERGER","BRIARD","COLLIE","WESTIE"],
      7: ["BASENJI","CANICHE","HARRIER","LEVRIER","MALTAIS","POINTER","SPANIEL","TERRIER"],
    },
    wordLengthComposition: [{"length":5,"count":3},{"length":6,"count":2},{"length":7,"count":1}],
    allowFreeDirections: true,
  },
  {
    themeId: "fr-d-climat-meteo",
    label: "Climat & Météo",
    difficultyTier: "D",
    wordsByLength: {
      4: ["VENT"],
      5: ["BRUME","FROID","GIVRE","GRÊLE","HIVER","NEIGE","NUAGE","ORAGE","PLUIE"],
      6: ["BRUINE","RAFALE","SAISON","TYPHON","ÉCLAIR"],
      7: ["AUTOMNE","CHALEUR","CYCLONE","OURAGAN","TEMPÊTE","TORNADE","VERGLAS"],
    },
    wordLengthComposition: [{"length":4,"count":1},{"length":5,"count":3},{"length":6,"count":1},{"length":7,"count":1}],
  },
  {
    themeId: "fr-d-poissons",
    label: "Poissons",
    difficultyTier: "D",
    wordsByLength: {
      4: ["SOLE","THON"],
      5: ["CARPE","MORUE","MULET"],
      6: ["DORADE","HARENG","PERCHE","REQUIN","SAUMON","SILURE","TRUITE","TURBOT"],
      7: ["ANCHOIS","BROCHET","PIRANHA","SARDINE","ÉGLEFIN"],
    },
    wordLengthComposition: [{"length":5,"count":3},{"length":6,"count":2},{"length":7,"count":1}],
    allowFreeDirections: true,
  },
  {
    themeId: "fr-d-marques-celebres",
    label: "Marques Célèbres",
    difficultyTier: "D",
    wordsByLength: {
      4: ["ACER","AVON","BOSE","DELL","DIOR","DOVE","FILA","FUJI","LEGO","MARS","NIKE","OLAY","OREO","PUMA","SONY","TWIX","VISA"],
      5: ["APPLE","ASICS","CANON","CASIO","CREST","DOLBY","EVIAN","FANTA","GUCCI","HALLS","HEINZ","HONDA","INTEL","KNORR","KRAFT","LINDT","MAGGI","NIKON","NIVEA","NOKIA","PEPSI","PRADA","ROLEX","SANYO","SHARP","TEFAL","TESLA","TWIRL","UMBRO","VICHY","WELLA","XEROX"],
      6: ["ADIDAS","AMAZON","ARMANI","BOUNTY","CHANEL","CRUNCH","DANONE","GALAXY","GIBSON","GODIVA","GOOGLE","HENKEL","HERMES","HOOVER","LIPTON","LOREAL","MATTEL","MENTOS","ORACLE","RAYBAN","REEBOK","REVLON","REXONA","SIGNAL","SMACKS","SPRITE","TAMPAX","VIAGRA"],
      7: ["AIRNESS","BARILLA","BUITONI","CADBURY","CARTIER","CLARINS","COLGATE","CRAYOLA","GRUNDIG","HISENSE","KENWOOD","KICKERS","KLEENEX","LACOSTE","LANCOME","MAIZENA","MIRINDA","NESCAFE","NUTELLA","PAMPERS","PANTENE","PERRIER","PHILIPS","SAMSUNG","SUNSILK","TOSHIBA","VERSACE"],
    },
  },
  {
    themeId: "fr-d-musique",
    label: "Musique",
    difficultyTier: "D",
    wordsByLength: {
      4: ["ALTO","ARIA","CLEF","NOTE","SOLO","TRIO"],
      5: ["BASSE","CANON","GAMME","HYMNE","OPÉRA","TEMPO","THÈME","TÉNOR"],
      6: ["ACCORD","ADAGIO","ATONAL","AUBADE","CHOEUR","GROUPE","MESURE","OCTAVE","RYTHME","SONATE","TIMBRE"],
      7: ["BALLADE","CADENCE","CANTATE","CHANSON","CONCERT","MÉLODIE","PRÉLUDE","QUATUOR","REFRAIN","RÉCITAL","SILENCE","SOLFÈGE","SOPRANO","UNISSON"],
    },
  },
  {
    themeId: "fr-e-anatomie-des-plantes",
    label: "Anatomie des plantes",
    difficultyTier: "E",
    wordsByLength: {
      4: ["PORE","SÈVE","TIGE"],
      5: ["BULBE","FLEUR","FRUIT","LIMBE","NOEUD","ÉPINE"],
      6: ["GRAINE","NECTAR","PISTIL","POLLEN","PÉTALE","RACINE","RAMEAU","SÉPALE"],
      7: ["BRANCHE","COROLLE","FEUILLE","STOMATE","ÉTAMINE"],
    },
  },
  {
    themeId: "fr-e-conteneurs-de-liquides",
    label: "Conteneurs de liquides",
    difficultyTier: "E",
    wordsByLength: {
      4: ["SEAU","VASE"],
      5: ["BARIL","BIDON","CHOPE","FIOLE","JARRE","OUTRE","TASSE","VERRE"],
      6: ["BÉCHER","CARAFE","CRUCHE","FLACON","GOURDE"],
      7: ["AMPHORE","BURETTE","CITERNE","CUVETTE","GOBELET","MARMITE","PIPETTE","THÉIÈRE","TONNEAU"],
    },
    wordLengthComposition: [{"length":5,"count":3},{"length":6,"count":2},{"length":7,"count":1}],
    allowFreeDirections: true,
  },
  {
    themeId: "fr-e-conteneurs-de-solides",
    label: "Conteneurs de solides",
    difficultyTier: "E",
    wordsByLength: {
      4: ["ÉTUI"],
      5: ["BOÎTE","COLIS","MALLE","POCHE"],
      6: ["BAGAGE","BOURSE","CAISSE","CARTON","CASIER","COFFRE","PANIER","PAQUET","TIROIR"],
      7: ["SACOCHE"],
    },
    wordLengthComposition: [{"length":4,"count":1},{"length":5,"count":3},{"length":6,"count":2}],
  },
  {
    themeId: "fr-e-couleurs",
    label: "Couleurs",
    difficultyTier: "E",
    wordsByLength: {
      4: ["AQUA","AZUR","BLEU","CYAN","DORÉ","GRIS","JADE","KAKI","NOIR","OCRE","ROSE","VERT"],
      5: ["AMBRE","BEIGE","BLANC","CRÈME","JAUNE","LILAS","MAUVE","OLIVE","PÊCHE","ROUGE","SÉPIA"],
      6: ["AMANDE","ARGENT","CERISE","CORAIL","CUIVRE","GRENAT","INDIGO","IVOIRE","MARRON","ORANGE","VIOLET"],
      7: ["ABRICOT","FUCHSIA","MAGENTA"],
    },
  },
  {
    themeId: "fr-e-elements-chimiques",
    label: "Éléments chimiques",
    difficultyTier: "E",
    wordsByLength: {
      4: ["BORE","IODE","NÉON","ZINC"],
      5: ["ARGON","AZOTE","BROME","FLUOR","PLOMB","RADON","XÉNON","ÉTAIN"],
      6: ["ARGENT","BARYUM","CHLORE","COBALT","CUIVRE","CURIUM","CÉRIUM","CÉSIUM","ERBIUM","HÉLIUM","INDIUM","NICKEL","OSMIUM","RADIUM","SODIUM","SOUFRE","TITANE"],
      7: ["ARSENIC","BISMUTH","BOHRIUM","CADMIUM","CALCIUM","CARBONE","DUBNIUM","GALLIUM","HAFNIUM","IRIDIUM","KRYPTON","LITHIUM","MERCURE","OXYGÈNE","THORIUM","URANIUM","YTTRIUM"],
    },
  },
  {
    themeId: "fr-e-groupes-d-amimaux",
    label: "Groupes d'amimaux",
    difficultyTier: "E",
    wordsByLength: {
      4: ["BANC","CLAN","NUÉE"],
      5: ["BANDE","HORDE","MEUTE"],
      6: ["COUVÉE","ESSAIM","HARDÉE","PORTÉE","TROUPE"],
      7: ["COLONIE"],
    },
    wordLengthComposition: [{"length":4,"count":3},{"length":5,"count":2},{"length":6,"count":1}],
  },
  {
    themeId: "fr-e-le-squelette-humain",
    label: "Le Squelette humain",
    difficultyTier: "E",
    wordsByLength: {
      4: [],
      5: ["CRÂNE","CÔTES","FÉMUR","TALUS","TIBIA","VOMER"],
      6: ["COCCYX","PÉRONÉ","RADIUS","ROTULE","SACRUM","ÉTRIER"],
      7: ["CUBITUS","ENCLUME","HUMÉRUS","MARTEAU","SCAPULA","STERNUM"],
    },
    wordLengthComposition: [{"length":5,"count":3},{"length":6,"count":2},{"length":7,"count":1}],
    allowFreeDirections: true,
  },
  {
    themeId: "fr-e-metaux",
    label: "Métaux",
    difficultyTier: "E",
    wordsByLength: {
      4: ["ZINC"],
      5: ["ACIER","PLOMB","ÉTAIN"],
      6: ["ARGENT","BRONZE","CHROME","COBALT","CUIVRE","NICKEL","TITANE"],
      7: ["LITHIUM","MERCURE","THORIUM","URANIUM"],
    },
    wordLengthComposition: [{"length":4,"count":1},{"length":5,"count":3},{"length":6,"count":1},{"length":7,"count":1}],
  },
  {
    themeId: "fr-e-uvres-d-art",
    label: "Œuvres d'art",
    difficultyTier: "E",
    wordsByLength: {
      4: ["FILM"],
      5: ["ALBUM","DANSE","HYMNE","OPÉRA","PHOTO","PIÈCE","POÈME","PROSE","ROMAN"],
      6: ["BALLET","DESSIN","PSAUME","SONATE","SONNET","STATUE","ÉLÉGIE","ÉPOPÉE"],
      7: ["BALLADE","CHANSON","COMÉDIE","CONCERT","CROQUIS","EFFIGIE","FRESQUE","GRAVURE","REQUIEM"],
    },
    wordLengthComposition: [{"length":4,"count":1},{"length":5,"count":3},{"length":6,"count":1},{"length":7,"count":1}],
  },
  {
    themeId: "fr-e-oiseaux",
    label: "Oiseaux",
    difficultyTier: "E",
    wordsByLength: {
      4: ["BUSE","GRUE","IBIS","KIWI"],
      5: ["AIGLE","CYGNE","HIBOU","HÉRON","MERLE"],
      6: ["AUTOUR","BUSARD","CAILLE","CANARD","CONDOR","COUCOU","DINDON","FAISAN","FAUCON","PAONNE","PIGEON","PINSON","PIVERT","TOUCAN","TÉTRAS"],
      7: ["CIGOGNE","CORBEAU","MANCHOT","MOINEAU","MOUETTE","MÉSANGE","PERDRIX","PÉLICAN","VAUTOUR"],
    },
  },
  {
    themeId: "fr-e-cours-d-eau",
    label: "Cours d'eau",
    difficultyTier: "E",
    wordsByLength: {
      4: ["ERIE","NESS","RHIN"],
      5: ["CONGO","GANGE","HURON","INDUS","LOIRE","LÉMAN","NIGER","SAÔNE","SEINE","TIGRE","VOLGA","VOLTA"],
      6: ["BAÏKAL","DANUBE","LOMOND","MALAWI","MÉKONG","TAMISE"],
      7: ["AMAZONE","GARONNE","MOSELLE","ONTARIO","VISTULE","YANGTSÉ","ZAMBÈZE"],
    },
  },
  {
    themeId: "fr-e-monnaies",
    label: "Monnaies",
    difficultyTier: "E",
    wordsByLength: {
      4: ["BAHT","DIME","DRAM","EURO","HWAN","INTI","KUNA","LIRE","MARK","PESO","REAL","YANG","YUAN"],
      5: ["BUDJU","DINAR","DUCAT","FRANC","KRONA","LIBRA","LIVRE","PAISA","RIYAL","SCUDO","SUCRE","ZLOTY"],
      6: ["DENIER","DINERO","DIRHAM","DOLLAR","ESCUDO","FLORIN","GINEIH","GOURDE","KORUNA","KWACHA","PESETA","ROUBLE","ROUPIE","SHEKEL","TANGKA","THALER"],
      7: ["AFGHANI","AUSTRAL","BOLIVAR","CENTIME","CRUZADO","DRACHME","PENNING","PIASTRE","RINGGIT","ROUPIAH"],
    },
  },
  {
    themeId: "fr-e-langues",
    label: "Langues",
    difficultyTier: "E",
    wordsByLength: {
      4: ["GREC","THAÏ","TURC"],
      5: ["ARABE","CORSE","HAKKA","HINDI","KURDE","LATIN","MAORI","PERSE","RUSSE","SERBE","SWATI","WOLOF","XIANG"],
      6: ["BASQUE","BIRMAN","BRETON","CORÉEN","DANOIS","FRISON","HÉBREU","KAZAKH","LETTON","MALAIS","OURDOU","OUZBEK","PERSAN","SOMALI","TADJIK","TAMOUL","ZOULOU"],
      7: ["ABKHAZE","ANGLAIS","BENGALI","BERBÈRE","BOSNIEN","CATALAN","CHINOIS","FINNOIS","GALLOIS","ITALIEN","LAOTIEN","MALTAIS","OCCITAN","QUECHUA","ROUMAIN","SLOVÈNE","SUÉDOIS","SWAHILI","TCHÈQUE","YIDDISH"],
    },
  },
  {
    themeId: "fr-e-villes-africaines",
    label: "Villes africaines",
    difficultyTier: "E",
    wordsByLength: {
      4: ["KANO","LAMU","LOMÉ","MAUN","SUEZ"],
      5: ["ACCRA","AKURE","ALGER","BÉNIN","CAIRE","DAKAR","GIZEH","LAGOS","RABAT","TUNIS","WARRI"],
      6: ["AGADIR","BAMAKO","BANGUI","DOUALA","DURBAN","HARARE","IBADAN","ILORIN","KADUNA","KIGALI","KUMASI","LUSAKA","MATOLA","NIAMEY","SOWETO","TANGER"],
      7: ["ABIDJAN","CONAKRY","KAMPALA","MOMBASA","NAIROBI","TRIPOLI","YAOUNDÉ"],
    },
  },
  {
    themeId: "fr-e-villes-asiatiques",
    label: "Villes asiatiques",
    difficultyTier: "E",
    wordsByLength: {
      4: ["ALEP","DOHA","XIAN"],
      5: ["DELHI","DHAKA","DUBAI","HANOI","KABUL","KYOTO","MACAO","OSAKA","RIYAD","SANAA","SURAT","SÉOUL","TOKYO","WUHAN"],
      6: ["ANKARA","BEIRUT","BOMBAY","JAIPUR","LAHORE","MADRAS","MOSCOU","MUMBAI","TAIPEI"],
      7: ["BAGHDAD","BANGKOK","BEIJING","BISHKEK","DJEDDAH","JAKARTA","KARACHI","MANILLE","MASHHAD","MOSSOUL","RANGOUN","TIANJIN","TÉHÉRAN"],
    },
  },
  {
    themeId: "fr-e-villes-europeennes",
    label: "Villes européennes",
    difficultyTier: "E",
    wordsByLength: {
      4: ["BALE","BONN","HAMM","LYON","NICE","OSLO","RIGA","ROME","VIGO","YORK"],
      5: ["BRAGA","BREDA","BREST","BRÊME","DIJON","ESPOO","ESSEN","GÊNES","LAHTI","LEEDS","LILLE","LIÈGE","MILAN","NAMUR","PARIS","PORTO","REIMS","SOFIA","TURIN","VARNA"],
      6: ["ANGERS","ANVERS","BERLIN","BOLTON","BRUGES","CANNES","CATANE","DRESDE","DUBLIN","DUDLEY","FOGGIA","KAUNAS","MADRID","MALAGA","MUNICH","NANTES","NAPLES","ODESSA","PADOUE","PRAGUE","RENNES","RIJEKA","SLOUGH","TOULON","VENISE","VIENNE","VÉRONE","ZURICH"],
      7: ["ATHÈNES","BELFAST","BOLOGNE","BRESCIA","BRISTOL","CARDIFF","COLOGNE","CORDOUE","CRAIOVA","GLASGOW","GRENADE","HAARLEM","HANOVRE","LEIPZIG","LONDRES","NEWPORT","NICOSIE","PALERME","RAVENNE","ROSTOCK","SALERNE","SÉVILLE","TALLINN","TAMPERE","VILNIUS"],
    },
  },
  {
    themeId: "fr-e-villes-nord-americaines",
    label: "Villes nord-américaines",
    difficultyTier: "E",
    wordsByLength: {
      4: [],
      5: ["MIAMI"],
      6: ["AUSTIN","BOSTON","CANCUN","DALLAS","DENVER","HAVANE","MERIDA","MEXICO","NASSAU","OTTAWA","PUEBLA","QUEBEC","TOLUCA"],
      7: ["ATLANTA","CALGARY","CHICAGO","DETROIT","HOUSTON","MANAGUA","MEMPHIS","ORLANDO","PHOENIX","SEATTLE","TIJUANA","TORONTO","ZAPOPAN"],
    },
    wordLengthComposition: [{"length":5,"count":1},{"length":6,"count":3},{"length":7,"count":2}],
    allowFreeDirections: true,
  },
  {
    themeId: "fr-e-villes-sud-americaines",
    label: "Villes sud-américaines",
    difficultyTier: "E",
    wordsByLength: {
      4: ["CALI","LIMA"],
      5: ["BÉLEM","CUZCO","NATAL","QUITO","SUCRE"],
      6: ["BOGOTA","MANAUS","RECIFE","SANTOS"],
      7: ["CARACAS","CORDOUE","IQUIQUE","MARACAY","MENDOZA","ROSARIO"],
    },
    wordLengthComposition: [{"length":5,"count":3},{"length":6,"count":2},{"length":7,"count":1}],
    allowFreeDirections: true,
  },
  {
    themeId: "fr-e-villes-du-monde",
    label: "Villes du monde",
    difficultyTier: "E",
    wordsByLength: {
      4: ["ALEP","APIA","BERN","BONN","DOHA","KIEV","LIMA","LOMÉ","LYON","NICE","OMSK","OSLO","PISE","RIGA","ROME","YORK"],
      5: ["ACCRA","ALGER","AMMAN","BAKOU","CAIRE","DAKAR","DELHI","DHAKA","DUBAI","GÊNES","HANOI","KABUL","KYOTO","LAGOS","LIÈGE","LUXOR","MIAMI","MILAN","MINSK","OSAKA","PARIS","QUITO","RABAT","REIMS","RIYAD","SANAA","SOFIA","SUCRE","SÉOUL","TOKYO","TUNIS","TURIN","VARNA"],
      6: ["ANKARA","ASMARA","ASTANA","AUSTIN","BAMAKO","BANGUI","BEIRUT","BERLIN","BILBAO","BISSAU","BOGOTA","BOSTON","CANCUN","CANNES","DALLAS","DENVER","DRESDE","DUBLIN","HARARE","HAVANE","KIGALI","LUANDA","MADRID","MANAMA","MAPUTO","MASERU","MECQUE","MONACO","MOSCOU","MUMBAI","MUNICH","NAPLES","NASSAU","NIAMEY","OTTAWA","OXFORD","PRAGUE","QUEBEC","RHODES","SYDNEY","TAIPEI","VENISE","VIENNE","VÉRONE","ZAGREB","ZURICH"],
      7: ["ABIDJAN","ATHÈNES","ATLANTA","BAGHDAD","BANGKOK","BEIJING","BISHKEK","BRISTOL","CARACAS","CARDIFF","CAYENNE","CHESTER","CHICAGO","CONAKRY","DETROIT","GLASGOW","GRENADE","HOUSTON","JAKARTA","KAMPALA","KOLKATA","LARNACA","LONDRES","MANAGUA","MANILLE","MEMPHIS","MYKONOS","NAIROBI","NICOSIE","ORLANDO","PAPEETE","SEATTLE","SÉVILLE","TALLINN","TORONTO","TRIPOLI","TÉHÉRAN","VILNIUS","YAOUNDÉ","YEREVAN"],
    },
  },
  {
    themeId: "fr-e-capitales-du-monde",
    label: "Capitales du monde",
    difficultyTier: "E",
    wordsByLength: {
      4: ["APIA","BERN","DOHA","KIEV","LIMA","LOMÉ","OSLO","RIGA","ROME"],
      5: ["ABUJA","ACCRA","ALGER","ALOFI","AMMAN","BAKOU","CAIRE","DAKAR","DHAKA","HANOI","KABUL","MINSK","PARIS","PRAIA","QUITO","RABAT","RIYAD","SANAA","SOFIA","SUCRE","SÉOUL","TOKYO","TUNIS","VADUZ"],
      6: ["ANKARA","ASMARA","ASTANA","AVARUA","BAMAKO","BANGUI","BEIRUT","BERLIN","BISSAU","BOGOTA","DUBLIN","HARARE","HAVANE","KIGALI","LUANDA","LUSAKA","MADRID","MANAMA","MAPUTO","MASERU","MONACO","MOSCOU","MUSCAT","NASSAU","NIAMEY","OTTAWA","PRAGUE","SKOPJE","TIRANA","VIENNE","ZAGREB"],
      7: ["ATHÈNES","BAGHDAD","BANGKOK","BEIJING","BISHKEK","CARACAS","CAYENNE","CONAKRY","JAKARTA","KAMPALA","LONDRES","MANAGUA","MANILLE","NAIROBI","NICOSIE","PAPEETE","TALLINN","TRIPOLI","TÉHÉRAN","VILNIUS","YAOUNDÉ","YEREVAN"],
    },
  },
  {
    themeId: "fr-e-dieux-deesses",
    label: "Dieux & Déesses",
    difficultyTier: "E",
    wordsByLength: {
      4: ["ARÈS","EROS","HÉRA","ISIS","LOKI","MARS","MAÂT","ODIN","RAMA","THOR","ZEUS"],
      5: ["CIRCÉ","CÉRÈS","DIANE","FREYA","HADÈS","HORUS","JANUS","JUNON","SHIVA","VESTA","VÉNUS"],
      6: ["ANUBIS","ATHÉNA","GANESH","HERMÈS","HESTIA","ISHTAR","OSIRIS"],
      7: ["APOLLON","ARTÉMIS","DÉMÉTER","JUPITER","KRISHNA","MERCURE","MINERVE","NEPTUNE","SATURNE","VISHNOU","VULCAIN"],
    },
  },
  {
    themeId: "fr-e-groupes-celebres",
    label: "Groupes célèbres",
    difficultyTier: "E",
    wordsByLength: {
      4: ["BLUR","KISS","MUSE","RUSH"],
      5: ["OASIS","QUEEN","WILCO"],
      6: ["EAGLES","PIXIES","WEEZER"],
      7: ["BAUHAUS","GARBAGE","GENESIS","JOURNEY","MISFITS","NIRVANA","PANTERA","PLACEBO","RAINBOW","RAMONES","ROXETTE","SEETHER"],
    },
  },
  {
    themeId: "fr-e-marques-de-voiture",
    label: "Marques de voiture",
    difficultyTier: "E",
    wordsByLength: {
      4: ["AUDI","FIAT","FORD","JEEP","OPEL","SAAB","SEAT"],
      5: ["BUICK","DACIA","DODGE","HONDA","ISUZU","LEXUS","LOTUS","MAZDA","SKODA","SMART","TESLA","VOLVO"],
      6: ["AUSTIN","DAEWOO","HUMMER","JAGUAR","LANCIA","NISSAN","SUBARU","SUZUKI","TOYOTA"],
      7: ["BENTLEY","BUGATTI","CITROËN","FERRARI","HYUNDAI","MCLAREN","PEUGEOT","PONTIAC","PORSCHE","RENAULT"],
    },
  },
];
