import type { SampleThemeWords } from '../types.js';

/**
 * Generated from docs/design/word-lists — do not hand-edit.
 * Regenerate with `node scripts/generate-word-lists.mjs` after the source
 * JSON files change (rebuild the engine first: `npm run build`).
 */
export const FRENCH_WORD_LIST_THEMES: readonly SampleThemeWords[] = [
  {
    themeId: "fr-a-anatomy",
    label: "Anatomy",
    difficultyTier: "A",
    wordsByLength: {
      4: ["CILS","DENT","FOIE","IRIS","JOUE","MAIN","NERF","PEAU","RATE","REIN","SANG","SEIN"],
      5: ["AORTE","COEUR","COUDE","CRÂNE","DOIGT","FÉMUR","GENOU","GORGE","NUQUE","ONGLE","PAUME","POUCE","TALON","TIBIA","VEINE"],
      6: ["ARTÈRE","BASSIN","BOUCHE","CUISSE","GLANDE","LANGUE","LARYNX","MENTON","MOLLET","MUSCLE","NARINE","ORTEIL","OVAIRE","POUMON","RADIUS","ROTULE","RÉTINE","THORAX","TYMPAN","VESSIE"],
      7: ["ABDOMEN","CERVEAU","CHEVEUX","ESTOMAC","HUMÉRUS","OREILLE","PHARYNX","POIGNET","SOURCIL","STERNUM","TRACHÉE"],
    },
  },
  {
    themeId: "fr-a-animals",
    label: "Animals",
    difficultyTier: "A",
    wordsByLength: {
      4: ["BUSE","CERF","GRUE","IBIS","KIWI","LAMA","LION","LOUP","LYNX","MITE","PAON","PUCE","PUMA","THON","ZÉBU","ÉLAN"],
      5: ["AIGLE","BISON","CRABE","CYGNE","DINGO","GUÊPE","HIBOU","HUSKY","HYÈNE","HÉRON","KOALA","LAPIN","MORSE","MOULE","MULET","ORQUE","PANDA","PONEY","SINGE","TAPIR","TAUPE","TIGRE","TIQUE","ZÈBRE"],
      6: ["AGNEAU","AUTOUR","BAUDET","CAFARD","CAILLE","CALMAR","CANARD","CASTOR","CHACAL","CHEVAL","CHÈVRE","CIGALE","COBAYE","COUCOU","DINDON","FAISAN","FAUCON","FOURMI","FRELON","GIRAFE","HOMARD","HUÎTRE","IGUANE","JAGUAR","JUMENT","LIMACE","LOUTRE","LÉZARD","MOUTON","NARVAL","OCELOT","OURSIN","PAONNE","PHOQUE","PIGEON","PUTOIS","RENARD","REQUIN","SOURIS","TORTUE","TOUCAN","TRUITE","TÉTRAS","VIPÈRE","ÉPONGE"],
      7: ["ABEILLE","ACARIEN","BALEINE","BELETTE","CHAMOIS","CIGOGNE","COLOMBE","CORBEAU","COUGUAR","CRAPAUD","CRIQUET","DAUPHIN","GAZELLE","GORILLE","GOÉLAND","GRILLON","GRIZZLI","HAMSTER","HERMINE","LOMBRIC","LUCIOLE","LÉOPARD","MANCHOT","MOINEAU","MOUETTE","MUSTANG","OPOSSUM","PERDRIX","PIRANHA","PITBULL","PÉLICAN","SERPENT","TERMITE","VAUTOUR"],
    },
  },
  {
    themeId: "fr-a-clothes-accessories",
    label: "Clothes & Accessories",
    difficultyTier: "A",
    wordsByLength: {
      4: ["BODY","CAPE","CUIR","GANT","JEAN","JUPE","KILT","KÉPI","LOOK","MODE","PULL","ROBE","SARI","SLIP","SOIE","TUTU"],
      5: ["BOTTE","BOXER","BURQA","BÉRET","CHÂLE","COTON","DENIM","GAINE","GILET","HABIT","KIPPA","LAINE","LYCRA","MANTE","NIQAB","NOEUD","NYLON","PARKA","POCHE","SHORT","SWEAT","TENUE","VESTE","VOILE"],
      6: ["ANORAK","BASKET","BIKINI","BLAZER","BLOUSE","BONNET","BOUCLE","BOURSE","BOUTON","CAFTAN","CASQUE","CORSET","JERSEY","KIMONO","MANCHE","MASQUE","MOHAIR","PONCHO","PYJAMA","SANGLE","SARONG","TURBAN"],
      7: ["BOTTINE","CAGOULE","CALEÇON","CHAPEAU","CHEMISE","COLLANT","COLLIER","COSTUME","CRAVATE","FOULARD","HOMBURG","LEGGING","MAGENTA","MOUFLES","POLAIRE","SACOCHE","SANDALE","SMOKING","SOULIER","TABLIER","TUNIQUE","VELOURS","ÉCHARPE"],
    },
  },
  {
    themeId: "fr-a-vegetables",
    label: "Vegetables",
    difficultyTier: "A",
    wordsByLength: {
      4: ["CHOU","GUAR","MAÏS","POIS","SOJA"],
      5: ["NAVET","RADIS"],
      6: ["COURGE","CÉLERI","ENDIVE","LAITUE","MANIOC","OIGNON","PANAIS","PATATE","POUSSE","TRUFFE"],
      7: ["CAROTTE","CRESSON","FENOUIL","HARICOT","POIREAU","POIVRON","ROMAINE","ÉPINARD"],
    },
  },
  {
    themeId: "fr-a-musical-instruments",
    label: "Musical Instruments",
    difficultyTier: "A",
    wordsByLength: {
      4: ["ALTO","GONG","LUTH","LYRE","TUBA"],
      5: ["BANJO","BASSE","FLÛTE","HARPE","KAZOO","ORGUE","PIANO","SITAR"],
      6: ["BASSON","CORNET","DJEMBÉ","GRELOT","PIPEAU","VIOLON"],
      7: ["CLAVIER","CYMBALE","DARBUKA","GUITARE","MARIMBA","OCARINA","TAMBOUR","UKULÉLÉ"],
    },
  },
  {
    themeId: "fr-a-occupations",
    label: "Occupations",
    difficultyTier: "A",
    wordsByLength: {
      4: ["CHEF","JUGE"],
      5: ["BONNE","COACH","GARDE","GUIDE","MAIRE","MARIN","MAÇON","MOINE","POÈTE","REINE","SCOUT","VALET","VOYOU","ÉLÈVE"],
      6: ["ACTEUR","ARCHER","AUTEUR","BARMAN","CONSUL","DÉPUTÉ","ESPION","EXPERT","GÉRANT","JOCKEY","MAÎTRE","MINEUR","MODÈLE","NAGEUR","PILOTE","PRINCE","PRÊTRE","RABBIN","SCRIBE","SHÉRIF","SOLDAT","TRADER","VOLEUR"],
      7: ["ARBITRE","ARTISTE","ATHLÈTE","ATTACHÉ","BARBIER","BATTEUR","BOUCHER","BOUFFON","CUISTOT","DACTYLO","EMPLOYÉ","FACTEUR","FERMIER","GARDIEN","GEÔLIER","GOLFEUR","GÉNÉRAL","HÔTESSE","LIVREUR","MÉDECIN","ORFÈVRE","OUVRIER","PASTEUR","PEINTRE","POMPIER","PORTIER","PÊCHEUR","ROUTIER","SERVEUR","SOUDEUR","STEWARD","VENDEUR","VICAIRE","VÉTÉRAN","ÉDITEUR","ÉLEVEUR"],
    },
  },
  {
    themeId: "fr-a-sports",
    label: "Sports",
    difficultyTier: "A",
    wordsByLength: {
      4: ["AXEL","BOXE","CLUB","GOLF","HAIE","JUDO","LUGE","POLO","SAUT","SURF"],
      5: ["CATCH","LIGUE","PALET","PATIN","POIDS","RUGBY"],
      6: ["AVIRON","BALLON","BOULES","COURSE","CROSSE","HOCKEY","JOUEUR","KARATÉ","MARCHE","PERCHE","RALLYE","RELAIS","SLALOM","SPRINT","SQUASH","TENNIS","VOLLEY","ÉQUIPE"],
      7: ["BOWLING","CERCEAU","COUREUR","CRICKET","CROQUET","CURLING","ESCRIME","GUICHET","JOGGEUR","MAILLET","PARKOUR","PLONGÉE","RAFTING"],
    },
  },
  {
    themeId: "fr-a-modes-of-transport",
    label: "Modes of Transport",
    difficultyTier: "A",
    wordsByLength: {
      4: ["AUTO","JEEP","LIMO","MOTO","TAXI","VÉLO"],
      5: ["AVION","BUGGY","CANOË","FERRY","FUSÉE","MÉTRO","TRAIN","WAGON","YACHT"],
      6: ["BATEAU","CAMION","GALÈRE","HÉLICO","NAVIRE"],
      7: ["BERLINE","CALÈCHE","CHARIOT","FRÉGATE","GONDOLE","LITIÈRE","MINIBUS","PLANEUR","PÉNICHE","SCOOTER","TRAMWAY","VOITURE"],
    },
  },
  {
    themeId: "fr-a-countries",
    label: "Countries",
    difficultyTier: "A",
    wordsByLength: {
      4: ["CUBA","INDE","IRAK","IRAN","LAOS","MALI","NIUE","OMAN","TOGO"],
      5: ["BÉNIN","CHILI","CHINE","CONGO","FIDJI","GABON","GHANA","GRÈCE","HAÏTI","JAPON","KENYA","LIBAN","LIBYE","MALTE","MAROC","NAURU","NIGER","NÉPAL","PÉROU","QATAR","SAMOA","SUÈDE","SYRIE","TCHAD","TONGA","YÉMEN"],
      6: ["ANGOLA","BELIZE","BOSNIE","BRUNEI","BRÉSIL","CANADA","CHYPRE","FRANCE","GAMBIE","GUINÉE","GUYANA","ISRAËL","ITALIE","KOSOVO","KOWEÏT","MALAWI","MONACO","PALAOS","PANAMA","RUSSIE","RWANDA","SERBIE","SOUDAN","SUISSE","TAÏWAN","TUVALU","ZAMBIE","ÉGYPTE"],
      7: ["ALBANIE","ALGÉRIE","ANDORRE","ANTIGUA","ARMÉNIE","BAHAMAS","BAHREÏN","BARBADE","BHOUTAN","BOLIVIE","BURUNDI","COMORES","CROATIE","ESPAGNE","ESTONIE","GÉORGIE","HONGRIE","IRLANDE","ISLANDE","LESOTHO","LIBÉRIA","MAURICE","MEXIQUE","MYANMAR","NAMIBIE","NIGÉRIA","NORVÈGE","OUGANDA","POLOGNE","SOMALIE","SÉNÉGAL","TUNISIE","TURQUIE","UKRAINE","URUGUAY","VANUATU","VIETNAM"],
    },
  },
  {
    themeId: "fr-a-vegan-food",
    label: "Vegan Food",
    difficultyTier: "A",
    wordsByLength: {
      4: ["ANIS","NOIX","THYM","TOFU"],
      5: ["CAJOU","CARVI","CUMIN","GLAND","PENNE","PÂTES","SAUGE","SUMAC"],
      6: ["AMANDE","MENTHE","ORIGAN","PERSIL","POIVRE","QUINOA","SAFRAN","SEITAN","SÉSAME","WASABI"],
      7: ["BASILIC","CHUTNEY","GIROFLE","KETCHUP","PAPRIKA"],
    },
  },
  {
    themeId: "fr-a-non-vegan-food",
    label: "Non-Vegan Food",
    difficultyTier: "A",
    wordsByLength: {
      4: ["PORC","VEAU"],
      5: ["BACON","BOEUF","STEAK"],
      6: ["BEURRE","CAVIAR","GIBIER","JAMBON","POULET","SAUMON"],
      7: ["ANCHOIS","CHEDDAR","CHORIZO","FROMAGE","SARDINE"],
    },
  },
  {
    themeId: "fr-b-alcoholic-drinks",
    label: "Alcoholic Drinks",
    difficultyTier: "B",
    wordsByLength: {
      4: ["ARAK","GROG","OUZO","RAKI","RHUM","SAKÉ"],
      5: ["BIÈRE","CIDRE","LAGER","PORTO","PUNCH","VODKA","XÉRÈS"],
      6: ["BRANDY","COGNAC","GRAPPA","KIRSCH","MOJITO","PASTIS","WHISKY"],
      7: ["BOURBON","CACHACA","LIQUEUR","MARTINI","MASTIKA","SAMBUCA","SANGRIA","TEQUILA"],
    },
  },
  {
    themeId: "fr-b-hand-tools",
    label: "Hand Tools",
    difficultyTier: "B",
    wordsByLength: {
      4: ["CLEF","CLOU","SCIE"],
      5: ["COLLE","FORET","PINCE","RABOT","RÈGLE"],
      6: ["CISEAU","NIVEAU"],
      7: ["ENCLUME","MARTEAU","PINCEAU"],
    },
  },
  {
    themeId: "fr-b-furniture",
    label: "Furniture",
    difficultyTier: "B",
    wordsByLength: {
      4: ["BANC","POUF","SOFA"],
      5: ["FUTON","HAMAC","TABLE","TRÔNE"],
      6: ["BUFFET","BUREAU","CANAPÉ","CHAISE","COFFRE"],
      7: ["BERCEAU","COMMODE","JUKEBOX","MATELAS","PLACARD","ÉTAGÈRE"],
    },
  },
  {
    themeId: "fr-b-tableware-kitchen-utensils",
    label: "Tableware & Kitchen Utensils",
    difficultyTier: "B",
    wordsByLength: {
      4: ["FOUR","GRIL","RÂPE"],
      5: ["FOUET","FRIGO","PIQUE","POÊLE","ROBOT","TAMIS","VERRE","ÉVIER"],
      6: ["BOUGIE","CARAFE","FLEURS","LOUCHE","MIXEUR","MOULIN","PANIER","PICHET","PINCES"],
      7: ["BALANCE","CISEAUX","COUTEAU","CUILLER","MARMITE","PLANCHA","PLANCHE","PLATEAU","SPATULE","THÉIÈRE","TORCHON","ZESTEUR"],
    },
  },
  {
    themeId: "fr-b-flowers",
    label: "Flowers",
    difficultyTier: "B",
    wordsByLength: {
      4: ["ARUM","ROSE","TIGE"],
      5: ["GENÊT","LILAS","PAVOT","ÉPINE"],
      6: ["AZALÉE","BLEUET","DAHLIA","JASMIN","MIMOSA","MUGUET","PENSÉE","PISTIL","PÉTALE","TULIPE"],
      7: ["BÉGONIA","CAMÉLIA","CHARDON","FEUILLE","GLAÏEUL","PIVOINE","SERINGA"],
    },
  },
  {
    themeId: "fr-b-bodies-of-water",
    label: "Bodies of Water",
    difficultyTier: "B",
    wordsByLength: {
      4: ["BAIE","MARE"],
      5: ["CANAL","FJORD","GOLFE","OASIS","OCÉAN","ÉTANG"],
      6: ["CRIQUE","FLAQUE","FLEUVE","LAGUNE","MARAIS","RAPIDE","SOURCE"],
      7: ["CASCADE","GLACIER","ICEBERG","RIVIÈRE","TORRENT"],
    },
  },
  {
    themeId: "fr-b-plants-and-trees",
    label: "Plants and Trees",
    difficultyTier: "B",
    wordsByLength: {
      4: ["ORME","PORE"],
      5: ["AULNE","BULBE","CHÊNE","CÈDRE","FLEUR","FRUIT","NOYAU","SAPIN","SAULE"],
      6: ["ACACIA","CYPRÈS","GRAINE","NECTAR","POLLEN","RACINE","ÉRABLE"],
      7: ["BOULEAU","BRANCHE","COROLLE","PLATANE","SÉQUOIA","TILLEUL","ÉTAMINE"],
    },
  },
  {
    themeId: "fr-c-jewelry-accessories",
    label: "Jewelry & Accessories",
    difficultyTier: "C",
    wordsByLength: {
      4: ["JADE","ONYX"],
      5: ["AGATE","AMBRE","BAGUE","BÉRYL","CAMÉE","JASPE","OPALE","PERLE","RUBIS","TIARE"],
      6: ["ARGENT","BROCHE","CHAÎNE","GRENAT","QUARTZ","SAPHIR","TOPAZE","ZIRCON"],
      7: ["APATITE","AZURITE","CITRINE","CRISTAL","DIADÈME","DIAMANT"],
    },
  },
  {
    themeId: "fr-c-weaponry",
    label: "Weaponry",
    difficultyTier: "C",
    wordsByLength: {
      4: ["ARME","MINE","ÉPÉE"],
      5: ["BALLE","BOMBE","CANON","FUSIL","LANCE","SABRE"],
      6: ["FLÈCHE"],
      7: ["MISSILE","MORTIER"],
    },
  },
  {
    themeId: "fr-c-sweets-and-desserts",
    label: "Sweets and Desserts",
    difficultyTier: "C",
    wordsByLength: {
      4: ["FLAN","MIEL"],
      5: ["CRÊPE","FUDGE","GELÉE","GLACE","SCONE","TARTE"],
      6: ["BONBON","CHURRO","GAUFRE","MOUSSE","MUFFIN","NOUGAT","SORBET","ÉCLAIR"],
      7: ["BAKLAVA","BEIGNET","BISCUIT","BROWNIE","CANNELÉ","CARAMEL","COMPOTE","CUPCAKE","GLAÇAGE","MACARON","PARFAIT","PRALINE","PUDDING","SOUFFLÉ","STRUDEL"],
    },
  },
  {
    themeId: "fr-c-time-timekeeping",
    label: "Time & Timekeeping",
    difficultyTier: "C",
    wordsByLength: {
      4: ["MOIS","TARD","ZONE"],
      5: ["ALORS","ANNÉE","APRÈS","AVANT","DURÉE","DÉLAI","FUTUR","HEURE","MATIN","PASSÉ"],
      6: ["ACTUEL","ANNUEL","JUBILÉ","MINUTE","MOMENT","RETARD","SAISON","SIÈCLE","ÉPOQUE"],
      7: ["BIENTÔT","HORAIRE","INSTANT","PRÉSENT","PÉRIODE","SECONDE","SEMAINE"],
    },
  },
  {
    themeId: "fr-c-sports-facilities",
    label: "Sports Facilities",
    difficultyTier: "C",
    wordsByLength: {
      4: ["DOJO","RING"],
      5: ["ARÈNE","COURT","PISTE","SALLE","STADE"],
      6: ["TATAMI","ÉCURIE"],
      7: ["CIRCUIT","GYMNASE","PISCINE","TERRAIN"],
    },
  },
  {
    themeId: "fr-d-musical-styles",
    label: "Musical Styles",
    difficultyTier: "D",
    wordsByLength: {
      4: ["ACID","FOLK","FUNK","JAZZ","PUNK","ROCK","SOCA","SOUL","ZOUK"],
      5: ["BLUES","CONGA","DISCO","HOUSE","MAMBO","MÉTAL","OPÉRA","RUMBA","SALSA","SAMBA","SWING","TANGO","VALSE"],
      6: ["BOLÉRO","GOSPEL","GRUNGE","MOTOWN","REGGAE","TECHNO","TRANSE"],
      7: ["BAROQUE","BRITPOP","CALYPSO","COUNTRY","DUBSTEP","RAGTIME"],
    },
  },
  {
    themeId: "fr-d-light-sources",
    label: "Light Sources",
    difficultyTier: "D",
    wordsByLength: {
      4: ["LAVE","LUNE","NÉON"],
      5: ["FLASH","LAMPE","LASER","LUEUR","PHARE"],
      6: ["BRAISE","COMÈTE","FLAMME","SOLEIL","TORCHE","ÉTOILE"],
      7: ["AMPOULE","BRIQUET","MÉTÉORE"],
    },
  },
  {
    themeId: "fr-d-leaders",
    label: "Leaders",
    difficultyTier: "D",
    wordsByLength: {
      4: ["CHAH","DOGE","KHAN","PAPE","TSAR","ÉMIR"],
      5: ["BARON","COMTE","NÉGUS","TYRAN","VIZIR"],
      6: ["CALIFE","CHEIKH","GOUROU","RÉGENT","SHOGUN","SULTAN"],
      7: ["INFANTE","PHARAON","TSARINE"],
    },
  },
  {
    themeId: "fr-d-car-parts",
    label: "Car Parts",
    difficultyTier: "D",
    wordsByLength: {
      4: ["PNEU","ROUE"],
      5: ["BOÎTE","CAPOT","JAUGE","JOINT","PORTE","RÉTRO","VITRE"],
      6: ["AIRBAG","ALARME","ESSIEU","FILTRE","FREINS","JANTES","LEVIER","MOTEUR","PISTON","PÉDALE","VOLANT"],
      7: ["AILERON","CAPTEUR","CHÂSSIS","CONSOLE","ESSENCE","FUSIBLE","SERRURE"],
    },
  },
  {
    themeId: "fr-d-animal-body-parts",
    label: "Animal Body Parts",
    difficultyTier: "D",
    wordsByLength: {
      4: ["AILE","BRAS","CROC","DARD"],
      5: ["BOSSE","CORNE","ERGOT","PATTE","PLUME","QUEUE","SABOT","TACHE"],
      6: ["MUSEAU","PATTES","PELAGE","TROMPE"],
      7: ["ANTENNE","DÉFENSE","ÉCAILLE"],
    },
  },
  {
    themeId: "fr-d-the-calendar",
    label: "The Calendar",
    difficultyTier: "D",
    wordsByLength: {
      4: ["AOÛT","JUIN","MARS"],
      5: ["AVRIL","JEUDI","LUNDI","MARDI"],
      6: ["BÉLIER","CANCER","SAMEDI","VIERGE"],
      7: ["FÉVRIER","GÉMEAUX","JANVIER","JUILLET","OCTOBRE","TAUREAU"],
    },
  },
  {
    themeId: "fr-d-famous-brands",
    label: "Famous Brands",
    difficultyTier: "D",
    wordsByLength: {
      4: ["ACER","AVON","BOSE","DELL","DIOR","DOVE","FILA","FUJI","LEGO","NIKE","OLAY","OREO","SONY","TWIX","VISA"],
      5: ["APPLE","ASICS","CASIO","CREST","DOLBY","EVIAN","FANTA","GUCCI","HALLS","HEINZ","KNORR","KRAFT","LINDT","MAGGI","NIKON","NIVEA","NOKIA","PEPSI","PRADA","ROLEX","SANYO","SHARP","TEFAL","TWIRL","UMBRO","VICHY","WELLA","XEROX"],
      6: ["ADIDAS","ARMANI","BOUNTY","CHANEL","CRUNCH","DANONE","GALAXY","GIBSON","GODIVA","HENKEL","HERMES","HOOVER","LIPTON","LOREAL","MATTEL","MENTOS","RAYBAN","REEBOK","REVLON","REXONA","SIGNAL","SMACKS","SPRITE","TAMPAX","VIAGRA"],
      7: ["AIRNESS","BARILLA","BUITONI","CADBURY","CARTIER","CLARINS","COLGATE","CRAYOLA","GRUNDIG","HISENSE","KENWOOD","KICKERS","KLEENEX","LACOSTE","LANCOME","MAIZENA","MIRINDA","NESCAFE","NUTELLA","PAMPERS","PANTENE","PERRIER","PHILIPS","SAMSUNG","SUNSILK","TOSHIBA","VERSACE"],
    },
  },
  {
    themeId: "fr-d-music",
    label: "Music",
    difficultyTier: "D",
    wordsByLength: {
      4: ["NOTE","SOLO","TRIO"],
      5: ["GAMME","HYMNE","TEMPO","THÈME","TÉNOR"],
      6: ["ACCORD","ADAGIO","ATONAL","AUBADE","CHOEUR","GROUPE","MESURE","OCTAVE","RYTHME","TIMBRE","VOLUME"],
      7: ["BALLADE","CADENCE","CANTATE","CHANSON","CONCERT","MÉLODIE","QUATUOR","RÉCITAL","SILENCE","SOLFÈGE","SOPRANO","UNISSON"],
    },
  },
  {
    themeId: "fr-e-colors",
    label: "Colors",
    difficultyTier: "E",
    wordsByLength: {
      4: ["AQUA","AZUR","BLEU","CYAN","GRIS","KAKI","NOIR","OCRE","VERT"],
      5: ["BEIGE","BLANC","CRÈME","JAUNE","MAUVE","SÉPIA"],
      6: ["CUIVRE","INDIGO","IVOIRE","MARRON","VIOLET"],
      7: ["AMAZONE","FUCHSIA","POURPRE"],
    },
  },
  {
    themeId: "fr-e-chemical-elements",
    label: "Chemical Elements",
    difficultyTier: "E",
    wordsByLength: {
      4: ["BORE","IODE","ZINC"],
      5: ["ARGON","AZOTE","BROME","FLUOR","PLOMB","RADON","XÉNON"],
      6: ["BARYUM","CHLORE","COBALT","CURIUM","CÉRIUM","ERBIUM","HÉLIUM","INDIUM","NICKEL","RADIUM","SODIUM","SOUFRE","TITANE"],
      7: ["ARSENIC","BISMUTH","BOHRIUM","CADMIUM","CALCIUM","CARBONE","DUBNIUM","IRIDIUM","KRYPTON","LITHIUM","MERCURE","OXYGÈNE","THORIUM","URANIUM"],
    },
  },
  {
    themeId: "fr-e-lakes-and-rivers",
    label: "Lakes and Rivers",
    difficultyTier: "E",
    wordsByLength: {
      4: ["ERIE","NESS","RHIN"],
      5: ["GANGE","HURON","INDUS","LOIRE","LÉMAN","SAÔNE","SEINE","VOLGA","VOLTA"],
      6: ["BAÏKAL","DANUBE","LOMOND","MÉKONG","TAMISE"],
      7: ["GARONNE","MOSELLE","ONTARIO","VISTULE","WHEATON","YANGTSÉ","ZAMBÈZE"],
    },
  },
  {
    themeId: "fr-e-currencies",
    label: "Currencies",
    difficultyTier: "E",
    wordsByLength: {
      4: ["BAHT","DIME","DRAM","EURO","HWAN","INTI","KUNA","LIRE","MARK","PESO","REAL","SHAH","YANG","YUAN"],
      5: ["BUDJU","DINAR","DUCAT","FRANC","KRONA","LIBRA","LIVRE","PAISA","RIYAL","SCUDO","SUCRE","ZLOTY"],
      6: ["DENIER","DINERO","DIRHAM","DOLLAR","ESCUDO","FLORIN","GINEIH","KORUNA","PESETA","ROUBLE","ROUPIE","SHEKEL","TANGKA","THALER"],
      7: ["AFGHANI","AUSTRAL","BOLIVAR","CENTIME","CRUZADO","DRACHME","PENNING","PIASTRE","RINGGIT"],
    },
  },
  {
    themeId: "fr-e-languages",
    label: "Languages",
    difficultyTier: "E",
    wordsByLength: {
      4: ["GREC","MAYA","THAÏ","TURC"],
      5: ["ARABE","CORSE","HAKKA","HINDI","KURDE","MAORI","RUSSE","SERBE","SWATI","WOLOF","XIANG"],
      6: ["BASQUE","BIRMAN","BRETON","CORÉEN","DANOIS","FRISON","HÉBREU","KAZAKH","LETTON","MALAIS","OURDOU","OUZBEK","PERSAN","SOMALI","TADJIK","TAMOUL","ZOULOU"],
      7: ["ABKHAZE","ANGLAIS","BENGALI","BERBÈRE","BOSNIEN","CATALAN","CHINOIS","FINNOIS","GALLOIS","ITALIEN","LAOTIEN","MALTAIS","OCCITAN","QUECHUA","SLOVÈNE","SUÉDOIS","SWAHILI","TCHÈQUE","YIDDISH"],
    },
  },
  {
    themeId: "fr-e-african-cities",
    label: "African Cities",
    difficultyTier: "E",
    wordsByLength: {
      4: ["KANO","LAMU","LOMÉ","MAUN","SUEZ"],
      5: ["ACCRA","AKURE","ALGER","CAIRE","DAKAR","GIZEH","LAGOS","RABAT","TUNIS","WARRI"],
      6: ["AGADIR","BANGUI","DOUALA","DURBAN","HARARE","IBADAN","ILORIN","KADUNA","KIGALI","KUMASI","LUSAKA","MATOLA","NIAMEY","SOWETO","TANGER"],
      7: ["ABIDJAN","CONAKRY","KAMPALA","MOMBASA","NAIROBI","TRIPOLI","YAOUNDÉ"],
    },
  },
  {
    themeId: "fr-e-asian-cities",
    label: "Asian Cities",
    difficultyTier: "E",
    wordsByLength: {
      4: ["ALEP","DOHA","XIAN"],
      5: ["DELHI","DHAKA","DUBAI","HANOI","KABUL","KYOTO","OSAKA","RIYAD","SANAA","SURAT","SÉOUL","TOKYO","WUHAN"],
      6: ["ANKARA","BEIRUT","BOMBAY","JAIPUR","LAHORE","MADRAS","MOSCOU"],
      7: ["BAGHDAD","BANGKOK","BEIJING","BISHKEK","DJEDDAH","JAKARTA","KARACHI","MANILLE","MASHHAD","MOSSOUL","RANGOUN","TIANJIN","TÉHÉRAN"],
    },
  },
  {
    themeId: "fr-e-european-cities",
    label: "European Cities",
    difficultyTier: "E",
    wordsByLength: {
      4: ["BALE","BONN","HAMM","LYON","NICE","RIGA","ROME","VIGO","YORK"],
      5: ["BRAGA","BREDA","BREST","BRÊME","DIJON","ESPOO","ESSEN","GÊNES","LAHTI","LEEDS","LILLE","LIÈGE","MILAN","NAMUR","PARIS","REIMS","SOFIA","TURIN","VARNA"],
      6: ["ANGERS","ANVERS","BERLIN","BOLTON","BRUGES","CANNES","CATANE","DRESDE","DUBLIN","DUDLEY","FOGGIA","KAUNAS","MADRID","MALAGA","MUNICH","NANTES","NAPLES","PADOUE","PRAGUE","RENNES","RIJEKA","SLOUGH","TOULON","VENISE","VIENNE","VÉRONE","ZURICH"],
      7: ["ATHÈNES","BELFAST","BOLOGNE","BRESCIA","BRISTOL","CARDIFF","COLOGNE","CORDOUE","CRAIOVA","GLASGOW","HAARLEM","HANOVRE","LEIPZIG","LONDRES","NEWPORT","NICOSIE","PALERME","RAVENNE","ROSTOCK","SALERNE","SÉVILLE","TALLINN","TAMPERE","VILNIUS"],
    },
  },
  {
    themeId: "fr-e-south-american-cities",
    label: "South-American Cities",
    difficultyTier: "E",
    wordsByLength: {
      4: ["CALI","LEON","LIMA"],
      5: ["BÉLEM","CUZCO","NATAL","QUITO"],
      6: ["BOGOTA","MANAUS","RECIFE","SANTOS"],
      7: ["CARACAS","IQUIQUE","MARACAY","MENDOZA","ROSARIO"],
    },
  },
  {
    themeId: "fr-e-world-cities",
    label: "World Cities",
    difficultyTier: "E",
    wordsByLength: {
      4: ["BERN","KIEV","OMSK","OSLO","PISE"],
      5: ["AMMAN","BAKOU","LUXOR","MINSK"],
      6: ["ASMARA","ASTANA","BAMAKO","BILBAO","BISSAU","LUANDA","MANAMA","MAPUTO","MASERU","MECQUE","MUMBAI","OXFORD","RHODES","SYDNEY","TAIPEI","ZAGREB"],
      7: ["ATLANTA","CAYENNE","CHESTER","KOLKATA","LARNACA","MEMPHIS","MYKONOS","ORLANDO","PAPEETE","YEREVAN"],
    },
  },
  {
    themeId: "fr-e-god-goddesses",
    label: "God & Goddesses",
    difficultyTier: "E",
    wordsByLength: {
      4: ["ARÈS","HÉRA","ISIS","LOKI","ODIN","RAMA","THOR","ZEUS"],
      5: ["CIRCÉ","CÉRÈS","DIANE","FREYA","HADÈS","JANUS","JUNON","SHIVA","VESTA","VÉNUS"],
      6: ["ANUBIS","ATHÉNA","HESTIA","ISHTAR","OSIRIS"],
      7: ["APOLLON","ARTÉMIS","DÉMÉTER","JUPITER","KRISHNA","MINERVE","NEPTUNE","SATURNE","VISHNOU","VULCAIN"],
    },
  },
  {
    themeId: "fr-e-famous-bands",
    label: "Famous Bands",
    difficultyTier: "E",
    wordsByLength: {
      4: ["BLUR","KISS","MUSE","RUSH","TOOL","TOTO"],
      5: ["QUEEN","WILCO"],
      6: ["PIXIES","WEEZER"],
      7: ["BAUHAUS","GARBAGE","GENESIS","JOURNEY","MISFITS","NIRVANA","PANTERA","PLACEBO","RAINBOW","RAMONES","ROXETTE","SEETHER"],
    },
  },
  {
    themeId: "fr-e-car-manufacturers",
    label: "Car Manufacturers",
    difficultyTier: "E",
    wordsByLength: {
      4: ["AUDI","FIAT","FORD","OPEL","SAAB","SEAT"],
      5: ["BUICK","DACIA","DODGE","HONDA","ISUZU","LEXUS","LOTUS","MAZDA","SKODA","SMART","TESLA","VOLVO"],
      6: ["DAEWOO","HUMMER","LANCIA","NISSAN","SUBARU","SUZUKI","TOYOTA"],
      7: ["BENTLEY","BUGATTI","CITROËN","FERRARI","HYUNDAI","PEUGEOT","PONTIAC","PORSCHE","RENAULT"],
    },
  },
];
